/**
 * Canonical list of the 13 Tumaini · TBHOS modules.
 * Single source of truth for the nav, landing grid, and module pages.
 */
import { JEWEL } from './glass'
import type { LifecycleStageId } from './lifecycle'

export interface ModuleDef {
  slug: string
  name: string         // Swahili name (display)
  english: string      // English helper for accessibility
  tagline: string      // Short Swahili line
  description: string  // Single-line description for the card
  features: string[]   // Sub-features (Swahili) — shown as "Inakuja" stubs
  accent: string       // Jewel hex for the card stripe
  glyph: string        // Unicode-safe label glyph (one or two letters)
  /** Lifecycle stages this module touches. 'all' = ministry-grade / cross-cutting. */
  stages: readonly LifecycleStageId[] | 'all'
}

export const MODULES: ModuleDef[] = [
  {
    slug: 'mimi',
    name: 'Mimi',
    english: 'Patient — Me',
    tagline: 'Safari yako ya roho.',
    description: 'Tathmini, hisia, malengo, na rekodi yako binafsi.',
    features: [
      'PHQ-9 · GAD-7 · PCL-5 (Kiswahili)',
      'Diary ya hisia na vichocheo',
      'Malengo binafsi na hatua za siku',
      'Faragha kamili — data yako ni yako',
      'Onyo la dharura na C-SSRS',
    ],
    accent: JEWEL.tealRoho,
    glyph: 'Mi',
    stages: ['tambua', 'tathmini', 'tiba', 'upyaji', 'uendelevu'],
  },
  {
    slug: 'roho',
    name: 'Mwenza',
    english: 'AI Companion',
    tagline: 'Rafiki wako wa polepole.',
    description: 'AI yetu yenyewe — Kiswahili kabisa, bila mtoa-huduma wa nje.',
    features: [
      'Mwenza · Mfunzi · Mlinzi · Mwandishi · Mhakiki · Mkumbusha',
      'Sauti — Sikiliza ASR + Kasuku Lugha TTS',
      'Wataalam 14 wa ndani (triage, CBT, MI, crisis…)',
      'Picha, sauti, hati — multimodal',
      'Hakuna LLM ya nje. Sovereign.',
    ],
    accent: JEWEL.goldHope,
    glyph: 'Ro',
    stages: 'all',
  },
  {
    slug: 'wataalam',
    name: 'Wataalam',
    english: 'Providers',
    tagline: 'Madaktari, washauri, wahudumu wa imani.',
    description: 'Anzisha kliniki ya kibinafsi — bure, kabisa virtual au ana kwa ana.',
    features: [
      'Caseload, ratiba, video, malipo',
      'Vyeti na uthibitisho wa MUHAS/MoH',
      'Maelekezo ya kitabibu (TibaAI-port)',
      'Ushirikiano na mhudumu wa imani',
      'Faili za EHR-fupi za tabia',
    ],
    accent: JEWEL.indigoWisdom,
    glyph: 'Wa',
    stages: ['tathmini', 'hatua', 'tiba', 'dharura', 'upyaji'],
  },
  {
    slug: 'gundua',
    name: 'Gundua',
    english: 'Discover',
    tagline: 'Tafuta msaada karibu nawe.',
    description: 'Ramani ya wataalam, vikundi, na huduma jirani.',
    features: [
      'Ramani ya watoa-huduma kwa wilaya',
      'Vikundi vya msaada (peer support)',
      'Filta kwa lugha, gharama, jinsia',
      'Tathmini za jamii',
      'Wasiliana kwa siri',
    ],
    accent: JEWEL.tealRoho,
    glyph: 'Gu',
    stages: ['kukuza', 'kinga', 'tambua'],
  },
  {
    slug: 'huduma',
    name: 'Huduma',
    english: 'Catalogue',
    tagline: 'Katalogi ya huduma zote.',
    description: 'Yote yanayopatikana — kwa wewe, kwa familia, kwa jamii.',
    features: [
      'Mistari ya dharura (24/7)',
      'Kliniki za umma na binafsi',
      'NGO na vikundi vya imani',
      'Mafunzo na warsha',
      'Rasilimali za bure',
    ],
    accent: JEWEL.goldHope,
    glyph: 'Hu',
    stages: 'all',
  },
  {
    slug: 'miradi',
    name: 'Miradi',
    english: 'Programs',
    tagline: 'Mipango iliyothibitishwa.',
    description: 'PM+ · CETA · IPT · t-CBT · MI · PST · DBT-lite · MBSR · Faith.',
    features: [
      'Problem Management Plus (WHO)',
      'CETA — common elements',
      'Tiba inayotegemea utafiti',
      'Vikao vya kibinafsi au kikundi',
      'Ufuatiliaji wa maendeleo',
    ],
    accent: JEWEL.indigoWisdom,
    glyph: 'Mr',
    stages: ['hatua', 'tiba', 'upyaji'],
  },
  {
    slug: 'maalum',
    name: 'Maalum',
    english: 'Specialized',
    tagline: 'Kwa kila hali maalum.',
    description: 'HIV, saratani, mama-mtoto, watoto, wazee, walevi, wakimbizi, magereza.',
    features: [
      'Afya ya akili na HIV',
      'Tegemeo la saratani',
      'Perinatal — kabla na baada ya kuzaa',
      'Walevi na vichocheo',
      'Wakimbizi na walio kwenye mfungwa',
    ],
    accent: JEWEL.maroonCrisis,
    glyph: 'Ma',
    stages: ['kinga', 'tambua', 'tiba', 'upyaji', 'uendelevu'],
  },
  {
    slug: 'shuleplus',
    name: 'Shule+',
    english: 'Schools',
    tagline: 'Afya ya akili shuleni.',
    description: 'Walimu, wanafunzi, na wazazi — mtandao mmoja.',
    features: [
      'Tathmini ya SDQ na PSC',
      'Mafunzo kwa walimu',
      'Vikundi vya wanafunzi',
      'Mawasiliano salama na wazazi',
      'Rasilimali za madarasa',
    ],
    accent: JEWEL.tealRoho,
    glyph: 'Sh',
    stages: ['kukuza', 'kinga', 'tambua', 'hatua'],
  },
  {
    slug: 'wafanyakazi',
    name: 'Wafanyakazi',
    english: 'Workforce / EAP',
    tagline: 'Programu ya msaada kazini.',
    description: 'EAP kwa makampuni — wafanyakazi wenye afya wakitoa zaidi.',
    features: [
      'Tathmini ya mafadhaiko kazini',
      'Vikao vya kibinafsi vya siri',
      'Ripoti za jumla kwa kampuni',
      'Mafunzo ya viongozi',
      'Mstari wa dharura wa kazini',
    ],
    accent: JEWEL.indigoWisdom,
    glyph: 'Wf',
    stages: ['kinga', 'tambua', 'hatua', 'tiba'],
  },
  {
    slug: 'mashirika',
    name: 'Mashirika',
    english: 'Interop',
    tagline: 'Daraja la mfumo wa afya.',
    description: 'Ushirikiano na THOS, NHIF, M-Pesa, na ICD-11.',
    features: [
      'SMART-on-FHIR na THOS',
      'NHIF claims za afya ya akili',
      'M-Pesa kwa malipo',
      'ICD-11 coding',
      'API ya watengenezaji',
    ],
    accent: JEWEL.goldHope,
    glyph: 'Mh',
    stages: 'all',
  },
  {
    slug: 'utafiti',
    name: 'Utafiti',
    english: 'Research',
    tagline: 'Tafiti za kimaadili na za kisayansi.',
    description: 'IRB-gated — uchunguzi wa PhD na wenzake.',
    features: [
      'Idhini ya washiriki (e-consent)',
      'Kuchukua data ya uchunguzi',
      'CFIR + RE-AIM frameworks',
      'Ufuatiliaji wa PHQ-9 (msingi)',
      'Ripoti za IRB na MUHAS',
    ],
    accent: JEWEL.tealRoho,
    glyph: 'Ut',
    stages: 'all',
  },
  {
    slug: 'sera',
    name: 'Sera',
    english: 'Policy & Ministry',
    tagline: 'Wizarani na bungeni.',
    description: 'Ramani ya mikoa, mlinganisho wa wilaya, mikataba ya MoH, na ripoti za bunge.',
    features: [
      'Ramani ya kitaifa — mikoa 26',
      'Mlinganisho wa mikoa (PHQ-9, ufikiaji, matokeo)',
      'Hali ya makubaliano ya MoH kwa wilaya',
      'Ripoti za robo-mwaka kwa Bunge (DOCX/PDF)',
      'Ubao wa wazi kwa wizara na Bunge',
    ],
    accent: JEWEL.indigoWisdom,
    glyph: 'Se',
    stages: 'all',
  },
  {
    slug: 'pumzi',
    name: 'Pumzi',
    english: 'Breathing',
    tagline: 'Pumzi yako, utulivu wako.',
    description: 'Mafunzo ya kupumua yaliyothibitishwa kisayansi.',
    features: [
      '4-7-8 (Weil)',
      'Sanduku 4-4-4-4 (SEAL)',
      'Mlinganisho 5-5 (HRV)',
      'Nadi Shodhana (pua mbili)',
      'Ujjayi · Bhastrika · Wim Hof · Midomo',
    ],
    accent: JEWEL.tealMwenza,
    glyph: 'Pu',
    stages: ['kinga', 'tambua', 'hatua', 'tiba', 'upyaji'],
  },
  {
    slug: 'ndani',
    name: 'Ndani',
    english: 'Admin',
    tagline: 'Uongozi wa ndani.',
    description: 'Idara ya ndani — uongozi, ukaguzi, faragha.',
    features: [
      'Uongozi wa watumiaji na RBAC',
      'Ukaguzi wa matumizi',
      'Faragha na uthibitisho',
      'Vipimo vya mfumo',
      'Maagizo ya mfumo',
    ],
    accent: JEWEL.maroonCrisis,
    glyph: 'Nd',
    stages: 'all',
  },
]
