/**
 * TibaHub Knowledge Base — Outbreaks & Infectious Disease Alerts v2.0
 * Built by Naim Systems
 *
 * Sources: Tanzania MOH Outbreak Guidelines, WHO Regional Africa,
 * CDC Tanzania, NIMR Tanzania, WHO Disease Outbreak News
 *
 * Coverage: 12 outbreak-prone conditions in Tanzania
 * Each entry includes:
 *   — How to recognise it
 *   — How it spreads (prevention-focused)
 *   — What to do immediately
 *   — Community response guidance
 *   — Full bilingual (English + Kiswahili)
 */

import type { AIResult } from '../../adapters/legacyTypes';

// ── Outbreak alias map ─────────────────────────────────────────────────────────
export const OUTBREAK_ALIASES: Record<string, string> = {
  'kipindupindu': 'cholera',
  'cholera': 'cholera',
  'kuhara maji': 'cholera',
  'typhoid': 'typhoid',
  'homa ya matumbo': 'typhoid',
  'enteric fever': 'typhoid',
  'meningitis': 'meningitis',
  'homa ya ubongo': 'meningitis',
  'ubongo kuwaka': 'meningitis',
  'bacterial meningitis': 'meningitis',
  'measles': 'measles',
  'surua': 'measles',
  'ukambi': 'measles',
  'rubeola': 'measles',
  'mpox': 'mpox',
  'monkeypox': 'mpox',
  'ndui ya nyani': 'mpox',
  'dengue': 'dengue',
  'dengue fever': 'dengue',
  'homa ya dengue': 'dengue',
  'rabies': 'rabies',
  'kichaa cha mbwa': 'rabies',
  'mbwa mwendawazimu': 'rabies',
  'schistosomiasis': 'schistosomiasis',
  'kichocho': 'schistosomiasis',
  'bilharzia': 'schistosomiasis',
  'malaria': 'malaria',
  'homa ya malaria': 'malaria',
  'plasmodium': 'malaria',
  'ebola': 'ebola',
  'marburg': 'marburg',
  'vhf': 'viral_haemorrhagic_fever',
  'homa ya damu': 'viral_haemorrhagic_fever',
  'leptospirosis': 'leptospirosis',
  'plague': 'plague',
  'tauni': 'plague',
};

const O: Record<string, AIResult> = {

  cholera: {
    level: 'urgent', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Guidelines on Cholera 2023.',
    text: `CHOLERA (Kipindupindu) — MEDICAL EMERGENCY\n\nCholera is a severe bacterial infection causing profuse, rapid watery diarrhoea that can kill within hours from dehydration.\n\nHOW TO RECOGNISE:\n★ Sudden onset of profuse, watery diarrhoea — described as "rice water stools" (grey-white, watery, odourless)\n★ Vomiting (often without nausea)\n★ Rapid, severe dehydration — sunken eyes, no urine, skin pinch returns slowly\n★ Muscle cramps (from electrolyte loss)\n★ Usually NO fever in uncomplicated cholera (unlike typhoid)\n★ Can lose litres of fluid per hour\n★ Can progress from well to critically ill in 2–4 hours\n\nHOW IT SPREADS:\n· Contaminated water — drinking water from unsafe sources\n· Contaminated food — especially seafood, raw vegetables washed in unsafe water\n· Direct contact with faeces of infected person\n· Poor sanitation\n\nFIRST RESPONSE (do all of this immediately):\n1. START ORS IMMEDIATELY — do not wait: Mix 6 teaspoons sugar + ½ teaspoon salt in 1 litre clean water. Drink continuously.\n2. GO TO HEALTH FACILITY IMMEDIATELY — severe cholera needs IV fluids\n3. ISOLATE the patient — separate their toilet/bucket, wash hands after any contact\n4. REPORT to the nearest health facility — cholera is a notifiable disease\n5. BOIL all drinking water in the household\n6. Wash hands with soap and water after using the toilet and before preparing food\n\nSIGNS OF SEVERE DEHYDRATION — IV FLUIDS NEEDED URGENTLY:\n★ Not able to drink\n★ Sunken eyes\n★ No urine for 4+ hours\n★ Skin remains "tented" when pinched\n★ Confusion or unconsciousness\n\nTREATMENT: IV Ringer's Lactate + ORS + Doxycycline (antibiotics given in health facility). Do not attempt home treatment alone for severe cholera.`,
    swahili: `KIPINDUPINDU — DHARURA YA KIMATIBABU\n\nKipindupindu ni maambukizi ya bakteria yanayosababisha kuhara kwa maji mengi haraka, ambayo yanaweza kuua ndani ya masaa machache kutokana na upungufu wa maji.\n\nJINSI YA KUTAMBUA:\n★ Kuanza ghafla kwa kuhara kwa maji mengi — "maji ya wali" (kijivu, ya maji, bila harufu)\n★ Kutapika (mara nyingi bila kichefuchefu)\n★ Upungufu mkali wa maji haraka — macho yaliyozama, hakuna mkojo, ngozi inabaki iliyoinuliwa ukiibana\n★ Maumivu ya misuli (kutokana na kupoteza elektroliti)\n★ Kwa kawaida HAKUNA homa (tofauti na typhoid)\n★ Inaweza kupoteza lita za maji kwa saa\n★ Inaweza kuendelea kutoka kuwa mzima hadi kuwa mgonjwa mkubwa ndani ya masaa 2–4\n\nJINSI INAVYOSAMBAA:\n· Maji yaliyochafuliwa — kunywa maji kutoka vyanzo visivyo salama\n· Chakula kilichochafuliwa — hasa samaki, mboga mbichi zilizoshawa na maji yasiyo salama\n· Mawasiliano ya moja kwa moja na kinyesi cha mtu aliyeambukizwa\n· Usafi mbaya\n\nJIMBU LA KWANZA (fanya hii yote mara moja):\n1. ANZA ORS MARA MOJA — usisute: Changanya vijiko 6 sukari + kijiko ½ chumvi kwenye lita 1 ya maji safi. Nywa bila kukoma.\n2. NENDA KITUO CHA AFYA MARA MOJA — kipindupindu kikali kinahitaji maji ya mishipa\n3. TENGA mgonjwa — tenganisha choo/ndoo yake, osha mikono baada ya mawasiliano yoyote\n4. RIPOTI kwa kituo cha afya karibu — kipindupindu ni ugonjwa unaotakiwa kuripotiwa\n5. CHEMSHA maji yote ya kunywa nyumbani\n\nISHARA ZA UPUNGUFU MKALI WA MAJI — MAJI YA MISHIPA YANAHITAJIKA HARAKA:\n★ Hawezi kunywa\n★ Macho yaliyozama\n★ Hakuna mkojo masaa 4+\n★ Ngozi inabaki "iliyoinuliwa" ukiibana\n★ Kuchanganyikiwa au kupoteza fahamu`,
  },

  typhoid: {
    level: 'action', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Typhoid Guidelines 2023.',
    text: `TYPHOID FEVER (Homa ya Matumbo) — Enteric Fever\n\nTyphoid is a bacterial infection (Salmonella typhi) from contaminated food or water. Endemic in Tanzania, especially in urban areas with poor water/sanitation.\n\nHOW TO RECOGNISE:\n★ Sustained fever — rises gradually each day for the first week, reaching 39–40°C\n★ Relative bradycardia — pulse rate lower than expected for the fever level\n★ Severe headache — prominent\n★ Abdominal pain and tenderness — especially around the navel\n★ Constipation (more common in adults) OR diarrhoea (more common in children)\n★ Rose spots — faint salmon-coloured spots on trunk (present in only 30%, easily missed)\n★ Coated tongue\n★ Splenomegaly and hepatomegaly (enlarged spleen and liver)\n★ Week 2–3: Risk of intestinal perforation (sudden severe abdominal pain + guarding = EMERGENCY)\n\nHOW IT SPREADS:\n· Faecal-oral route — contaminated water, uncooked food\n· Food prepared by infected carrier\n· Unwashed hands after toilet\n\nTREATMENT (requires prescription):\n· Ciprofloxacin 500mg twice daily for 10–14 days (first-line Tanzania)\n· Ceftriaxone IV for severe cases (hospital)\n· Azithromycin 1g daily for 5 days (alternative)\n· Confirmation: Widal test (low sensitivity), blood culture (gold standard)\n\nNOTE: Widal test is commonly done in Tanzania but is unreliable at single time points — paired titers needed. Clinical diagnosis is important.\n\nPREVENTION:\n✓ Drink only boiled or purified water\n✓ Eat only thoroughly cooked hot food\n✓ Wash hands with soap before eating and after toilet\n✓ Typhoid vaccine available (Vi polysaccharide — 2–3 years protection)\n\nGo to hospital IMMEDIATELY:\n★ Sudden severe abdominal pain with guarding (intestinal perforation)\n★ High fever lasting more than 5 days without response to antibiotics\n★ Confusion, extreme weakness, or bleeding`,
    swahili: `TYPHOID (Homa ya Matumbo) — Homa ya Matumbo\n\nTyphoid ni maambukizi ya bakteria (Salmonella typhi) kutoka chakula au maji yaliyochafuliwa. Ni ya kawaida Tanzania, hasa maeneo ya mijini yenye matatizo ya maji/usafi.\n\nJINSI YA KUTAMBUA:\n★ Homa inayoendelea — inaongezeka polepole kila siku kwa wiki ya kwanza, ikifika 39–40°C\n★ Mapigo ya moyo ya polepole tofauti na kiwango cha homa\n★ Maumivu makali ya kichwa\n★ Maumivu ya tumbo — hasa karibu na kitovu\n★ Kuvimbiwa (zaidi kwa wazima) AU kuhara (zaidi kwa watoto)\n★ Wiki 2–3: Hatari ya kutoboka kwa matumbo (maumivu makali ghafla ya tumbo = DHARURA)\n\nJINSI INAVYOSAMBAA:\n· Njia ya kinyesi-kwa-mdomo — maji yaliyochafuliwa, chakula kisichopikwa\n· Chakula kilichoandaliwa na mbeba wa maambukizi\n· Mikono isiyooshwa baada ya choo\n\nMATIBABU (inahitaji dawa ya daktari):\n· Ciprofloxacin 500mg mara mbili kwa siku kwa siku 10–14\n· Ceftriaxone IV kwa hali kali (hospitali)\n\nKUZUIWA:\n✓ Kunywa maji yaliyochemshwa tu au yaliyosafishwa\n✓ Kula chakula kilichopikwa vizuri na kilicho cha moto\n✓ Osha mikono na sabuni kabla ya kula na baada ya choo\n✓ Chanjo ya typhoid inapatikana\n\nNenda hospitali MARA MOJA:\n★ Maumivu makali ghafla ya tumbo (kutoboka kwa matumbo)\n★ Homa kali inayodumu zaidi ya siku 5 bila kuitikia antibiotics`,
  },

  meningitis: {
    level: 'urgent', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Meningitis Guidelines 2023.',
    text: `MENINGITIS — LIFE-THREATENING EMERGENCY\n\nMeningitis is inflammation of the membranes surrounding the brain and spinal cord. Bacterial meningitis can kill within 24 hours of symptom onset.\n\nCLASSIC TRIAD (present in only ~45% — do not wait for all three):\n★ Sudden severe headache — worst ever\n★ High fever (38.5°C+)\n★ Stiff neck — cannot touch chin to chest\n\nOTHER KEY SIGNS:\n★ Sensitivity to light (photophobia) — wants to be in dark room\n★ Sensitivity to sound (phonophobia)\n★ Nausea and vomiting\n★ Confusion or altered consciousness\n★ Seizures\n★ Kernig's sign: Cannot fully straighten knee when hip is flexed\n★ Brudzinski's sign: Flexing neck causes involuntary bending of knees\n\nMENINGOCOCCAL PURPURIC RASH — MOST DANGEROUS SIGN:\n★ Purple or red spots that DO NOT FADE when you press a clear glass on them (non-blanching)\n★ Can appear anywhere on the body\n★ This sign = meningococcal septicaemia = CALL FOR HELP IMMEDIATELY\n\nIN INFANTS (under 18 months):\n· Bulging fontanelle (soft spot on head)\n· High-pitched cry\n· Refusal to feed\n· Stiff body\n· Does NOT always have neck stiffness — check fontanelle\n\nACTION:\n★ DO NOT WAIT — This is a MEDICAL EMERGENCY. Go to hospital IMMEDIATELY.\n★ Every hour of delay increases risk of death and permanent brain damage.\n★ Treatment: IV Ceftriaxone/Penicillin + Dexamethasone. Early treatment saves lives.\n\nCAUSES in Tanzania:\nBacterial: Neisseria meningitidis (commonest), Streptococcus pneumoniae, TB meningitis\nViral: Usually self-limiting, less severe\nTB meningitis: Gradual onset over weeks — headache, fever, personality change, neck stiffness\n\nVACCINATION: Meningococcal vaccine available — speak to your health facility.`,
    swahili: `MENINGITIS — DHARURA YA HATARI YA MAISHA\n\nMeningitis ni kuvimba kwa utando unaozunguka ubongo na uti wa mgongo. Meningitis ya bakteria inaweza kuua ndani ya masaa 24 ya kuanza kwa dalili.\n\nDALILI TATU KUU (zipo tu kwa takriban 45% — usisute mpaka zote zionekane):\n★ Maumivu makali ghafla ya kichwa — mabaya zaidi maishani\n★ Homa kali (38.5°C+)\n★ Shingo ngumu — hawezi kuleta kidevu kifuani\n\nDALILI NYINGINE MUHIMU:\n★ Kuepuka mwanga (anataka chumba chenye giza)\n★ Kuepuka sauti\n★ Kichefuchefu na kutapika\n★ Kuchanganyikiwa au kupoteza fahamu\n★ Mshtuko\n\nUPELE WA MENINGOCOCCAL — ISHARA YA HATARI ZAIDI:\n★ Madoa ya zambarau au nyekundu ambayo HAYAFIIFII ukibonyeza glasi wazi juu yake (non-blanching)\n★ Yanaweza kuonekana sehemu yoyote ya mwili\n★ Ishara hii = ITA MSAADA MARA MOJA\n\nKWA WATOTO WACHANGA (chini ya miezi 18):\n· Ubuni (sehemu laini ya kichwa) unaoboha juu\n· Kulia kwa sauti kali\n· Kukataa kunyonya\n· Mwili mgumu\n· SIWEZI kuwa na shingo ngumu — angalia ubuni\n\nHATUA:\n★ USISUTE — Hii ni DHARURA YA KIMATIBABU. Nenda hospitali MARA MOJA.\n★ Kila saa ya kuchelewa inaongeza hatari ya kifo na uharibifu wa kudumu wa ubongo.`,
  },

  measles: {
    level: 'action', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Measles Guidelines.',
    text: `MEASLES (Surua/Ukambi) — Highly Contagious, Vaccine-Preventable\n\nMeasles is one of the most contagious infections known. One infected person can infect 12–18 others. Preventable by vaccination.\n\nHOW TO RECOGNISE (in order of appearance):\nDAY 1–4 — Prodrome:\n★ High fever (can reach 40°C+)\n★ Runny nose (coryza)\n★ Cough\n★ Red, watery, light-sensitive eyes (conjunctivitis)\n★ Koplik's spots — small white spots inside the cheeks, opposite the molars (pathognomonic — only seen in measles)\n\nDAY 4–7 — Rash:\n★ Blotchy, flat-to-raised red rash\n★ Starts BEHIND THE EARS and at the HAIRLINE\n★ Spreads DOWNWARD — face → neck → trunk → arms → legs\n★ Rash appears as fever peaks\n★ Fades in the same order it appeared after ~5 days\n\nCOMPLICATIONS (most important):\n· Pneumonia — most common cause of measles death\n· Encephalitis (brain inflammation) — 1 in 1000 cases — headache, seizures, confusion\n· Blindness (corneal ulceration) — especially with Vitamin A deficiency\n· Diarrhoea and severe malnutrition\n· Subacute sclerosing panencephalitis (SSPE) — years later, fatal brain degeneration\n\nTREATMENT:\n· Vitamin A — given immediately: 200,000 IU daily for 2 days (reduces complications and death)\n· Supportive: Fluids, fever control, treat complications\n· No antiviral — prevention through vaccination is the only solution\n\nCONTAGIOUS PERIOD: 4 days before to 4 days after rash appears. ISOLATE the child.\n\nPREVENTION:\n✓ MMR vaccine at 9 months and 15–18 months (Tanzania immunisation schedule)\n✓ Catch-up vaccination for unvaccinated children and adults\n✓ Herd immunity requires 95% vaccination coverage\n\nREPORT any case of measles to the nearest health facility — it is a notifiable disease.`,
    swahili: `SURUA (UKAMBI) — Maambukizi Sana, Yanazuiwa na Chanjo\n\nSurua ni moja ya maambukizi ya kuambukiza zaidi yanayojulikana. Mtu mmoja aliyeambukizwa anaweza kuambukiza wengine 12–18. Inazuiwa na chanjo.\n\nJINSI YA KUTAMBUA (kwa mpangilio wa kuonekana):\nSIKU 1–4 — Awali:\n★ Homa kali (inaweza kufika 40°C+)\n★ Pua inayotiririka\n★ Kikohozi\n★ Macho mekundu, yenye maji, kuepuka mwanga\n★ Madoa ya Koplik — madoa madogo meupe ndani ya mashavu (ishara ya kipekee ya surua)\n\nSIKU 4–7 — Upele:\n★ Upele nyekundu wenye madoa\n★ Unaanza NYUMA YA MASIKIO na MSTARI WA NYWELE\n★ Unasambaa CHINI — uso → shingo → kifua → mikono → miguu\n★ Upele unaonekana homa ikiwa juu\n\nMATATIZO (muhimu zaidi):\n· Pneumonia — sababu ya kawaida zaidi ya kifo cha surua\n· Encephalitis — 1 kati ya kesi 1000 — maumivu ya kichwa, mshtuko, kuchanganyikiwa\n· Upofu — hasa na upungufu wa Vitamini A\n· Kuhara na utapiamlo mkali\n\nMATIBABU:\n· Vitamini A — toa mara moja: IU 200,000 kila siku kwa siku 2\n· Msaada: Maji, kupunguza homa, kutibu matatizo\n\nKUZUIWA:\n✓ Chanjo ya MMR miezi 9 na miezi 15–18 (ratiba ya chanjo Tanzania)\n✓ RIPOTI kesi yoyote ya surua kwa kituo cha afya karibu`,
  },

  malaria: {
    level: 'watch', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania NMCP. WHO Malaria Guidelines 2023.',
    text: `MALARIA — Most Common Cause of Fever in Tanzania\n\nMalaria is caused by Plasmodium parasites, transmitted by female Anopheles mosquitoes. P. falciparum (most common in Tanzania) is the most deadly species.\n\nHOW TO RECOGNISE:\nUNCOMPLICATED MALARIA:\n★ Fever — often cyclical: spikes and sweating episodes\n★ Chills and rigors (shaking)\n★ Severe headache\n★ Muscle aches and joint pains\n★ Nausea, vomiting\n★ Fatigue and weakness\n★ In children: Irritability, poor feeding, cough\n\nSEVERE/CEREBRAL MALARIA — EMERGENCY:\n★ High fever + altered consciousness or confusion\n★ Repeated convulsions\n★ Severe anaemia (very pale, breathless)\n★ Yellow eyes (haemolytic jaundice)\n★ Dark cola-coloured urine (haemoglobinuria — "blackwater fever")\n★ Unable to sit or stand\n★ Respiratory distress\n\nDIAGNOSIS:\n✓ Malaria Rapid Diagnostic Test (RDT) — available FREE at all government health facilities\n✓ Blood smear microscopy — gold standard\nDo NOT treat for malaria without a confirmed positive test (WHO policy)\n\nTREATMENT (first-line Tanzania):\n· Artemether-Lumefantrine (ALu/Coartem) — 3-day course\n· Take with food or milk (improves absorption)\n· Complete the full course even if you feel better\n· Severe malaria (hospital): IV Artesunate\n· Pregnancy first trimester: Quinine + Clindamycin\n· Pregnancy second/third trimester: ALu\n\nPREVENTION:\n✓ Sleep under an Insecticide-Treated Bed Net (LLIN) EVERY night\n✓ Eliminate standing water around the house\n✓ Wear long sleeves and trousers in the evenings\n✓ Malaria prophylaxis for travellers — consult health facility\n✓ Pregnant women: Intermittent Preventive Treatment (IPTp) with SP\n✓ Children under 5: IPTc in high-transmission areas\n\nGo to hospital IMMEDIATELY:\n★ Child with fever and any danger sign — NEVER WAIT\n★ Fever with confusion, seizures, or difficulty breathing\n★ Dark urine with fever\n★ Positive RDT with severe symptoms`,
    swahili: `MALARIA — Sababu ya Kawaida Zaidi ya Homa Tanzania\n\nMalaria inasababishwa na vimelea vya Plasmodium, vinavyosambazwa na mbu wa kike wa Anopheles. P. falciparum (ya kawaida zaidi Tanzania) ni aina ya hatari zaidi.\n\nJINSI YA KUTAMBUA:\nMALARIA ISIYO NA MATATIZO:\n★ Homa — mara nyingi ya mzunguko: kupanda na jasho\n★ Kutetemeka na baridi\n★ Maumivu makali ya kichwa\n★ Maumivu ya misuli na viungo\n★ Kichefuchefu, kutapika\n★ Uchovu na udhaifu\n\nMALARIA KALI/YA UBONGO — DHARURA:\n★ Homa kali + kupoteza fahamu au kuchanganyikiwa\n★ Mshtuko unarudiwa\n★ Upungufu mkali wa damu\n★ Macho ya njano\n★ Mkojo wa rangi ya cola nyeusi\n★ Kushindwa kukaa au kusimama\n\nUCHUNGUZI:\n✓ Kipimo cha haraka cha malaria (RDT) — BURE vituo vyote vya serikali\nUSITIBU malaria bila kipimo kinachothibitisha (sera ya WHO)\n\nMATIBABU (mstari wa kwanza Tanzania):\n· Artemether-Lumefantrine (ALu/Coartem) — kozi ya siku 3\n· Chukua na chakula au maziwa\n· Maliza kozi yote hata ukihisi vizuri\n\nKUZUIWA:\n✓ Lala chini ya chandarua cha kutiwa dawa (LLIN) KILA usiku\n✓ Ondoa maji yaliyosimama karibu na nyumba\n✓ Vaa nguo ndefu jioni\n✓ Wanawake wajawazito: IPTp na SP\n\nNenda hospitali MARA MOJA:\n★ Mtoto mwenye homa na dalili yoyote ya hatari — USISUTE\n★ Homa na kuchanganyikiwa, mshtuko, au kupumua kwa shida`,
  },

  rabies: {
    level: 'urgent', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Rabies Guidelines 2023.',
    text: `RABIES (Kichaa cha Mbwa) — 100% FATAL if not treated BEFORE symptoms appear.\n\nRabies is caused by a virus transmitted through the saliva of an infected animal, usually via a bite or scratch. Once symptoms appear, rabies is almost universally fatal. Prevention after a bite (post-exposure prophylaxis — PEP) is life-saving.\n\nCOMMON SOURCES IN TANZANIA:\n· Dogs (most common — responsible for 95%+ of human rabies in Africa)\n· Cats\n· Monkeys\n· Bats — even a small scratch or bite\n· Any wild mammal acting strangely\n\nSIGNS OF RABIES IN ANIMALS:\n· Unusual aggression or unusual tameness\n· Drooling excessively\n· Paralysis\n· Disorientation, staggering\n· Dog may attack without provocation\n\nIF BIT OR SCRATCHED BY AN ANIMAL:\n1. WASH IMMEDIATELY — Wash the wound thoroughly with soap and running water for 15 FULL MINUTES. This is the most important first step — reduces transmission risk significantly.\n2. Apply iodine or alcohol after washing\n3. Go to health facility WITHIN 24 HOURS for assessment and PEP (post-exposure prophylaxis)\n4. Do NOT cover the wound tightly immediately\n5. Report the incident — if possible, observe the animal for 10 days\n\nPOST-EXPOSURE PROPHYLAXIS (PEP):\n· Rabies vaccine series — given on Day 0, 3, 7, and 14 or 28 (depending on regimen)\n· Rabies immunoglobulin (RIG) — for deep bites, multiple bites, or bites to face/neck/hands\n· Must be started as soon as possible after the bite — effectiveness decreases with delay\n· PEP is available at selected health facilities in Tanzania\n\nSYMPTOMS OF RABIES (once these appear — prognosis is almost universally fatal):\n★ Initial: Tingling or pain at the bite site, fever, headache\n★ Progresses to: Agitation, confusion, hallucinations\n★ Hydrophobia — painful spasms when trying to swallow water\n★ Aerophobia — fear of air currents\n★ Paralysis, coma, death\n★ Death usually occurs within 2–10 days of symptom onset\n\nANY ANIMAL BITE = SEEK MEDICAL CARE TODAY. Do not wait to see if symptoms develop — by then it is too late.`,
    swahili: `KICHAA CHA MBWA — 100% YA KUUA kama haitibiwa KABLA ya dalili kuonekana.\n\nKichaa cha mbwa kinasababishwa na virusi vinavyosambazwa kupitia mate ya mnyama aliyeambukizwa, kawaida kupitia kuumwa au kukwaruliwa. Mara dalili zinapoanza, kichaa cha mbwa karibu hazipatikani kuponywa. Kuzuia baada ya kuumwa (PEP) kunaokoa maisha.\n\nVYANZO VYA KAWAIDA TANZANIA:\n· Mbwa (ya kawaida zaidi — wanawajibika kwa zaidi ya 95% ya kichaa cha mbwa cha binadamu Afrika)\n· Paka\n· Nyani\n· Popo — hata mchubuko mdogo au kuumwa\n\nKAMA ULIUWA AU KUKWARULIWA NA MNYAMA:\n1. OSHA MARA MOJA — Osha jeraha kwa sabuni na maji yanayotiririka kwa dakika 15 KAMILI. Hii ndiyo hatua muhimu zaidi ya kwanza.\n2. Weka iodini au alkoholi baada ya kuosha\n3. Nenda kituo cha afya NDANI YA MASAA 24 kwa tathmini na PEP\n4. RIPOTI tukio\n\nDALILI ZA KICHAA CHA MBWA (mara zinapoanza — karibu daima inaua):\n★ Kwanza: Kuchwa au maumivu mahali palipoumwa, homa, maumivu ya kichwa\n★ Inaendelea hadi: Wasiwasi, kuchanganyikiwa, maono ya uongo\n★ Hydrophobia — maumivu ya kushindwa kumeza maji\n★ Kupooza, kutokuwa na fahamu, kifo\n\nKUUMWA CHOCHOTE NA MNYAMA = TAFUTA MATIBABU LEO. Usisute kuona kama dalili zitatokea — kufikia wakati huo itakuwa kuchelewa sana.`,
  },

  schistosomiasis: {
    level: 'action', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania NTDCP. WHO Schistosomiasis Guidelines.',
    text: `SCHISTOSOMIASIS (Kichocho/Bilharzia) — Very Common in Tanzania\n\nSchistosomiasis is a parasitic infection caused by flatworm larvae (cercariae) in freshwater. Tanzania has some of the highest rates in Africa, particularly around Lake Victoria, Lake Tanganyika, Lake Nyasa, and river valleys.\n\nHOW IT SPREADS:\n· Swimming, wading, washing clothes, or bathing in freshwater containing infected snails\n· The larvae (cercariae) penetrate through intact skin\n· Most common in fishing communities and children who swim in lakes and rivers\n\nFORMS AND SYMPTOMS:\nACUTE (Swimmer's Itch / Katayama fever — weeks after infection):\n★ Itching and rash where larvae entered skin\n★ Fever, headache, muscle aches\n★ Cough\n★ Urticaria (hives)\n\nCHRONIC INTESTINAL SCHISTOSOMIASIS (S. mansoni):\n★ Abdominal pain\n★ Blood in stool (haematochezia)\n★ Diarrhoea\n★ Portal hypertension (enlarged liver, spleen) — advanced disease\n★ Anaemia, malnutrition in children — stunted growth\n\nCHRONIC UROGENITAL SCHISTOSOMIASIS (S. haematobium):\n★ Blood in urine (haematuria) — most characteristic sign, often painless\n★ Frequent and painful urination\n★ Long-term: Bladder damage, kidney damage, increased risk of bladder cancer\n★ Female genital schistosomiasis: Genital lesions, increased HIV acquisition risk\n\nDIAGNOSIS:\n· Stool microscopy (Kato-Katz) for S. mansoni\n· Urine filtration for S. haematobium (dipstick for blood)\n· Serology for early infection\n\nTREATMENT:\n· Praziquantel 40mg/kg as single dose — highly effective, safe, inexpensive\n· Available in Tanzania as part of mass drug administration (MDA) campaigns\n· Re-treatment usually needed as re-infection is common\n\nPREVENTION:\n✓ Avoid swimming in freshwater — lakes, rivers, irrigation canals\n✓ Use safe (piped or treated) water for bathing and washing\n✓ Take Praziquantel if offered during MDA campaigns\n✓ Dry wet clothes quickly in sunlight — cercariae die when clothes dry`,
    swahili: `KICHOCHO (BILHARZIA) — Ya Kawaida Sana Tanzania\n\nKichocho ni maambukizi ya vimelea vinavyosababishwa na mabuu ya minyoo ya bapa kwenye maji ya bara. Tanzania ina baadhi ya viwango vya juu zaidi Afrika, hasa karibu na Ziwa Victoria, Tanganyika, Nyasa, na mabonde ya mito.\n\nJINSI INAVYOSAMBAA:\n· Kuogelea, kupita, kuosha nguo, au kuoga kwenye maji ya baridi yenye konokono walioambukizwa\n· Mabuu yanaingia kupitia ngozi nzima\n· Ya kawaida kwa wavuvi na watoto wanaoogelea maziwa na mito\n\nAINANA DALILI:\nKICHOCHO CHA MATUMBO (damu kwenye kinyesi, maumivu ya tumbo)\nKICHOCHO CHA MKOJO (damu mkojoni — ishara ya kawaida zaidi, mara nyingi bila maumivu):\n★ Damu mkojoni (haematuria)\n★ Kukojoa mara kwa mara na kwa maumivu\n★ Muda mrefu: Uharibifu wa kibofu, uharibifu wa figo, hatari ya saratani ya kibofu\n\nMATIBABU:\n· Praziquantel 40mg/kg kwa dozi moja — inafaa sana, salama, bei rahisi\n· Inapatikana Tanzania kama sehemu ya kampeni za kutoa dawa kwa wingi (MDA)\n\nKUZUIWA:\n✓ Epuka kuogelea kwenye maji ya baridi ya bara — maziwa, mito\n✓ Tumia maji salama (bomba au yaliyotibiwa) kuoga na kuosha\n✓ Chukua Praziquantel ukipewa wakati wa kampeni za MDA\n✓ Kausha nguo haraka kwenye jua — mabuu hufa nguo zinapokauka`,
  },

  mpox: {
    level: 'action', confidence: 'high', source: 'offline',
    disclaimer: 'WHO Mpox Guidance 2024. Tanzania MOH.',
    text: `MPOX (Monkeypox) — Emerging Concern in East Africa\n\nMpox is a viral disease causing a characteristic rash with fever. Two clades: Clade I (more severe, now spreading in eastern DRC and neighbouring countries including Tanzania border regions) and Clade II (less severe, global 2022 outbreak).\n\nHOW TO RECOGNISE:\nStage 1 (Days 0–5):\n★ Fever, headache, severe backache, muscle aches\n★ Lymph node swelling — enlarged, painful lymph nodes (distinguishes from smallpox and chickenpox)\n★ Extreme fatigue\n\nStage 2 — RASH (within 1–3 days of fever):\n★ Rash starts on FACE, then spreads to palms, soles, body\n★ Progresses through stages: macules → papules → vesicles → pustules → scabs\n★ ALL lesions at the SAME STAGE at one time (unlike chickenpox which is mixed stages)\n★ Lesions are PAINFUL, not just itchy\n★ Lesions can appear in mouth, genitals, eyes\n★ 2–4 week illness in most cases\n\nTRANSMISSION:\n· Direct contact with skin lesions, body fluids, or respiratory secretions of infected person\n· Contact with contaminated materials (bedding, clothes)\n· Animal-to-human: Rodents and primates (eating bushmeat, handling infected animals)\n· Sexual contact (major route in Clade IIb 2022 outbreak)\n· Respiratory droplets (prolonged close contact)\n\nISOLATION:\n· Isolate infected person until all lesions have fully crusted and scabs have fallen off\n· Cover all lesions\n· Use gloves when caring for patient\n· Disinfect surfaces and wash bedding separately\n\nTREATMENT:\n· Supportive care — fever control, wound care, pain management\n· No widely available antiviral in Tanzania — severe cases may be referred\n· Vaccination available for close contacts (limited supply in Tanzania)\n\nREPORT any suspected cases to the nearest health facility and Tanzania MOH. Mpox is a notifiable disease.`,
    swahili: `MPOX — Wasiwasi Unaokua Afrika Mashariki\n\nMpox ni ugonjwa wa virusi unaosababisha upele wa kipekee na homa. Ina aina mbili: Clade I (kali zaidi, inasambaa sasa DRC mashariki na nchi jirani) na Clade II (kali kidogo).\n\nJINSI YA KUTAMBUA:\nHatua 1 (Siku 0–5):\n★ Homa, maumivu ya kichwa, maumivu makali ya mgongo, maumivu ya misuli\n★ Kuvimba kwa nodi za lymph — zinazovimba, zenye maumivu (inaitofautisha na tetewanga)\n★ Uchovu mkubwa\n\nHatua 2 — UPELE (ndani ya siku 1–3 za homa):\n★ Upele unaanza USONI, kisha unasambaa kwenye viganja, nyayo, mwili\n★ Majeraha yote HATUA MOJA kwa wakati mmoja (tofauti na tetewanga ambayo ina hatua mchanganyiko)\n★ Majeraha yana MAUMIVU, si kuwasha tu\n\nKUZUIWA:\n· Epuka mawasiliano ya karibu na mtu mwenye upele\n· Epuka nyama ya mwitu na wanyama pori wanaoonekana wagonjwa\n\nRIPOTI kesi yoyote inayoshukiwa kwa kituo cha afya karibu. Mpox ni ugonjwa unaotakiwa kuripotiwa.`,
  },

  dengue: {
    level: 'action', confidence: 'high', source: 'offline',
    disclaimer: 'WHO Dengue Guidelines 2023. Tanzania MOH.',
    text: `DENGUE FEVER — Increasing in Tanzania's Urban Areas\n\nDengue is a viral infection transmitted by Aedes aegypti mosquitoes (black and white striped, bites during the day). Endemic in Dar es Salaam and other Tanzanian cities.\n\nHOW TO RECOGNISE:\nCLASSIC DENGUE (most common):\n★ Sudden high fever (39–40°C) — abrupt onset\n★ Severe headache — especially behind the eyes (retro-orbital pain)\n★ Severe joint and muscle pain — "breakbone fever"\n★ Nausea, vomiting, loss of appetite\n★ Rash — appears 3–4 days into illness: measles-like, may have pale "islands" within red\n★ Mild bleeding: Easy bruising, nosebleed, gum bleeding\n★ Positive tourniquet test\n\nWARNING SIGNS (Severe Dengue — go to hospital immediately):\n★ Abdominal pain or tenderness\n★ Persistent vomiting (3+ times in 24 hours)\n★ Bleeding from gums or nose\n★ Blood in vomit (coffee grounds) or stool (black/tarry)\n★ Rapid breathing\n★ Fatigue, restlessness, agitation\n★ Liver enlargement\n★ Clinical fluid accumulation (ascites, pleural effusion)\n\nTREATMENT:\n· NO specific antiviral — supportive treatment only\n· Fluids — oral rehydration is critical; IV fluids if needed\n· Paracetamol for fever and pain — DO NOT give aspirin or ibuprofen (increases bleeding risk)\n· Rest\n· Monitor platelet count daily if hospitalised\n\nPREVENTION:\n✓ Eliminate mosquito breeding sites: Empty and turn over any containers holding water (flower pots, tyres, buckets, water drums)\n✓ Use mosquito repellent\n✓ Wear long sleeves and trousers during day — Aedes bites during daylight\n✓ Install window and door screens`,
    swahili: `DENGUE — Inaongezeka Maeneo ya Mijini Tanzania\n\nDengue ni maambukizi ya virusi yanayosambazwa na mbu wa Aedes aegypti (mbu wenye milia nyeusi na nyeupe, wanaouma wakati wa mchana). Inajulikana Dar es Salaam na miji mingine Tanzania.\n\nJINSI YA KUTAMBUA:\n★ Homa kali ghafla (39–40°C)\n★ Maumivu makali ya kichwa — hasa nyuma ya macho\n★ Maumivu makali ya viungo na misuli — "homa ya mifupa kuvunjika"\n★ Kichefuchefu, kutapika\n★ Upele — unaonekana siku 3–4 za ugonjwa\n★ Kutokwa damu kidogo: Michubuko rahisi, kutoka damu pua, ufizi\n\nISHARA ZA ONYO (Dengue Kali — nenda hospitali MARA MOJA):\n★ Maumivu ya tumbo\n★ Kutapika sana (mara 3+ kwa saa 24)\n★ Damu kwenye matapishi au kinyesi\n★ Upungufu wa pumzi\n★ Uchovu mkubwa, wasiwasi\n\nMATIBABU:\n· Hakuna dawa maalum ya virusi — matibabu ya msaada tu\n· Maji — ORS ni muhimu; maji ya mishipa kama yahitajika\n· Paracetamol kwa homa na maumivu — USITOE aspirin au ibuprofen (inaongeza hatari ya kutokwa damu)\n\nKUZUIWA:\n✓ Ondoa maeneo ya kuzaana kwa mbu: Futa na pindua vyombo vyovyote vinavyoshikilia maji\n✓ Tumia dawa ya kufukuza mbu\n✓ Vaa nguo ndefu wakati wa mchana — Aedes wanasuma wakati wa mchana`,
  },

  viral_haemorrhagic_fever: {
    level: 'urgent', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO VHF Guidelines.',
    text: `VIRAL HAEMORRHAGIC FEVER (Ebola, Marburg, Lassa) — HIGHEST PRIORITY EMERGENCY\n\nViral haemorrhagic fevers are rare but highly dangerous. Tanzania borders DRC where Ebola/Marburg outbreaks have occurred.\n\nKEY WARNING SIGNS (any of these in a patient with fever):\n★ Unexplained bleeding from any site — gums, nose, eyes, rectum, skin bruising\n★ Fever that does not respond to antimalarials AND antibiotics\n★ Severe headache + fever + muscle aches in a person who:\n   · Has recently returned from a high-risk area\n   · Has had contact with a sick or dead person from an affected area\n   · Has had contact with sick animals or bushmeat\n\nIF VIRAL HAEMORRHAGIC FEVER IS SUSPECTED:\n★ DO NOT touch the patient without protective equipment\n★ ISOLATE immediately — separate room, separate toilet\n★ Call the health facility BEFORE transporting — DO NOT walk in to the hospital unannounced\n★ Contact Tanzania MOH Emergency Operations: +255-800-110-027 (free)\n★ Do NOT touch body fluids, blood, or deceased patients\n★ All contact tracing will be initiated by public health authorities\n\nTRANSMISSION (Ebola/Marburg):\n· Direct contact with blood, body fluids (sweat, saliva, urine) of symptomatic patients\n· Burial practices — contact with deceased patients\n· Healthcare workers without PPE\n· NOT airborne in normal conditions\n\nIMPORTANT: Ebola and Marburg are not endemic in Tanzania as of 2024, but vigilance is required given proximity to DRC outbreaks.`,
    swahili: `HOMA YA DAMU (Ebola, Marburg, Lassa) — DHARURA YA KIPAUMBELE CHA JUU\n\nHoma ya damu ni nadra lakini ni hatari sana. Tanzania inapakana na DRC ambapo milipuko ya Ebola/Marburg imetokea.\n\nISHARA ZA ONYO (yoyote kati ya hizi kwa mgonjwa mwenye homa):\n★ Kutokwa na damu bila kuelezwa sehemu yoyote — ufizi, pua, macho, puru, michubuko ya ngozi\n★ Homa isiyoitikia dawa za malaria NA antibiotics\n★ Maumivu makali ya kichwa + homa + maumivu ya misuli kwa mtu ambaye:\n   · Amirudi hivi karibuni kutoka eneo la hatari\n   · Amekuwa na mawasiliano na mtu mgonjwa au aliyefariki kutoka eneo lililoathirika\n\nKAMA HOMA YA DAMU INASHUKIWA:\n★ USIGUSE mgonjwa bila vifaa vya kujikinga\n★ TENGA MARA MOJA — chumba tofauti, choo tofauti\n★ Piga simu kituo cha afya KABLA ya kusafirisha\n★ Wasiliana na MOH Tanzania: +255-800-110-027 (bila malipo)\n★ USIGUSE maji ya mwili, damu, au maiti`,
  },

  leptospirosis: {
    level: 'action', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Leptospirosis Guidelines.',
    text: `LEPTOSPIROSIS — Waterborne, Underdiagnosed in Tanzania\n\nLeptospirosis is a bacterial infection (Leptospira species) transmitted through water or soil contaminated with infected animal urine. Often undiagnosed in Tanzania — confused with malaria or typhoid.\n\nHOW IT SPREADS:\n· Contact with water/mud contaminated by urine of infected animals (rats most common, also cattle, dogs, pigs)\n· Flooding season — major risk factor in Tanzania\n· Wading through floodwater, working in rice paddies, fishing\n· Bacteria enter through cuts, abrasions, or mucous membranes\n\nHOW TO RECOGNISE:\nMILD (Anicteric Leptospirosis — 90% of cases):\n★ Sudden onset high fever (often >39°C)\n★ Severe headache\n★ Severe muscle aches — especially calf muscles (characteristic)\n★ Conjunctival suffusion (red eyes WITHOUT discharge — characteristic)\n★ Rash (variable)\n★ Often mimics malaria or dengue — will test negative for both\n\nSEVERE (Weil's Disease — 10% of cases):\n★ Jaundice (yellow eyes)\n★ Kidney failure (reduced urine output)\n★ Bleeding — from lungs, gastrointestinal, skin\n★ Myocarditis (heart inflammation)\n★ Confusion\n\nTREATMENT:\n· Mild: Doxycycline 100mg twice daily for 7 days (or Amoxicillin)\n· Severe: IV Penicillin G or Ceftriaxone (hospital)\n\nPREVENTION:\n✓ Avoid wading in floodwater if possible\n✓ Wear rubber boots and gloves when working with animals or floodwater\n✓ Do not swim in potentially contaminated water\n✓ Cover food — protect from rodent contamination\n✓ Control rodents around homes and grain stores`,
    swahili: `LEPTOSPIROSIS — Inasambazwa na Maji, Haijatibuliwa Tanzania\n\nLeptospirosis ni maambukizi ya bakteria yanayosambazwa kupitia maji au udongo uliochafuliwa na mkojo wa wanyama walioambukizwa. Mara nyingi haijatambuliwa Tanzania — inachanganyikiwa na malaria au typhoid.\n\nJINSI INAVYOSAMBAA:\n· Mawasiliano na maji/tifutifu yaliyochafuliwa na mkojo wa wanyama walioambukizwa (panya wa kawaida zaidi, pia ng'ombe, mbwa, nguruwe)\n· Msimu wa mafuriko — hatari kubwa Tanzania\n· Kupita kwenye maji ya mafuriko, kufanya kazi mashambani ya mpunga, uvuvi\n\nJINSI YA KUTAMBUA:\n★ Homa kali ghafla\n★ Maumivu makali ya kichwa\n★ Maumivu makali ya misuli — hasa misuli ya miguu (dalili ya kipekee)\n★ Macho mekundu bila usaha (dalili ya kipekee)\n★ Mara nyingi inafanana na malaria au dengue — itapima hasi kwa vyote viwili\n\nHALI KALI:\n★ Macho ya njano (jaundice)\n★ Kushindwa kwa figo\n★ Kutokwa na damu\n\nMATIBABU:\n· Kali kidogo: Doxycycline 100mg mara mbili kwa siku kwa siku 7\n· Kali: IV Penicillin au Ceftriaxone (hospitali)\n\nKUZUIWA:\n✓ Epuka kupita kwenye maji ya mafuriko kama inawezekana\n✓ Vaa buti za mpira na glavu ukifanya kazi na wanyama au maji ya mafuriko\n✓ Dhibiti panya karibu na nyumba`,
  },

  plague: {
    level: 'urgent', confidence: 'high', source: 'offline',
    disclaimer: 'Tanzania MOH. WHO Plague Guidelines.',
    text: `PLAGUE (Tauni) — Present in Tanzania\n\nPlague is a bacterial infection (Yersinia pestis) that remains endemic in parts of Tanzania, particularly in western Tanzania (Lindi, Mtwara) and the plateau regions. It killed millions historically — still present and dangerous today.\n\nFORMS:\n\nBUBONIC PLAGUE (most common):\n★ Sudden fever, chills, headache, extreme weakness\n★ Painful, swollen lymph nodes (BUBOES) — usually in groin, armpit, or neck\n★ Buboes are tender, egg-to-orange-sized lymph node swellings\n★ Transmitted: Flea bites (fleas from infected rodents)\n\nSEPTICEMIC PLAGUE:\n★ Blood poisoning — fever, chills, extreme weakness, abdominal pain\n★ Bleeding into skin — dark patches (hence "Black Death")\n★ Can occur without visible buboes\n\nPNEUMONIC PLAGUE (most dangerous, airborne):\n★ Rapidly progressing pneumonia\n★ Fever + severe headache + cough producing blood-stained sputum\n★ Can be transmitted person-to-person through respiratory droplets\n★ Nearly 100% fatal without treatment within 24 hours\n\nIF PLAGUE IS SUSPECTED:\n★ ISOLATE the patient immediately\n★ Call the health facility before coming\n★ Contact Tanzania MOH emergency line\n★ Healthcare workers must use full PPE\n\nTREATMENT (highly effective if started early):\n· Streptomycin IM or Gentamicin IM — first-line\n· Doxycycline or Ciprofloxacin — alternatives\n\nPREVENTION:\n✓ Avoid contact with dead rodents\n✓ Pest control — reduce rat populations around homes\n✓ Flea control on pets\n✓ Report unusual rodent die-offs to health authorities`,
    swahili: `TAUNI (PLAGUE) — Ipo Tanzania\n\nTauni ni maambukizi ya bakteria (Yersinia pestis) ambayo bado yanajulikana sehemu za Tanzania, hasa Tanzania ya Magharibi. Iliua mamilioni kihistoria — bado ipo na ni hatari leo.\n\nAINA:\nTAUNI YA TEZI (ya kawaida zaidi):\n★ Homa ghafla, baridi, maumivu ya kichwa, udhaifu mkubwa\n★ Kuvimba kwa nodi za lymph chenye maumivu (BUBOES) — kawaida kinena, kwapa, au shingo\n★ Inasambazwa: Kuumwa na viroboto (viroboto kutoka kwa panya walioambukizwa)\n\nTAUNI YA MAPAFU (hatari zaidi, inasambazwa angani):\n★ Pneumonia inayoendelea haraka\n★ Homa + maumivu makali ya kichwa + kikohozi cha kutoa kohozi lenye damu\n★ Karibu 100% hufa bila matibabu ndani ya masaa 24\n\nKAMA TAUNI INASHUKIWA:\n★ TENGA mgonjwa MARA MOJA\n★ Piga simu kituo cha afya kabla ya kuja\n★ Wasiliana na nambari ya dharura ya MOH Tanzania\n\nMATIBABU (inafaa sana kama inaanza mapema):\n· Streptomycin IM au Gentamicin IM — mstari wa kwanza\n\nKUZUIWA:\n✓ Epuka kugusa panya waliokufa\n✓ Udhibiti wa wadudu — punguza idadi ya panya karibu na nyumba\n✓ Ripoti vifo vya panya visivyo vya kawaida kwa mamlaka ya afya`,
  },

};

// ── Matcher ───────────────────────────────────────────────────────────────────

export function matchOutbreak(query: string): AIResult | null {
  const q = query.toLowerCase();

  // 1. Alias map
  for (const [alias, key] of Object.entries(OUTBREAK_ALIASES)) {
    if (q.includes(alias) && O[key]) return O[key];
  }

  // 2. Direct key match
  for (const key of Object.keys(O)) {
    if (q.includes(key.replace(/_/g, ' ')) || q.includes(key)) return O[key];
  }

  return null;
}
