/**
 * Anaemia — Phase 15. Sources: WHO Anaemia 2023, NTLG STG 2023, NACP, IMCI.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const ANAEMIA: ConditionKnowledge = {
  id: 'anaemia',
  aliases: CONDITION_ALIASES.anaemia,
  category: 'hematologic',
  whatItIs: {
    en: 'Anaemia is a low haemoglobin level — the red protein that carries oxygen in red blood cells. WHO definitions: <11 g/dL in pregnancy and children 6 months-5 years, <12 g/dL non-pregnant women, <13 g/dL men. Common symptoms: tiredness, weakness, breathlessness on exertion, pallor (inside eyelids, palms), palpitations, headache. In Tanzania the leading causes are iron deficiency (poor diet, hookworm, pregnancy losses, heavy menstruation), malaria (haemolysis), sickle cell disease, vitamin B12 or folate deficiency, and chronic disease (HIV, TB, kidney disease, cancer). Each cause needs different treatment — iron for iron deficiency, malaria treatment for malaria, B12 injections for B12 deficiency, etc.',
    sw: 'Upungufu wa damu (anaemia) ni kiwango cha chini cha hemoglobini — protini nyekundu inayobeba oksijeni katika seli nyekundu za damu. Ufafanuzi wa WHO: <11 g/dL katika mimba na watoto miezi 6-miaka 5, <12 g/dL kwa wanawake wasio wajawazito, <13 g/dL kwa wanaume. Dalili za kawaida: uchovu, udhaifu, kushindwa kupumua wakati wa kujishughulisha, kufifia (ndani ya kope, viganja), mapigo ya moyo, maumivu ya kichwa. Tanzania sababu kuu ni upungufu wa madini ya chuma (lishe duni, hookworm, kupoteza mimba, hedhi kali), malaria (haemolysis), ugonjwa wa selimundu, upungufu wa vitamini B12 au folate, na ugonjwa sugu (VVU, TB, ugonjwa wa figo, saratani). Kila sababu inahitaji matibabu tofauti — madini ya chuma kwa upungufu wa chuma, matibabu ya malaria kwa malaria, sindano za B12 kwa upungufu wa B12, nk.',
    sw_mtaa: 'Anaemia ni low haemoglobin level — red protein inayobeba oxygen katika red blood cells. WHO definitions: <11 g/dL katika pregnancy na watoto miezi 6-miaka 5, <12 g/dL non-pregnant women, <13 g/dL men. Common symptoms: tiredness, weakness, breathlessness on exertion, pallor (ndani ya eyelids, palms), palpitations, headache. Tanzania leading causes ni iron deficiency (poor diet, hookworm, pregnancy losses, heavy menstruation), malaria (haemolysis), sickle cell disease, vitamin B12 au folate deficiency, na chronic disease (HIV, TB, kidney disease, cancer). Kila cause inahitaji different treatment — iron kwa iron deficiency, malaria treatment kwa malaria, B12 injections kwa B12 deficiency, nk.',
  },
  whyItMatters: {
    en: 'Anaemia in pregnancy raises risks of maternal mortality, preterm birth, low birth weight, and postpartum haemorrhage; ANC iron + folic acid supplementation is standard for this reason. Anaemia in children under 5 impairs growth and brain development. Anaemia is also a sentinel of underlying disease — in someone older than 50, new iron-deficiency anaemia must be investigated for gut bleeding from peptic ulcer or colorectal cancer; in someone with chronic cough or weight loss, look for TB or HIV; in a child with malaria-prone area, look for repeated malaria infections or hookworm. Treating just the symptom (giving iron) without finding the cause is incomplete care.',
    sw: 'Upungufu wa damu katika mimba huongeza hatari za vifo vya kimama, kuzaa mapema, uzito mdogo wa kuzaliwa, na kutokwa damu baada ya kuzaa; nyongeza ya madini ya chuma + folic acid katika ANC ni ya kawaida kwa sababu hii. Upungufu wa damu kwa watoto chini ya miaka 5 huathiri ukuaji na maendeleo ya ubongo. Upungufu wa damu pia ni ishara ya ugonjwa wa msingi — kwa mtu zaidi ya miaka 50, upungufu mpya wa damu wa madini ya chuma lazima uchunguzwe kwa kutokwa damu kwa utumbo kutoka kidonda cha peptic au saratani ya colorectal; kwa mtu mwenye kikohozi sugu au kupoteza uzito, tafuta TB au VVU; kwa mtoto katika eneo la malaria, tafuta maambukizi ya malaria ya mara kwa mara au hookworm. Kutibu dalili tu (kutoa chuma) pasipo kupata sababu ni huduma isiyokamilika.',
    sw_mtaa: 'Anaemia katika pregnancy inaraise risks za maternal mortality, preterm birth, low birth weight, na postpartum haemorrhage; ANC iron + folic acid supplementation ni standard kwa sababu hii. Anaemia kwa watoto under 5 inaimpair growth na brain development. Anaemia pia ni sentinel ya underlying disease — kwa mtu older than 50, new iron-deficiency anaemia lazima iinvestigated kwa gut bleeding kutoka peptic ulcer au colorectal cancer; kwa mtu mwenye chronic cough au weight loss, tafuta TB au HIV; kwa mtoto katika malaria-prone area, tafuta repeated malaria infections au hookworm. Kutreating tu symptom (giving iron) bila kufind cause ni incomplete care.',
  },
  commonQuestions: [
    { q: { en: 'What causes anaemia?', sw: 'Anaemia inasababishwa na nini?' }, a: { en: 'In Tanzania most common: iron deficiency (poor diet, heavy menstruation, hookworm, pregnancy losses), malaria (red blood cell destruction), sickle cell disease, vitamin B12 or folate deficiency, chronic disease (HIV, TB, kidney disease, cancer). A full blood count and blood film, plus ferritin where available, tell you the cause. Stool exam for hookworm is useful in farming communities.', sw: 'Tanzania kawaida zaidi: upungufu wa madini ya chuma (lishe duni, hedhi kali, hookworm, kupoteza mimba), malaria (uharibifu wa seli nyekundu za damu), ugonjwa wa selimundu, upungufu wa vitamini B12 au folate, ugonjwa sugu (VVU, TB, ugonjwa wa figo, saratani). Hesabu kamili ya damu na blood film, pamoja na ferritin pale inapopatikana, hukuambia sababu. Kipimo cha kinyesi kwa hookworm ni cha manufaa katika jamii za wakulima.', sw_mtaa: 'Tanzania most common: iron deficiency (poor diet, heavy menstruation, hookworm, pregnancy losses), malaria (red blood cell destruction), sickle cell disease, vitamin B12 au folate deficiency, chronic disease (HIV, TB, kidney disease, cancer). Full blood count na blood film, plus ferritin pale inapopatikana, zinakuambia cause. Stool exam kwa hookworm ni useful katika farming communities.' } },
    { q: { en: 'How is iron deficiency anaemia treated?', sw: 'Anaemia ya upungufu wa chuma inatibiwaje?' }, a: { en: 'Oral iron (ferrous sulfate or similar) at 60-120 mg elemental iron daily for 3-6 months, even after haemoglobin normalises (to refill iron stores). Take with vitamin C (orange juice) to improve absorption; avoid tea/coffee at the same time as iron tablets. Side effects: dark stool (harmless), nausea, constipation. Eat iron-rich foods: red meat, liver, dark green leafy vegetables, beans, fortified flour. Treat any hookworm with albendazole. In pregnancy, iron + folic acid is part of routine ANC. IV iron is used when oral is not tolerated or absorption is poor.', sw: 'Chuma cha kumeza (ferrous sulfate au sawa) kwa 60-120 mg ya chuma cha kimsingi kila siku kwa miezi 3-6, hata baada ya hemoglobini kurudi kawaida (kujaza tena akiba ya chuma). Chukua na vitamini C (juisi ya machungwa) kuboresha unyonyaji; epuka chai/kahawa wakati huo huo na tembe za chuma. Athari: kinyesi cheusi (hakidhuru), kichefuchefu, kufunga choo. Kula vyakula vyenye madini ya chuma: nyama nyekundu, ini, mboga za kijani kibichi, maharage, unga uliotajirishwa. Tibu hookworm yoyote na albendazole. Katika mimba, chuma + folic acid ni sehemu ya ANC ya kawaida. Chuma cha IV hutumika wakati cha kumeza hakivumiliwi au unyonyaji ni mbaya.', sw_mtaa: 'Oral iron (ferrous sulfate au similar) kwa 60-120 mg elemental iron daily kwa miezi 3-6, hata baada ya haemoglobin kurudi kawaida (kurefill iron stores). Chukua na vitamin C (orange juice) kuimprove absorption; epuka tea/coffee kwa same time na iron tablets. Side effects: dark stool (harmless), nausea, constipation. Kula iron-rich foods: red meat, liver, dark green leafy vegetables, beans, fortified flour. Treat hookworm yoyote na albendazole. Katika pregnancy, iron + folic acid ni sehemu ya routine ANC. IV iron inatumika wakati oral haijatolerated au absorption ni poor.' } },
    { q: { en: 'How do I know if I am anaemic?', sw: 'Najuaje kama nina upungufu wa damu?' }, a: { en: 'Common signs: pale inside the eyelids and palms, tiredness, breathlessness climbing stairs, palpitations, headache, poor concentration. In children: pallor, poor appetite, poor growth, irritability. Many people with mild anaemia have no symptoms — only a blood test reveals it. Pregnant women, children under 5, and people with chronic illness should be screened routinely.', sw: 'Ishara za kawaida: kufifia ndani ya kope na viganja, uchovu, kushindwa kupumua kupanda ngazi, mapigo ya moyo, maumivu ya kichwa, umakini mbaya. Kwa watoto: kufifia, hamu mbaya ya chakula, ukuaji mbaya, hasira. Watu wengi wenye upungufu mdogo wa damu hawana dalili — kipimo cha damu tu hugundua. Wanawake wajawazito, watoto chini ya miaka 5, na watu wenye ugonjwa sugu wanapaswa kuchunguzwa mara kwa mara.', sw_mtaa: 'Common signs: pale ndani ya eyelids na palms, tiredness, breathlessness kupanda stairs, palpitations, headache, poor concentration. Kwa watoto: pallor, poor appetite, poor growth, irritability. Many people wenye mild anaemia hawana symptoms — only blood test inareveal it. Pregnant women, children under 5, na watu wenye chronic illness wapaswa kuscreened routinely.' } },
    { q: { en: 'Can anaemia be prevented?', sw: 'Anaemia inaweza kuzuiwa?' }, a: { en: 'Yes for many causes: iron-rich diet, deworming twice a year in school children and farmers, sleeping under insecticide-treated bednets to prevent malaria, treating heavy menstruation, antenatal iron + folic acid in pregnancy, breastfeeding for 6 months, fortified flour at population level. Sickle cell anaemia cannot be prevented but its complications can be reduced.', sw: 'Ndio kwa sababu nyingi: lishe yenye chuma, deworming mara mbili kwa mwaka kwa watoto wa shule na wakulima, kulala chini ya neti zenye dawa za kuua wadudu kuzuia malaria, kutibu hedhi kali, chuma + folic acid kabla ya kuzaa katika mimba, kunyonyesha kwa miezi 6, unga uliotajirishwa katika kiwango cha idadi ya watu. Anaemia ya selimundu haiwezi kuzuiwa lakini matatizo yake yanaweza kupunguzwa.', sw_mtaa: 'Ndio kwa many causes: iron-rich diet, deworming twice a year kwa school children na farmers, kulala chini ya insecticide-treated bednets kuzuia malaria, kutreating heavy menstruation, antenatal iron + folic acid katika pregnancy, breastfeeding kwa miezi 6, fortified flour at population level. Sickle cell anaemia haiwezi kuzuiwa lakini complications zake zinaweza kupunguzwa.' } },
  ],
  selfManagement: [
    { en: 'Take iron tablets daily as prescribed, with vitamin C and away from tea/coffee.', sw: 'Chukua tembe za chuma kila siku kama ilivyoamriwa, na vitamini C na mbali na chai/kahawa.', sw_mtaa: 'Chukua iron tablets daily as prescribed, na vitamin C na mbali na tea/coffee.' },
    { en: 'Eat iron-rich foods: red meat, liver, fish, beans, lentils, dark green leafy vegetables, fortified flour.', sw: 'Kula vyakula vyenye chuma: nyama nyekundu, ini, samaki, maharage, dengu, mboga za kijani kibichi, unga uliotajirishwa.', sw_mtaa: 'Kula iron-rich foods: red meat, liver, samaki, beans, lentils, dark green leafy vegetables, fortified flour.' },
    { en: 'Sleep under an insecticide-treated bednet every night, especially in pregnancy and for children.', sw: 'Lala chini ya neti yenye dawa ya kuua wadudu kila usiku, hasa katika mimba na kwa watoto.', sw_mtaa: 'Lala chini ya insecticide-treated bednet kila usiku, especially katika pregnancy na kwa children.' },
    { en: 'Take deworming tablets twice a year in endemic areas, especially school-age children and farmers.', sw: 'Chukua tembe za deworming mara mbili kwa mwaka katika maeneo endemic, hasa watoto wa umri wa shule na wakulima.', sw_mtaa: 'Chukua deworming tablets twice a year katika endemic areas, especially school-age children na farmers.' },
    { en: 'Pregnant women: attend ANC early and take iron + folic acid throughout pregnancy as prescribed.', sw: 'Wanawake wajawazito: hudhuria ANC mapema na chukua chuma + folic acid katika mimba yote kama ilivyoamriwa.', sw_mtaa: 'Pregnant women: hudhuria ANC early na chukua iron + folic acid katika pregnancy yote as prescribed.' },
  ],
  warningTriggers: [
    { en: 'Heavy menstruation, frequent pregnancies', sw: 'Hedhi kali, mimba za mara kwa mara', sw_mtaa: 'Heavy menstruation, frequent pregnancies' },
    { en: 'Poor diet — low intake of meat, eggs, beans, leafy vegetables', sw: 'Lishe duni — ulaji mdogo wa nyama, mayai, maharage, mboga za majani', sw_mtaa: 'Poor diet — low intake of meat, eggs, beans, leafy vegetables' },
    { en: 'Hookworm — barefoot in fields, contaminated soil', sw: 'Hookworm — peku katika mashamba, udongo uliochafuliwa', sw_mtaa: 'Hookworm — barefoot katika fields, contaminated soil' },
    { en: 'Repeated malaria — especially in children', sw: 'Malaria ya mara kwa mara — hasa kwa watoto', sw_mtaa: 'Repeated malaria — especially kwa watoto' },
    { en: 'Chronic disease — HIV, TB, kidney disease, cancer', sw: 'Magonjwa sugu — VVU, TB, ugonjwa wa figo, saratani', sw_mtaa: 'Chronic disease — HIV, TB, kidney disease, cancer' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Very pale, weak, fast heart rate, fainting — severe anaemia, may need urgent transfusion', sw: 'Kufifia sana, dhaifu, mapigo ya moyo ya haraka, kuzimia — anaemia kali, inaweza kuhitaji kuongezewa damu haraka', sw_mtaa: 'Very pale, weak, fast heart rate, fainting — severe anaemia, inaweza kuhitaji urgent transfusion' }, urgency: 'emergency' },
    { sign: { en: 'Bleeding (heavy menstruation, melaena, vomiting blood) with anaemia', sw: 'Kutokwa damu (hedhi kali, kinyesi cheusi, kutapika damu) na anaemia', sw_mtaa: 'Bleeding (heavy menstruation, melaena, vomiting blood) na anaemia' }, urgency: 'urgent' },
    { sign: { en: 'New anaemia in someone over 50 — investigate for GI bleeding/cancer', sw: 'Anaemia mpya kwa mtu zaidi ya miaka 50 — chunguza kwa kutokwa damu kwa utumbo/saratani', sw_mtaa: 'New anaemia kwa mtu over 50 — investigate kwa GI bleeding/cancer' }, urgency: 'urgent' },
    { sign: { en: 'Anaemia in pregnancy — must be treated to reduce maternal and fetal risk', sw: 'Anaemia katika mimba — lazima itibiwe kupunguza hatari ya kimama na ya kijusi', sw_mtaa: 'Anaemia katika pregnancy — lazima itibiwe kupunguza maternal na fetal risk' }, urgency: 'urgent' },
    { sign: { en: 'Anaemia in a child not responding to iron after 4 weeks — re-investigate', sw: 'Anaemia kwa mtoto asiyejibu chuma baada ya wiki 4 — chunguza tena', sw_mtaa: 'Anaemia kwa mtoto asiyejibu iron baada ya wiki 4 — re-investigate' }, urgency: 'routine' },
  ],
  comorbidityNotes: [
    { coCondition: 'malaria', note: { en: 'Malaria is one of the commonest causes of anaemia in Tanzanian children. Every child with severe anaemia in a malaria area should be tested and treated for malaria.', sw: 'Malaria ni mojawapo ya sababu kuu zaidi za anaemia kwa watoto wa Tanzania. Kila mtoto mwenye anaemia kali katika eneo la malaria anapaswa kupimwa na kutibiwa kwa malaria.', sw_mtaa: 'Malaria ni mojawapo ya commonest causes za anaemia kwa Tanzanian children. Kila mtoto mwenye severe anaemia katika malaria area apaswa kupimwa na kutreated kwa malaria.' } },
    { coCondition: 'maternal_care', note: { en: 'Anaemia in pregnancy raises risk of PPH, preterm birth, and low birth weight. Routine iron + folic acid is part of WHO ANC. Severe anaemia near term may need transfusion before delivery.', sw: 'Anaemia katika mimba huongeza hatari ya PPH, kuzaa mapema, na uzito mdogo wa kuzaliwa. Chuma + folic acid ya kawaida ni sehemu ya ANC ya WHO. Anaemia kali karibu na muda wa kuzaa inaweza kuhitaji kuongezewa damu kabla ya kuzaa.', sw_mtaa: 'Anaemia katika pregnancy inaraise risk ya PPH, preterm birth, na low birth weight. Routine iron + folic acid ni sehemu ya WHO ANC. Severe anaemia near term inaweza kuhitaji transfusion kabla ya delivery.' } },
    { coCondition: 'sickle_cell', note: { en: 'Sickle cell disease causes lifelong haemolytic anaemia. Iron is NOT routinely given (sickle cell patients are usually not iron-deficient) — folic acid 5 mg daily is standard.', sw: 'Ugonjwa wa selimundu husababisha anaemia ya haemolytic ya maisha. Chuma HAITOLEWI kawaida (wagonjwa wa selimundu kawaida hawana upungufu wa chuma) — folic acid 5 mg kila siku ni ya kawaida.', sw_mtaa: 'Sickle cell disease inasababisha lifelong haemolytic anaemia. Iron HAITOLEWI routinely (sickle cell patients kawaida hawana iron-deficient) — folic acid 5 mg daily ni standard.' } },
  ],
  sources: [src('WHO_ANAEMIA_2023'), src('NTLG_STG_2023'), src('WHO_ANC_2016'), src('IMCI_2024')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
