/**
 * Bronchiolitis — Phase 15 pediatric respiratory. Sources: IMCI 2024, WHO, NTLG.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const BRONCHIOLITIS: ConditionKnowledge = {
  id: 'bronchiolitis',
  aliases: CONDITION_ALIASES.bronchiolitis,
  category: 'pediatric',
  whatItIs: {
    en: 'Bronchiolitis is a viral infection of the smallest airways (bronchioles) in babies under 2 years, most commonly caused by respiratory syncytial virus (RSV). It starts like a cold (runny nose, mild fever, cough) for 2-3 days, then progresses to wheezing, fast breathing, and difficulty feeding because the baby cannot suck and breathe. Most babies have mild illness and recover at home. Babies under 3 months, those with congenital heart disease, prematurity, or HIV are at higher risk of severe disease needing hospital admission.',
    sw: 'Bronchiolitis ni maambukizi ya virusi ya njia ndogo za hewa (bronchioles) kwa watoto chini ya miaka 2, mara nyingi inasababishwa na respiratory syncytial virus (RSV). Huanza kama mafua (pua kukimbia, homa ndogo, kikohozi) kwa siku 2-3, kisha hutoka kwa kupuza (wheezing), kupumua kwa haraka, na ugumu wa kunyonya kwa sababu mtoto hawezi kunyonya na kupumua. Watoto wengi wana ugonjwa mdogo na hupona nyumbani. Watoto chini ya miezi 3, wenye ugonjwa wa moyo wa kuzaliwa nao, kuzaliwa kabla ya wakati, au VVU wako katika hatari kubwa ya ugonjwa mkali unaohitaji kulazwa hospitalini.',
    sw_mtaa: 'Bronchiolitis ni viral infection ya smallest airways (bronchioles) kwa babies under miaka 2, mara nyingi inasababishwa na respiratory syncytial virus (RSV). Inaanza kama cold (runny nose, mild fever, cough) kwa siku 2-3, kisha inaprogress kwa wheezing, fast breathing, na difficulty feeding kwa sababu baby hawezi kunyonya na kupumua. Most babies wana mild illness na wanarecover nyumbani. Babies under miezi 3, wenye congenital heart disease, prematurity, au HIV wako katika higher risk ya severe disease inayohitaji hospital admission.',
  },
  whyItMatters: {
    en: 'Bronchiolitis is a leading cause of admission in babies in Tanzania during the cool/wet season. The critical message to families: most cases are viral and antibiotics, salbutamol, and steroids do NOT help — they are often given out of habit but have no benefit in classic bronchiolitis. Supportive care (oxygen if SpO2 < 92%, small frequent feeds or NG tube if not feeding, fluids, paracetamol for fever) is what saves lives. The other critical point is recognising danger signs: fast breathing, indrawing, grunting, blue lips, lethargy, refusing feeds — IMCI red flags. Bronchiolitis can also be the trigger that unmasks asthma in older children, but in the under-2s wheezing + cold-like symptoms is usually bronchiolitis.',
    sw: 'Bronchiolitis ni sababu kuu ya kulazwa kwa watoto Tanzania wakati wa msimu wa baridi/mvua. Ujumbe muhimu kwa familia: kesi nyingi ni za virusi na antibiotic, salbutamol, na steroid HAZISAIDII — mara nyingi hutolewa kwa mazoea lakini hazina manufaa katika bronchiolitis ya kawaida. Huduma ya kuunga mkono (oksijeni ikiwa SpO2 < 92%, milo midogo ya mara kwa mara au mrija wa NG ikiwa hanyonyi, maji, paracetamol kwa homa) ndio inayookoa maisha. Jambo lingine muhimu ni kutambua ishara za hatari: kupumua kwa haraka, kuingia ndani kwa kifua, kukokota, midomo ya bluu, uchovu, kukataa kunyonya — alama nyekundu za IMCI. Bronchiolitis pia inaweza kuwa kichocheo kinachofunua pumu kwa watoto wakubwa, lakini kwa wa chini ya miaka 2 kupuza + dalili kama za mafua kwa kawaida ni bronchiolitis.',
    sw_mtaa: 'Bronchiolitis ni leading cause ya admission kwa babies Tanzania during cool/wet season. Critical message kwa families: most cases ni viral na antibiotics, salbutamol, na steroids HAZISAIDII — mara nyingi zinatolewa out of habit lakini hazina benefit katika classic bronchiolitis. Supportive care (oxygen ikiwa SpO2 < 92%, small frequent feeds au NG tube ikiwa hanyonyi, fluids, paracetamol kwa fever) ndio inayookoa lives. Other critical point ni kurecognise danger signs: fast breathing, indrawing, grunting, blue lips, lethargy, refusing feeds — IMCI red flags. Bronchiolitis pia inaweza kuwa trigger inayounmask asthma kwa older children, lakini kwa under-2s wheezing + cold-like symptoms kawaida ni bronchiolitis.',
  },
  commonQuestions: [
    { q: { en: 'How is bronchiolitis treated?', sw: 'Bronchiolitis inatibiwaje?' }, a: { en: 'Supportive care is the mainstay: nasal saline drops to clear blocked nose, small frequent feeds (or NG feeds if too breathless to suck), paracetamol for fever, oxygen if SpO2 < 92%. NO antibiotics (unless secondary bacterial infection), NO steroids (no benefit), NO salbutamol (no benefit in classic bronchiolitis under 12 months — though a trial dose is reasonable in older infants who may have viral-induced wheeze). Most babies improve over 7-10 days. Cough can persist for 2-3 weeks.', sw: 'Huduma ya kuunga mkono ni msingi: matone ya saline puani kusafisha pua iliyoziba, milo midogo ya mara kwa mara (au milo ya NG ikiwa anashindwa kupumua sana kunyonya), paracetamol kwa homa, oksijeni ikiwa SpO2 < 92%. HAKUNA antibiotic (isipokuwa maambukizi ya bakteria ya pili), HAKUNA steroid (hakuna manufaa), HAKUNA salbutamol (hakuna manufaa katika bronchiolitis ya kawaida chini ya miezi 12 — ingawa dose ya jaribio ni busara kwa watoto wakubwa wanaoweza kuwa na kupuza kunakosababishwa na virusi). Watoto wengi huimarika kwa siku 7-10. Kikohozi kinaweza kudumu wiki 2-3.', sw_mtaa: 'Supportive care ni mainstay: nasal saline drops kusafisha blocked nose, small frequent feeds (au NG feeds ikiwa too breathless kunyonya), paracetamol kwa fever, oxygen ikiwa SpO2 < 92%. NO antibiotics (isipokuwa secondary bacterial infection), NO steroids (no benefit), NO salbutamol (no benefit katika classic bronchiolitis under 12 months — ingawa trial dose ni reasonable kwa older infants wanaoweza kuwa na viral-induced wheeze). Most babies wanaimprove over siku 7-10. Cough inaweza kupersist wiki 2-3.' } },
    { q: { en: 'When should I take my baby to hospital?', sw: 'Nimpeleke mtoto wangu hospitalini lini?' }, a: { en: 'Go urgently if: fast breathing (>60 breaths/min in baby <2 months, >50 in 2-12 months, >40 in 1-5 years), indrawing/recession of the chest, grunting noises, blue lips or fingertips, refusing all feeds or vomiting all feeds, very sleepy/hard to wake, less than half normal nappies. Babies under 3 months with any respiratory symptoms should be assessed early — they tire quickly.', sw: 'Nenda haraka ikiwa: kupumua kwa haraka (>pumzi 60/dakika kwa mtoto <miezi 2, >50 kwa miezi 2-12, >40 kwa mwaka 1-5), kuingia ndani/recession ya kifua, sauti za kukokota, midomo ya bluu au ncha za vidole, kukataa milo yote au kutapika milo yote, kulala sana/kushindwa kuamka, chini ya nusu ya nepi za kawaida. Watoto chini ya miezi 3 wenye dalili yoyote ya kupumua wanapaswa kupimwa mapema — huchoka haraka.', sw_mtaa: 'Nenda urgently ikiwa: fast breathing (>breaths 60/min kwa baby <miezi 2, >50 kwa miezi 2-12, >40 kwa mwaka 1-5), indrawing/recession ya chest, grunting noises, blue lips au fingertips, refusing all feeds au vomiting all feeds, very sleepy/hard kuamka, less than half normal nappies. Babies under miezi 3 wenye respiratory symptoms yoyote wapimwa early — wanachoka haraka.' } },
    { q: { en: 'Can bronchiolitis be prevented?', sw: 'Bronchiolitis inaweza kuzuiwa?' }, a: { en: 'Reduce risk by: washing hands before handling baby, avoiding crowded smoky environments (especially biomass cooking smoke and tobacco smoke), keeping people with colds away from young babies, exclusive breastfeeding for 6 months (provides immune protection), full immunisation. Newer RSV vaccines/antibodies (nirsevimab, maternal RSV vaccine) reduce RSV bronchiolitis substantially but availability in Tanzania is limited so far.', sw: 'Punguza hatari kwa: kuosha mikono kabla ya kushika mtoto, kuepuka mazingira yenye msongamano na moshi (hasa moshi wa kupika wa biomass na moshi wa tumbaku), kuwaweka watu wenye mafua mbali na watoto wadogo, kunyonyesha pekee kwa miezi 6 (hutoa ulinzi wa kinga), chanjo kamili. Chanjo/antibodies mpya za RSV (nirsevimab, chanjo ya RSV ya kimama) hupunguza bronchiolitis ya RSV kwa kiasi kikubwa lakini upatikanaji Tanzania ni mdogo hadi sasa.', sw_mtaa: 'Reduce risk kwa: kuwash hands kabla ya kushika baby, kuepuka crowded smoky environments (especially biomass cooking smoke na tobacco smoke), kuweka watu wenye colds mbali na young babies, exclusive breastfeeding kwa miezi 6 (inatoa immune protection), full immunisation. Newer RSV vaccines/antibodies (nirsevimab, maternal RSV vaccine) zinareduce RSV bronchiolitis substantially lakini availability Tanzania ni limited so far.' } },
    { q: { en: 'Will my baby get asthma later?', sw: 'Mtoto wangu atapata pumu baadaye?' }, a: { en: 'Some babies who have severe bronchiolitis are more likely to develop wheeze with future colds or asthma later, but most do not. The link is not because bronchiolitis caused asthma, but because both share predisposing factors. Smoke exposure in childhood (biomass cooking, tobacco) is a major preventable risk for both.', sw: 'Watoto wengine wenye bronchiolitis kali wana uwezekano mkubwa wa kupata kupuza na mafua ya baadaye au pumu, lakini wengi hawapati. Uhusiano sio kwa sababu bronchiolitis ilisababisha pumu, bali kwa sababu zote mbili zinashiriki sababu za kuhusisha. Mfiduo wa moshi utotoni (kupika kwa biomass, tumbaku) ni hatari kuu inayozuilika kwa zote mbili.', sw_mtaa: 'Some babies wenye severe bronchiolitis ni more likely kuendeloea wheeze na future colds au asthma later, lakini most hawana. Link sio kwa sababu bronchiolitis ilisababisha asthma, bali kwa sababu zote zinashiriki predisposing factors. Smoke exposure utotoni (biomass cooking, tobacco) ni major preventable risk kwa both.' } },
  ],
  selfManagement: [
    { en: 'Nasal saline drops before feeds clear the nose and help feeding.', sw: 'Matone ya saline puani kabla ya milo husafisha pua na husaidia kunyonya.', sw_mtaa: 'Nasal saline drops kabla ya feeds zinasafisha nose na zinasaidia feeding.' },
    { en: 'Offer smaller, more frequent feeds (or expressed breast milk by cup/spoon if too breathless to suck).', sw: 'Toa milo midogo zaidi, ya mara kwa mara zaidi (au maziwa ya mama yaliyotolewa kwa kikombe/kijiko ikiwa anashindwa kupumua sana kunyonya).', sw_mtaa: 'Toa smaller, more frequent feeds (au expressed breast milk kwa cup/spoon ikiwa too breathless kunyonya).' },
    { en: 'Paracetamol for fever and discomfort — at correct weight-based dose. Do NOT give ibuprofen under 3 months.', sw: 'Paracetamol kwa homa na usumbufu — kwa dose sahihi kulingana na uzito. USIMPE ibuprofen chini ya miezi 3.', sw_mtaa: 'Paracetamol kwa fever na discomfort — kwa correct weight-based dose. USIMPE ibuprofen under miezi 3.' },
    { en: 'Keep baby upright when feeding and during sleep on a slight incline to help breathing.', sw: 'Mhifadhi mtoto wima wakati wa kunyonya na wakati wa kulala kwa mwinuko mdogo kusaidia kupumua.', sw_mtaa: 'Keep baby upright wakati wa feeding na wakati wa sleep kwa slight incline kusaidia breathing.' },
    { en: 'Avoid smoke exposure — keep cooking fires away from where baby sleeps, no tobacco smoke indoors.', sw: 'Epuka mfiduo wa moshi — weka moto wa kupika mbali na anakolala mtoto, hakuna moshi wa tumbaku ndani.', sw_mtaa: 'Epuka smoke exposure — keep cooking fires mbali na where baby sleeps, no tobacco smoke indoors.' },
  ],
  warningTriggers: [
    { en: 'RSV season — usually cool/wet months', sw: 'Msimu wa RSV — kawaida miezi ya baridi/mvua', sw_mtaa: 'RSV season — kawaida cool/wet months' },
    { en: 'Crowded living, daycare, older siblings with colds', sw: 'Maisha ya msongamano, daycare, watoto wakubwa wenye mafua', sw_mtaa: 'Crowded living, daycare, older siblings wenye colds' },
    { en: 'Biomass cooking smoke or tobacco smoke exposure', sw: 'Mfiduo wa moshi wa kupika wa biomass au moshi wa tumbaku', sw_mtaa: 'Biomass cooking smoke au tobacco smoke exposure' },
    { en: 'Prematurity, congenital heart disease, immunodeficiency including HIV', sw: 'Kuzaliwa mapema, ugonjwa wa moyo wa kuzaliwa, ukosefu wa kinga ikijumuisha VVU', sw_mtaa: 'Prematurity, congenital heart disease, immunodeficiency including HIV' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Fast breathing (using IMCI thresholds) or indrawing — IMCI emergency signs', sw: 'Kupumua kwa haraka (kutumia vizingiti vya IMCI) au kuingia ndani — ishara za dharura za IMCI', sw_mtaa: 'Fast breathing (using IMCI thresholds) au indrawing — IMCI emergency signs' }, urgency: 'emergency' },
    { sign: { en: 'Blue lips or fingertips, severe respiratory distress — emergency', sw: 'Midomo ya bluu au ncha za vidole, kushindwa kupumua sana — dharura', sw_mtaa: 'Blue lips au fingertips, severe respiratory distress — emergency' }, urgency: 'emergency' },
    { sign: { en: 'Refusing all feeds or vomiting all feeds — dehydration risk, emergency for baby <3 months', sw: 'Kukataa milo yote au kutapika milo yote — hatari ya kukosa maji, dharura kwa mtoto <miezi 3', sw_mtaa: 'Refusing all feeds au vomiting all feeds — dehydration risk, emergency kwa baby <miezi 3' }, urgency: 'emergency' },
    { sign: { en: 'Lethargy, unresponsive, or seizure — emergency', sw: 'Uchovu, kutoitikia, au mzozo — dharura', sw_mtaa: 'Lethargy, unresponsive, au seizure — emergency' }, urgency: 'emergency' },
    { sign: { en: 'Apnea (pauses in breathing) — common in young babies with RSV — emergency', sw: 'Apnea (kusimama kwa kupumua) — kawaida kwa watoto wadogo wenye RSV — dharura', sw_mtaa: 'Apnea (pauses katika breathing) — common kwa young babies wenye RSV — emergency' }, urgency: 'emergency' },
  ],
  comorbidityNotes: [
    { coCondition: 'pneumonia', note: { en: 'Bronchiolitis and pneumonia overlap clinically in young babies. IMCI thresholds for fast breathing apply equally. Antibiotics are given for pneumonia but not for pure bronchiolitis — chest X-ray and clinical course help distinguish.', sw: 'Bronchiolitis na nimonia zinaingiliana kimatibabu kwa watoto wadogo. Vizingiti vya IMCI vya kupumua kwa haraka vinatumika sawasawa. Antibiotic hutolewa kwa nimonia lakini si kwa bronchiolitis safi — X-ray ya kifua na mwendo wa kimatibabu husaidia kutofautisha.', sw_mtaa: 'Bronchiolitis na pneumonia zinaoverlap clinically kwa young babies. IMCI thresholds kwa fast breathing zinatumika equally. Antibiotics zinatolewa kwa pneumonia lakini si kwa pure bronchiolitis — chest X-ray na clinical course zinasaidia kudistinguish.' } },
    { coCondition: 'asthma', note: { en: 'Children with severe or recurrent bronchiolitis episodes may later develop asthma. Avoid smoke exposure throughout childhood.', sw: 'Watoto wenye vipindi vikali au vya mara kwa mara vya bronchiolitis wanaweza kuendeleza pumu baadaye. Epuka mfiduo wa moshi katika utoto wote.', sw_mtaa: 'Children wenye severe au recurrent bronchiolitis episodes wanaweza kuendeleza asthma later. Epuka smoke exposure katika utoto wote.' } },
  ],
  sources: [src('IMCI_2024'), src('WHO_PNEUMONIA_2022'), src('NTLG_STG_2023'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
