/**
 * Cervical Cancer — Phase 15. Sources: WHO Cervical 2022, NACP, NTLG.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const CERVICAL_CANCER: ConditionKnowledge = {
  id: 'cervical_cancer',
  aliases: CONDITION_ALIASES.cervical_cancer,
  category: 'oncologic',
  whatItIs: {
    en: 'Cervical cancer is cancer of the lower part of the womb (uterus) that opens into the vagina. Almost all cases are caused by long-term infection with high-risk types of human papillomavirus (HPV), a very common sexually-transmitted virus. Most HPV infections clear by themselves; in some women — especially with HIV — the virus persists and slowly causes pre-cancer changes over years, then cancer. Cervical cancer is the leading cancer among women in Tanzania, but it is one of the most preventable cancers: HPV vaccine in girls 9-14 prevents most cases, and routine screening (VIA — visual inspection with acetic acid — every 3 years from age 25-49) catches pre-cancer before it becomes cancer. Pre-cancer is curable with simple ablation (cryotherapy or thermal ablation) at the same screening visit.',
    sw: 'Saratani ya shingo ya kizazi (cervical cancer) ni saratani ya sehemu ya chini ya mji wa mimba inayofunguka katika uke. Kesi karibu zote husababishwa na maambukizi ya muda mrefu ya aina za hatari za human papillomavirus (HPV), virusi vya kawaida vya kuambukizwa kingono. Maambukizi mengi ya HPV hujiponya; kwa wanawake wengine — hasa wenye VVU — virusi hudumu na polepole husababisha mabadiliko ya kabla-saratani kwa miaka, kisha saratani. Saratani ya shingo ya kizazi ni saratani inayoongoza miongoni mwa wanawake Tanzania, lakini ni mojawapo ya saratani zinazoweza kuzuiwa zaidi: chanjo ya HPV kwa wasichana 9-14 huzuia kesi nyingi, na uchunguzi wa kawaida (VIA — uchunguzi wa kuonekana na asidi ya acetic — kila miaka 3 kutoka umri wa 25-49) hugundua kabla-saratani kabla ya kuwa saratani. Kabla-saratani inatibika kwa ablation rahisi (cryotherapy au thermal ablation) katika ziara ile ile ya uchunguzi.',
    sw_mtaa: 'Cervical cancer ni cancer ya lower part ya womb (uterus) inayofunguka katika vagina. Almost all cases zinasababishwa na long-term infection na high-risk types za HPV, very common sexually-transmitted virus. Most HPV infections zinajiponya by themselves; kwa some women — especially wenye HIV — virus inapersist na polepole inasababisha pre-cancer changes over years, kisha cancer. Cervical cancer ni leading cancer miongoni mwa women Tanzania, lakini ni mojawapo ya most preventable cancers: HPV vaccine kwa girls 9-14 inazuia most cases, na routine screening (VIA — visual inspection na acetic acid — kila miaka 3 kutoka age 25-49) inakamata pre-cancer kabla ya kuwa cancer. Pre-cancer inatibika na simple ablation (cryotherapy au thermal ablation) katika same screening visit.',
  },
  whyItMatters: {
    en: 'Tanzania has invested heavily in cervical cancer prevention: HPV vaccine is in the routine schedule for girls age 9-14, and VIA screening is rolled out across district hospitals and health centres. Two messages save the most lives. First — every girl should get the HPV vaccine before she becomes sexually active; even one dose gives strong protection. Second — every woman aged 25-49, especially women living with HIV (who should screen more often, from age 25 every 1-2 years), should attend cervical screening. Most women never feel any symptoms from pre-cancer or even early cancer — screening is the only way to catch it. Symptoms like bleeding between periods, bleeding after sex, smelly discharge, or bleeding after menopause must be investigated urgently.',
    sw: 'Tanzania imewekeza sana katika kuzuia saratani ya shingo ya kizazi: chanjo ya HPV iko katika ratiba ya kawaida kwa wasichana wa umri wa 9-14, na uchunguzi wa VIA umetolewa katika hospitali za wilaya na vituo vya afya. Ujumbe miwili huokoa maisha mengi zaidi. Kwanza — kila msichana anapaswa kupata chanjo ya HPV kabla hajawa active kingono; hata dose moja inatoa ulinzi mkali. Pili — kila mwanamke wa umri wa 25-49, hasa wanawake wanaoishi na VVU (wanapaswa kuchunguzwa mara nyingi zaidi, kutoka umri wa 25 kila miaka 1-2), wanapaswa kuhudhuria uchunguzi wa shingo ya kizazi. Wanawake wengi hawajisikii dalili yoyote kutoka kabla-saratani au hata saratani ya mapema — uchunguzi ndio njia pekee ya kuigundua. Dalili kama kutokwa damu kati ya hedhi, kutokwa damu baada ya ngono, uchafu unaonuka, au kutokwa damu baada ya menopause lazima zichunguzwe haraka.',
    sw_mtaa: 'Tanzania imewekeza sana katika cervical cancer prevention: HPV vaccine iko katika routine schedule kwa girls age 9-14, na VIA screening inarolled out across district hospitals na health centres. Two messages zinaokoa most lives. First — kila msichana apaswa kupata HPV vaccine kabla hajawa sexually active; even one dose inatoa strong protection. Second — kila mwanamke aged 25-49, especially women living with HIV (wapaswa kuscreen more often, kutoka age 25 kila miaka 1-2), wapaswa kuhudhuria cervical screening. Most women never feel symptoms yoyote kutoka pre-cancer au even early cancer — screening ni only way ya kuikamata. Symptoms kama bleeding between periods, bleeding baada ya sex, smelly discharge, au bleeding baada ya menopause lazima ziinvestigated urgently.',
  },
  commonQuestions: [
    { q: { en: 'What is HPV and how does it cause cervical cancer?', sw: 'HPV ni nini na inasababishaje saratani ya shingo ya kizazi?' }, a: { en: 'HPV is a virus passed during sexual contact — most sexually active people get it at some point. There are many types; about 14 high-risk types (especially HPV 16 and 18) can cause cervical cancer if infection persists for many years. The body usually clears HPV in 1-2 years, but in some women — especially those with HIV — it stays and slowly damages the cells of the cervix, eventually becoming cancer. HPV is also linked to anal, throat, penile, and vulval cancers.', sw: 'HPV ni virusi inayopita wakati wa mawasiliano ya kingono — watu wengi walio active kingono huipata wakati fulani. Kuna aina nyingi; aina karibu 14 za hatari (hasa HPV 16 na 18) zinaweza kusababisha saratani ya shingo ya kizazi ikiwa maambukizi yanadumu kwa miaka mingi. Mwili kawaida huondoa HPV katika miaka 1-2, lakini kwa wanawake wengine — hasa wenye VVU — inadumu na polepole inaharibu seli za shingo ya kizazi, hatimaye inakuwa saratani. HPV pia inahusishwa na saratani za njia ya haja kubwa, koo, uume, na vulva.', sw_mtaa: 'HPV ni virus inayopita wakati wa sexual contact — most sexually active people wanaipata at some point. Kuna many types; about 14 high-risk types (especially HPV 16 na 18) zinaweza kusababisha cervical cancer ikiwa infection inapersist kwa many years. Body usually inaclear HPV katika miaka 1-2, lakini kwa some women — especially wenye HIV — inadumu na polepole inaharibu cells za cervix, eventually inakuwa cancer. HPV pia inalinked kwa anal, throat, penile, na vulval cancers.' } },
    { q: { en: 'What is VIA screening?', sw: 'Uchunguzi wa VIA ni nini?' }, a: { en: 'VIA stands for Visual Inspection with Acetic Acid. A clinician (often a trained nurse) gently looks at the cervix with a speculum and paints it with vinegar (acetic acid). Pre-cancer areas turn white. The test takes a few minutes, costs little, and gives results immediately. If a white "VIA-positive" area is seen, it can usually be treated the same day with cryotherapy (freezing) or thermal ablation (heat) — called "screen-and-treat". Painful is mild and recovery is quick. Tanzania has rolled VIA out across most districts; ask at your nearest reproductive and child health clinic.', sw: 'VIA inasimama kwa Visual Inspection with Acetic Acid — uchunguzi wa kuonekana na asidi ya acetic. Daktari (mara nyingi muuguzi aliyefunzwa) anaangalia shingo ya kizazi kwa upole na speculum na anaipaka siki (asidi ya acetic). Maeneo ya kabla-saratani yanakuwa meupe. Kipimo kinachukua dakika chache, kina gharama ndogo, na hutoa matokeo mara moja. Ikiwa eneo jeupe la "VIA-chanya" linaonekana, linaweza kawaida kutibiwa siku ile ile na cryotherapy (kuganda) au thermal ablation (joto) — kuitwa "screen-and-treat". Maumivu ni madogo na kupona ni haraka. Tanzania imetoa VIA katika wilaya nyingi; uliza katika kliniki yako ya karibu zaidi ya afya ya uzazi na mtoto.', sw_mtaa: 'VIA inasimama kwa Visual Inspection with Acetic Acid. Clinician (mara nyingi trained nurse) anaangalia cervix kwa upole na speculum na anaipaint na vinegar (acetic acid). Pre-cancer areas zinakuwa white. Test inachukua dakika chache, ina gharama ndogo, na inatoa results immediately. Ikiwa white "VIA-positive" area linaonekana, linaweza usually kutibiwa same day na cryotherapy (kuganda) au thermal ablation (joto) — inaitwa "screen-and-treat". Pain ni mild na recovery ni haraka. Tanzania imerolled out VIA across most districts; uliza katika nearest reproductive na child health clinic yako.' } },
    { q: { en: 'Who should get the HPV vaccine?', sw: 'Nani anapaswa kupata chanjo ya HPV?' }, a: { en: 'Girls aged 9-14 are the priority — the vaccine is most effective before HPV exposure (before sexual activity). Tanzania offers HPV vaccine in this age group through schools and health facilities. The vaccine is safe, effective, and does NOT make young women infertile or promiscuous (common myths — both are false). Older girls and young women can also be vaccinated if not previously given, up to age 26 generally, with less benefit if already exposed. Boys can also be vaccinated (protects against other HPV-related cancers) where programmes include them.', sw: 'Wasichana wa umri wa 9-14 ni kipaumbele — chanjo ni yenye ufanisi zaidi kabla ya kufichuliwa kwa HPV (kabla ya shughuli ya kingono). Tanzania inatoa chanjo ya HPV katika kundi hili la umri kupitia shule na vituo vya afya. Chanjo ni salama, ya ufanisi, na HAILEI vijana wanawake kuwa tasa au wasiochaguzi (hadithi za kawaida — zote ni za uongo). Wasichana wakubwa na wanawake vijana wanaweza pia kupewa chanjo ikiwa hawajapewa hapo awali, hadi umri wa 26 kwa ujumla, na manufaa kidogo ikiwa tayari wamefichuliwa. Wavulana wanaweza pia kupewa chanjo (inalinda dhidi ya saratani nyingine zinazohusiana na HPV) pale programu zinapowaambia.', sw_mtaa: 'Girls aged 9-14 ni priority — vaccine ni most effective kabla ya HPV exposure (kabla ya sexual activity). Tanzania inatoa HPV vaccine katika age group hii kupitia schools na health facilities. Vaccine ni safe, effective, na HAILEI young women kuwa infertile au promiscuous (common myths — both ni false). Older girls na young women wanaweza pia kuvaccinated ikiwa hawajapewa previously, hadi age 26 generally, na less benefit ikiwa tayari exposed. Boys wanaweza pia kuvaccinated (inalinda dhidi ya other HPV-related cancers) pale programmes zinapowainclude.' } },
    { q: { en: 'I have HIV. Do I need different cervical screening?', sw: 'Nina VVU. Ninahitaji uchunguzi tofauti wa shingo ya kizazi?' }, a: { en: 'Yes. Women living with HIV develop cervical pre-cancer faster and more often than HIV-negative women, even on ART. WHO recommends starting cervical screening at age 25 (not 30) and screening more often — every 1-2 years, depending on local protocols and previous results. Tanzania\'s NACP integrates cervical screening into HIV care; ask at your CTC clinic. Being on ART with good viral suppression reduces (but does not eliminate) the risk. Pre-cancer treatment (cryotherapy/thermal ablation) is fully compatible with ART.', sw: 'Ndio. Wanawake wanaoishi na VVU huendeleza kabla-saratani ya shingo ya kizazi haraka na mara nyingi zaidi kuliko wanawake wasio na VVU, hata wakiwa kwenye ART. WHO inapendekeza kuanza uchunguzi wa shingo ya kizazi kutoka umri wa 25 (sio 30) na kuchunguzwa mara nyingi zaidi — kila miaka 1-2, kulingana na itifaki za ndani na matokeo ya awali. NACP ya Tanzania imeunganisha uchunguzi wa shingo ya kizazi katika huduma ya VVU; uliza katika kliniki yako ya CTC. Kuwa kwenye ART na ukandamizaji mzuri wa virusi hupunguza (lakini hauondoi) hatari. Matibabu ya kabla-saratani (cryotherapy/thermal ablation) yanaendana kabisa na ART.', sw_mtaa: 'Ndio. Women living with HIV wanadevelop cervical pre-cancer faster na more often kuliko HIV-negative women, even on ART. WHO inarecommend kuanza cervical screening at age 25 (sio 30) na kuscreen more often — kila miaka 1-2, depending on local protocols na previous results. Tanzania\'s NACP inaintegrate cervical screening katika HIV care; uliza katika CTC clinic yako. Kuwa on ART na good viral suppression inareduce (lakini haiondoi) risk. Pre-cancer treatment (cryotherapy/thermal ablation) inaendana kabisa na ART.' } },
  ],
  selfManagement: [
    { en: 'Get HPV vaccine for your daughters at age 9-14 — the single most effective prevention.', sw: 'Pata chanjo ya HPV kwa binti zako wa umri wa 9-14 — kuzuia moja yenye ufanisi zaidi.', sw_mtaa: 'Pata HPV vaccine kwa binti zako age 9-14 — single most effective prevention.' },
    { en: 'Attend cervical screening (VIA) every 3 years from age 25-49 (more often if HIV-positive).', sw: 'Hudhuria uchunguzi wa shingo ya kizazi (VIA) kila miaka 3 kutoka umri wa 25-49 (mara nyingi zaidi ikiwa una VVU).', sw_mtaa: 'Hudhuria cervical screening (VIA) kila miaka 3 kutoka age 25-49 (more often ikiwa HIV-positive).' },
    { en: 'If screening is positive, accept same-day treatment — it is brief and curative for pre-cancer.', sw: 'Ikiwa uchunguzi ni chanya, kubali matibabu ya siku ile ile — ni mafupi na ya kuponya kwa kabla-saratani.', sw_mtaa: 'Ikiwa screening ni positive, accept same-day treatment — ni brief na curative kwa pre-cancer.' },
    { en: 'Use condoms — they reduce (do not eliminate) HPV transmission and protect against other STIs.', sw: 'Tumia kondomu — hupunguza (haziondoi) maambukizi ya HPV na hulinda dhidi ya STI nyingine.', sw_mtaa: 'Tumia condoms — zinareduce (hazielimitate) HPV transmission na zinalinda dhidi ya other STIs.' },
    { en: 'Stop smoking — smoking accelerates HPV-related cancer development.', sw: 'Acha sigara — sigara hukimbiza maendeleo ya saratani inayohusiana na HPV.', sw_mtaa: 'Acha sigara — smoking inaaccelerate HPV-related cancer development.' },
  ],
  warningTriggers: [
    { en: 'HIV infection — accelerates HPV persistence and cancer development', sw: 'Maambukizi ya VVU — hukimbiza HPV kudumu na maendeleo ya saratani', sw_mtaa: 'HIV infection — inaaccelerate HPV persistence na cancer development' },
    { en: 'Multiple sexual partners or early age of first intercourse', sw: 'Wenza wengi wa kingono au umri mdogo wa kuanza ngono', sw_mtaa: 'Multiple sexual partners au early age ya first intercourse' },
    { en: 'Smoking', sw: 'Sigara', sw_mtaa: 'Smoking' },
    { en: 'Not attending cervical screening', sw: 'Kutohudhuria uchunguzi wa shingo ya kizazi', sw_mtaa: 'Kutohudhuria cervical screening' },
    { en: 'No HPV vaccination', sw: 'Hakuna chanjo ya HPV', sw_mtaa: 'No HPV vaccination' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Bleeding between periods, bleeding after sex, or bleeding after menopause — urgent gynaecology assessment', sw: 'Kutokwa damu kati ya hedhi, kutokwa damu baada ya ngono, au kutokwa damu baada ya menopause — tathmini ya haraka ya gynaecology', sw_mtaa: 'Bleeding between periods, bleeding baada ya sex, au bleeding baada ya menopause — urgent gynaecology assessment' }, urgency: 'urgent' },
    { sign: { en: 'Smelly, blood-stained, or watery vaginal discharge — needs assessment', sw: 'Uchafu wa uke unaonuka, wenye damu, au wa maji — unahitaji tathmini', sw_mtaa: 'Smelly, blood-stained, au watery vaginal discharge — inahitaji assessment' }, urgency: 'urgent' },
    { sign: { en: 'Pelvic pain, leg swelling, or kidney pain in someone with cervical cancer — possible advanced disease', sw: 'Maumivu ya pelvic, uvimbe wa miguu, au maumivu ya figo kwa mtu mwenye saratani ya shingo ya kizazi — uwezekano wa ugonjwa wa hali ya juu', sw_mtaa: 'Pelvic pain, leg swelling, au kidney pain kwa mtu mwenye cervical cancer — possible advanced disease' }, urgency: 'urgent' },
    { sign: { en: 'Any woman age 25-49 who has never been screened — book screening at the next clinic visit', sw: 'Mwanamke yeyote wa umri wa 25-49 ambaye hajawahi kuchunguzwa — andikisha uchunguzi katika ziara ijayo ya kliniki', sw_mtaa: 'Woman yeyote age 25-49 ambaye never been screened — book screening katika next clinic visit' }, urgency: 'routine' },
  ],
  comorbidityNotes: [
    { coCondition: 'hiv', note: { en: 'Women with HIV have 6x higher risk of cervical cancer. NACP integrates cervical screening into HIV care: start screening at age 25, every 1-2 years. ART reduces but does not eliminate risk. Cervical screening is a standard part of comprehensive HIV care for women.', sw: 'Wanawake wenye VVU wana hatari ya mara 6 zaidi ya saratani ya shingo ya kizazi. NACP imeunganisha uchunguzi wa shingo ya kizazi katika huduma ya VVU: anza uchunguzi kutoka umri wa 25, kila miaka 1-2. ART hupunguza lakini hauondoi hatari. Uchunguzi wa shingo ya kizazi ni sehemu ya kawaida ya huduma kamili ya VVU kwa wanawake.', sw_mtaa: 'Women wenye HIV wana 6x higher risk ya cervical cancer. NACP imeintegrate cervical screening katika HIV care: start screening at age 25, kila miaka 1-2. ART inareduce lakini haiondoi risk. Cervical screening ni standard part ya comprehensive HIV care kwa women.' } },
  ],
  sources: [src('WHO_CERVICAL_2022'), src('NACP_ART_2024'), src('NTLG_STG_2023'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
