/**
 * Epilepsy — Phase 15. Sources: WHO mhGAP 2023, WHO Epilepsy 2022, NTLG.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const EPILEPSY: ConditionKnowledge = {
  id: 'epilepsy',
  aliases: CONDITION_ALIASES.epilepsy,
  category: 'neurologic',
  whatItIs: {
    en: 'Epilepsy is a brain condition in which a person has had two or more unprovoked seizures (or one seizure with strong risk of recurrence). A seizure is a sudden burst of abnormal electrical activity in the brain — it can cause loss of consciousness with whole-body shaking (generalised tonic-clonic), staring spells (absence seizures), or unusual sensations or movements affecting one part of the body (focal seizures). Most people with epilepsy can be well-controlled on a single anti-seizure medication and live full, productive lives. Epilepsy is not contagious, it is not caused by witchcraft or curse, and it is not a punishment — it is a brain condition like any other.',
    sw: 'Kifafa (epilepsy) ni hali ya ubongo ambapo mtu amekuwa na mzozo wa kifafa mawili au zaidi yasiyochochewa (au mzozo mmoja na hatari kubwa ya kurudia). Mzozo wa kifafa ni mlipuko wa ghafla wa shughuli za umeme zisizo za kawaida katika ubongo — unaweza kusababisha kupoteza fahamu pamoja na kutetemeka kwa mwili mzima (generalised tonic-clonic), vipindi vya kushtua macho (absence seizures), au hisia au harakati zisizo za kawaida zinazoathiri sehemu moja ya mwili (focal seizures). Watu wengi wenye kifafa wanaweza kudhibitiwa vyema kwa dawa moja ya kupambana na mzozo na kuishi maisha kamili, yenye uzalishaji. Kifafa hakiambukizwi, hakisababishwi na uchawi au laana, na sio adhabu — ni hali ya ubongo kama nyingine yoyote.',
    sw_mtaa: 'Epilepsy ni brain condition ambapo mtu amekuwa na two au more unprovoked seizures (au one seizure na strong risk ya recurrence). Seizure ni sudden burst ya abnormal electrical activity katika brain — inaweza kusababisha loss of consciousness na whole-body shaking (generalised tonic-clonic), staring spells (absence seizures), au unusual sensations au movements zinazoaffect one part ya body (focal seizures). Most people wenye epilepsy wanaweza kuwell-controlled na single anti-seizure medication na kuishi full, productive lives. Epilepsy haiambukizi, haisababishwi na witchcraft au curse, na sio punishment — ni brain condition kama nyingine yoyote.',
  },
  whyItMatters: {
    en: 'In Tanzania, the treatment gap for epilepsy is huge — most people with epilepsy do not receive medication, despite the WHO essential drugs (phenobarbitone, carbamazepine, sodium valproate, phenytoin) being affordable and effective. Untreated epilepsy causes injury (burns from cooking fires, drowning, road accidents), school dropout, unemployment, and severe stigma. The mhGAP framework supports primary-care management — most stable epilepsy can be managed by clinical officers and nurses, not only neurologists. The two most important practical points for families: (1) treatment is daily and lifelong for most people, missing doses causes breakthrough seizures, (2) status epilepticus (a seizure lasting more than 5 minutes or repeating without recovery) is a medical emergency.',
    sw: 'Tanzania, pengo la matibabu ya kifafa ni kubwa — watu wengi wenye kifafa hawapokei dawa, licha ya dawa muhimu za WHO (phenobarbitone, carbamazepine, sodium valproate, phenytoin) kuwa za nafuu na za ufanisi. Kifafa kisichotibiwa husababisha jeraha (kuungua kutoka moto wa kupika, kuzama, ajali za barabarani), kuachisha shule, ukosefu wa ajira, na unyanyapaa mkali. Mfumo wa mhGAP unaunga mkono usimamizi wa huduma ya msingi — kifafa kingi imara kinaweza kusimamiwa na clinical officer na wauguzi, sio wataalamu wa neva tu. Mambo mawili muhimu zaidi ya vitendo kwa familia: (1) matibabu ni ya kila siku na ya maisha kwa watu wengi, kukosa dose husababisha mzozo wa breakthrough, (2) status epilepticus (mzozo unaodumu zaidi ya dakika 5 au unaorudia bila kupona) ni dharura ya matibabu.',
    sw_mtaa: 'Tanzania, treatment gap kwa epilepsy ni huge — most people wenye epilepsy hawapokei medication, licha ya WHO essential drugs (phenobarbitone, carbamazepine, sodium valproate, phenytoin) kuwa affordable na effective. Untreated epilepsy inasababisha injury (burns kutoka cooking fires, drowning, road accidents), school dropout, unemployment, na severe stigma. mhGAP framework inasupport primary-care management — most stable epilepsy inaweza kumanaged na clinical officers na nurses, sio neurologists tu. Two most important practical points kwa families: (1) treatment ni daily na lifelong kwa most people, missing doses inasababisha breakthrough seizures, (2) status epilepticus (seizure lasting zaidi ya dakika 5 au repeating bila recovery) ni medical emergency.',
  },
  commonQuestions: [
    { q: { en: 'What should I do during someone\'s seizure?', sw: 'Nifanye nini wakati wa mzozo wa mtu?' }, a: { en: 'Stay calm. Move sharp/hot objects away. Cushion the head with something soft. Loosen anything tight around the neck. Time the seizure. Roll the person onto their side once shaking stops. Do NOT put anything in the mouth — they cannot swallow their tongue. Do NOT hold them down. Do NOT pour water. Call an ambulance if: seizure lasts > 5 minutes, repeats without recovery, first-ever seizure, injury, pregnancy, or in water.', sw: 'Tulia. Sogeza vitu vyenye ncha/moto. Tia kichwa kitu laini. Legeza chochote kibanacho shingo. Pima muda wa mzozo. Mgeuze mtu upande mara baada ya kutetemeka kukoma. USIWEKE chochote mdomoni — hawawezi kumeza ulimi. USIMSHIKE chini. USIMWAGE maji. Piga simu ambulensi ikiwa: mzozo unadumu > dakika 5, unarudia bila kupona, mzozo wa kwanza kabisa, jeraha, mimba, au katika maji.', sw_mtaa: 'Stay calm. Sogeza sharp/hot objects mbali. Cushion head na kitu soft. Loosen chochote tight karibu na neck. Time the seizure. Roll mtu kwa side mara baada ya shaking kukoma. Do NOT put chochote katika mouth — hawawezi kumeza tongue. Do NOT shika down. Do NOT pour water. Call ambulance ikiwa: seizure inadumu > dakika 5, inarepeat bila recovery, first-ever seizure, injury, pregnancy, au katika water.' } },
    { q: { en: 'Can epilepsy be cured?', sw: 'Kifafa kinaweza kuponywa?' }, a: { en: 'For most people, epilepsy can be very well controlled — meaning no seizures while on medication — and many can come off medication after 2-3 seizure-free years. Some specific epilepsies in children resolve completely with growth. Adult-onset epilepsy from a structural cause (old stroke, head injury, brain infection) usually needs lifelong treatment. Cure is real for many, control is the norm, and even when not cured the goal is full active life.', sw: 'Kwa watu wengi, kifafa kinaweza kudhibitiwa vyema sana — maana hakuna mzozo wakati wa dawa — na wengi wanaweza kuacha dawa baada ya miaka 2-3 bila mzozo. Kifafa fulani maalum kwa watoto huisha kabisa na ukuaji. Kifafa cha utu uzima kutoka sababu ya kimuundo (kiharusi cha zamani, jeraha la kichwa, maambukizi ya ubongo) kawaida hunyitaji matibabu ya maisha. Kupona ni halisi kwa wengi, udhibiti ni kawaida, na hata pale isipopona lengo ni maisha kamili ya kufanya kazi.', sw_mtaa: 'Kwa most people, epilepsy inaweza kuvery well controlled — meaning no seizures wakati wa medication — na many wanaweza kuacha medication baada ya miaka 2-3 bila seizures. Some specific epilepsies kwa watoto zinaisha kabisa na growth. Adult-onset epilepsy kutoka structural cause (old stroke, head injury, brain infection) usually inahitaji lifelong treatment. Cure ni real kwa many, control ni norm, na even when not cured goal ni full active life.' } },
    { q: { en: 'Is epilepsy caused by witchcraft or curse?', sw: 'Kifafa kinasababishwa na uchawi au laana?' }, a: { en: 'No. Epilepsy is a medical condition with medical causes: scarring from an old brain infection (meningitis, cerebral malaria, neurocysticercosis), head injury, stroke, birth-related brain injury, or a genetic tendency. It is not contagious. It is not punishment. People with epilepsy can marry, work, raise children, and live normally with proper treatment. Stigma is one of the biggest barriers to care in Tanzania — talking about epilepsy openly helps.', sw: 'Hapana. Kifafa ni hali ya kimatibabu yenye sababu za kimatibabu: makovu kutoka maambukizi ya zamani ya ubongo (meningitis, malaria ya ubongo, neurocysticercosis), jeraha la kichwa, kiharusi, jeraha la ubongo linalohusiana na kuzaa, au mwelekeo wa kijenetiki. Hakiambukizi. Sio adhabu. Watu wenye kifafa wanaweza kuoa, kufanya kazi, kulea watoto, na kuishi kawaida kwa matibabu sahihi. Unyanyapaa ni mojawapo ya vizuizi vikubwa zaidi vya huduma Tanzania — kuongea juu ya kifafa kwa wazi husaidia.', sw_mtaa: 'Hapana. Epilepsy ni medical condition yenye medical causes: scarring kutoka old brain infection (meningitis, cerebral malaria, neurocysticercosis), head injury, stroke, birth-related brain injury, au genetic tendency. Haiambukizi. Sio punishment. Watu wenye epilepsy wanaweza kuoa, kufanya kazi, kulea watoto, na kuishi normally na proper treatment. Stigma ni mojawapo ya biggest barriers kwa care Tanzania — kuongea about epilepsy openly kunasaidia.' } },
    { q: { en: 'What medicines treat epilepsy?', sw: 'Dawa gani zinatibu kifafa?' }, a: { en: 'Tanzania commonly uses: phenobarbitone (cheapest, widely available, controlled drug), carbamazepine, sodium valproate, phenytoin. Newer drugs (levetiracetam, lamotrigine) where available. Choice depends on seizure type, age, pregnancy plans, side effects. CRITICAL: sodium valproate should be avoided in women of childbearing age unless there is no alternative — it causes severe birth defects. All anti-seizure medications must be taken DAILY without missing doses; abrupt stopping causes breakthrough seizures, sometimes status epilepticus.', sw: 'Tanzania kawaida hutumia: phenobarbitone (cha rahisi zaidi, kinapatikana sana, dawa iliyodhibitiwa), carbamazepine, sodium valproate, phenytoin. Dawa mpya zaidi (levetiracetam, lamotrigine) pale zinapopatikana. Chaguo hutegemea aina ya mzozo, umri, mipango ya mimba, athari. MUHIMU: sodium valproate inapaswa kuepukwa kwa wanawake wa umri wa kuzaa isipokuwa hakuna mbadala — husababisha kasoro kali za kuzaliwa. Dawa zote za kupambana na mzozo lazima zichukuliwe KILA SIKU pasipo kukosa dose; kuacha ghafla husababisha mzozo wa breakthrough, wakati mwingine status epilepticus.', sw_mtaa: 'Tanzania commonly inatumia: phenobarbitone (cheapest, widely available, controlled drug), carbamazepine, sodium valproate, phenytoin. Newer drugs (levetiracetam, lamotrigine) pale zinapopatikana. Choice inategemea seizure type, age, pregnancy plans, side effects. CRITICAL: sodium valproate inapaswa kuepukwa kwa women wa childbearing age isipokuwa hakuna alternative — inasababisha severe birth defects. Anti-seizure medications zote lazima zichukuliwe DAILY bila kukosa doses; abrupt stopping inasababisha breakthrough seizures, wakati mwingine status epilepticus.' } },
  ],
  selfManagement: [
    { en: 'Take medication every day at the same times, even when you feel well.', sw: 'Chukua dawa kila siku kwa nyakati sawa, hata unapojihisi vizuri.', sw_mtaa: 'Chukua medication kila siku kwa same times, hata unapojihisi vizuri.' },
    { en: 'Sleep regularly — sleep deprivation is one of the commonest seizure triggers.', sw: 'Lala kwa kawaida — kukosa usingizi ni mojawapo ya vichocheo vya kawaida zaidi vya mzozo.', sw_mtaa: 'Sleep regularly — sleep deprivation ni mojawapo ya commonest seizure triggers.' },
    { en: 'Avoid alcohol — it lowers seizure threshold and interacts with most anti-seizure medications.', sw: 'Epuka pombe — inapunguza kizingiti cha mzozo na inaingiliana na dawa nyingi za kupambana na mzozo.', sw_mtaa: 'Epuka pombe — inalower seizure threshold na inaingiliana na most anti-seizure medications.' },
    { en: 'Avoid cooking over open fires alone if seizures are not well controlled — burns from cooking fire seizures are the commonest serious injury in Tanzania.', sw: 'Epuka kupika juu ya moto wazi peke yako ikiwa mizozo haidhibitiwi vyema — kuungua kutoka mzozo wa moto wa kupika ni jeraha la kawaida zaidi la makali Tanzania.', sw_mtaa: 'Epuka kupika juu ya open fires peke yako ikiwa seizures hazidhibitiwi vizuri — burns kutoka cooking fire seizures ni commonest serious injury Tanzania.' },
    { en: 'Tell schools, employers, and family about your epilepsy so they can help safely — secrecy is more dangerous than disclosure.', sw: 'Waambie shule, waajiri, na familia kuhusu kifafa chako ili waweze kusaidia kwa usalama — usiri ni hatari zaidi kuliko kuwafichulia.', sw_mtaa: 'Waambie schools, employers, na family about epilepsy yako so they can help safely — secrecy ni more dangerous kuliko disclosure.' },
    { en: 'Carry a card or wear a tag noting "I have epilepsy" so helpers know during a seizure.', sw: 'Beba kadi au vaa tag ikisema "Nina kifafa" ili wasaidizi wajue wakati wa mzozo.', sw_mtaa: 'Beba kadi au vaa tag ikisema "Nina epilepsy" ili helpers wajue wakati wa seizure.' },
  ],
  warningTriggers: [
    { en: 'Missing medication doses', sw: 'Kukosa dose za dawa', sw_mtaa: 'Missing medication doses' },
    { en: 'Sleep deprivation, late nights', sw: 'Kukosa usingizi, usiku wa kuchelewa', sw_mtaa: 'Sleep deprivation, late nights' },
    { en: 'Alcohol or recreational drugs', sw: 'Pombe au dawa za kulevya', sw_mtaa: 'Alcohol au recreational drugs' },
    { en: 'Severe stress, hunger, dehydration', sw: 'Mfadhaiko mkali, njaa, kukosa maji', sw_mtaa: 'Severe stress, hunger, dehydration' },
    { en: 'Infection, fever (especially in children)', sw: 'Maambukizi, homa (hasa kwa watoto)', sw_mtaa: 'Infection, fever (especially kwa watoto)' },
    { en: 'Flashing lights (only in a minority of patients with photosensitive epilepsy)', sw: 'Mwanga unaomulika (kwa wachache wa wagonjwa wenye kifafa cha photosensitive)', sw_mtaa: 'Flashing lights (kwa minority ya patients wenye photosensitive epilepsy)' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Seizure lasting > 5 minutes or repeating without recovery — STATUS EPILEPTICUS, emergency', sw: 'Mzozo unaodumu > dakika 5 au unaorudia bila kupona — STATUS EPILEPTICUS, dharura', sw_mtaa: 'Seizure lasting > dakika 5 au repeating bila recovery — STATUS EPILEPTICUS, emergency' }, urgency: 'emergency' },
    { sign: { en: 'First-ever seizure in any age — needs assessment to find cause', sw: 'Mzozo wa kwanza kabisa kwa umri wowote — unahitaji tathmini kupata sababu', sw_mtaa: 'First-ever seizure katika age yoyote — inahitaji assessment kupata cause' }, urgency: 'urgent' },
    { sign: { en: 'Seizure with injury, in water, in pregnancy, or with diabetes', sw: 'Mzozo na jeraha, katika maji, katika mimba, au na kisukari', sw_mtaa: 'Seizure na injury, katika water, katika pregnancy, au na diabetes' }, urgency: 'urgent' },
    { sign: { en: 'New or different seizure pattern in someone with known epilepsy', sw: 'Muundo mpya au tofauti wa mzozo kwa mtu mwenye kifafa kinachojulikana', sw_mtaa: 'New au different seizure pattern kwa mtu mwenye known epilepsy' }, urgency: 'urgent' },
    { sign: { en: 'Cannot afford or has run out of medication — visit clinic for refill BEFORE running out', sw: 'Hawezi kumudu au amemaliza dawa — tembelea kliniki kwa kurudisha KABLA ya kumaliza', sw_mtaa: 'Cannot afford au amemaliza medication — tembelea clinic kwa refill KABLA ya kumaliza' }, urgency: 'urgent' },
  ],
  comorbidityNotes: [
    { coCondition: 'maternal_care', note: { en: 'Women with epilepsy planning pregnancy need pre-conception counselling: review and possibly switch medication (avoid sodium valproate), start high-dose folic acid (5 mg) before conception, joint care between neurology/clinical officer and obstetrics. Seizure control matters more for both mother and baby than minor risks of medication. Most women with epilepsy have healthy babies.', sw: 'Wanawake wenye kifafa wanaopanga mimba wanahitaji ushauri wa kabla ya kuchanganyika: pitia na pengine ubadilishe dawa (epuka sodium valproate), anza folic acid ya dose ya juu (5 mg) kabla ya kuchanganyika, huduma ya pamoja kati ya neurology/clinical officer na uzazi. Udhibiti wa mzozo ni muhimu zaidi kwa mama na mtoto kuliko hatari ndogo za dawa. Wanawake wengi wenye kifafa wana watoto wenye afya.', sw_mtaa: 'Women wenye epilepsy planning pregnancy wanahitaji pre-conception counselling: review na possibly switch medication (epuka sodium valproate), anza high-dose folic acid (5 mg) kabla ya conception, joint care between neurology/clinical officer na obstetrics. Seizure control ni more important kwa both mother na baby kuliko minor risks za medication. Most women wenye epilepsy wana healthy babies.' } },
    { coCondition: 'malaria', note: { en: 'Cerebral malaria is a major cause of post-infectious epilepsy in Tanzania. Children who survive cerebral malaria need follow-up for seizures over the following years. Conversely, any new seizure in a malaria-endemic area with fever needs malaria testing.', sw: 'Malaria ya ubongo ni sababu kuu ya kifafa cha baada ya maambukizi Tanzania. Watoto wanaopona malaria ya ubongo wanahitaji ufuatiliaji wa mizozo katika miaka inayofuata. Kinyume chake, mzozo wowote mpya katika eneo malaria-endemic na homa unahitaji upimaji wa malaria.', sw_mtaa: 'Cerebral malaria ni major cause ya post-infectious epilepsy Tanzania. Watoto wanaosurvive cerebral malaria wanahitaji follow-up kwa seizures over following years. Conversely, new seizure yoyote katika malaria-endemic area na fever inahitaji malaria testing.' } },
  ],
  sources: [src('WHO_EPILEPSY_2022'), src('WHO_MHGAP_2023'), src('NTLG_STG_2023'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
