/**
 * Hepatitis B — Phase 15. Sources: WHO HepB 2024, NTLG STG 2023, NACP.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const HEPATITIS_B: ConditionKnowledge = {
  id: 'hepatitis_b',
  aliases: CONDITION_ALIASES.hepatitis_b,
  category: 'infectious',
  whatItIs: {
    en: 'Hepatitis B is a viral infection of the liver caused by HBV, spread mainly through blood (sharing needles, unsafe injections, blood transfusion), sex, and from mother to baby at birth. Most adult infections clear themselves within 6 months; in some, the virus stays for life — chronic hepatitis B — and slowly damages the liver, eventually causing cirrhosis or liver cancer. Babies who get HBV at birth have a very high chance (>90%) of chronic infection — which is why the birth-dose HBV vaccine plus three later doses is so important. Tanzania has moderate-to-high HBV prevalence and routine infant vaccination is in place.',
    sw: 'Hepatitis B ni maambukizi ya virusi ya ini yanayosababishwa na HBV, yanayoenea hasa kupitia damu (kushiriki sindano, sindano zisizo salama, kuongezewa damu), ngono, na kutoka mama kwa mtoto wakati wa kuzaliwa. Maambukizi mengi ya watu wazima hujiponya ndani ya miezi 6; kwa wengine, virusi hubaki maisha — hepatitis B sugu — na huharibu ini polepole, hatimaye husababisha cirrhosis au saratani ya ini. Watoto wachanga wanaopata HBV wakati wa kuzaliwa wana nafasi kubwa sana (>90%) ya maambukizi sugu — ndio sababu chanjo ya kuzaliwa ya HBV pamoja na dose tatu za baadaye ni muhimu sana. Tanzania ina prevalence ya HBV ya wastani-hadi-juu na chanjo ya kawaida ya watoto wachanga ipo.',
    sw_mtaa: 'Hepatitis B ni viral infection ya liver inayosababishwa na HBV, inayoenea mainly kupitia blood (sharing needles, unsafe injections, blood transfusion), sex, na kutoka mother kwa baby at birth. Most adult infections zinajiponya ndani ya miezi 6; kwa some, virus inabaki for life — chronic hepatitis B — na inaharibu liver polepole, eventually inasababisha cirrhosis au liver cancer. Babies wanaopata HBV at birth wana very high chance (>90%) ya chronic infection — ndiyo sababu birth-dose HBV vaccine plus three later doses ni muhimu sana. Tanzania ina moderate-to-high HBV prevalence na routine infant vaccination iko in place.',
  },
  whyItMatters: {
    en: 'Hepatitis B is the leading cause of liver cancer in Tanzania and across sub-Saharan Africa. Two interventions change the picture dramatically: routine birth-dose HBV vaccine + 3-dose infant series (already in Tanzania\'s programme), and screening of all pregnant women so that their babies receive timely vaccine plus immunoglobulin if available. For someone with chronic HBV, lifelong follow-up is important; tenofovir-based treatment is given when criteria are met (high viral load, raised liver enzymes, evidence of fibrosis) — and conveniently the same tenofovir is part of TLD ART, so HBV-HIV co-infection is treated as one regimen. Hepatitis B in pregnancy with high viral load needs antiviral treatment in the third trimester to reduce mother-to-child transmission.',
    sw: 'Hepatitis B ni sababu kuu ya saratani ya ini Tanzania na Afrika kusini mwa jangwa la Sahara. Hatua mbili zinabadilisha picha kwa kiasi kikubwa: chanjo ya kawaida ya kuzaliwa ya HBV + mfululizo wa dose 3 wa watoto wachanga (tayari katika programu ya Tanzania), na uchunguzi wa wanawake wote wajawazito ili watoto wao wapate chanjo kwa wakati pamoja na immunoglobulin pale inapopatikana. Kwa mtu mwenye HBV sugu, ufuatiliaji wa maisha ni muhimu; matibabu ya msingi wa tenofovir hutolewa wakati vigezo vinapokutana (mzigo wa juu wa virusi, vimeng\'enya vya ini vilivyoinuka, ushahidi wa fibrosis) — na kwa urahisi tenofovir ile ile ni sehemu ya TLD ART, kwa hivyo HBV-HIV co-infection hutibiwa kama regimen moja. Hepatitis B katika mimba na mzigo wa juu wa virusi inahitaji matibabu ya antiviral katika trimester ya tatu kupunguza maambukizi ya mama-kwa-mtoto.',
    sw_mtaa: 'Hepatitis B ni leading cause ya liver cancer Tanzania na across sub-Saharan Africa. Two interventions zinabadilisha picture dramatically: routine birth-dose HBV vaccine + 3-dose infant series (tayari katika Tanzania\'s programme), na screening ya wanawake wote pregnant ili babies wao wapate timely vaccine plus immunoglobulin pale inapopatikana. Kwa mtu mwenye chronic HBV, lifelong follow-up ni muhimu; tenofovir-based treatment inatolewa wakati criteria zinameet (high viral load, raised liver enzymes, evidence ya fibrosis) — na conveniently tenofovir ile ile ni sehemu ya TLD ART, kwa hivyo HBV-HIV co-infection inatreated kama one regimen. Hepatitis B katika pregnancy na high viral load inahitaji antiviral treatment katika third trimester kupunguza mother-to-child transmission.',
  },
  commonQuestions: [
    { q: { en: 'How is hepatitis B spread?', sw: 'Hepatitis B inaenea vipi?' }, a: { en: 'Through blood (unsafe injections, blood transfusion, shared needles, traditional cuts/scarification with shared blades), sex, and from mother to baby at birth. Saliva and casual contact (sharing food, hugging) generally do not spread it. Razors and toothbrushes can if blood is present.', sw: 'Kupitia damu (sindano zisizo salama, kuongezewa damu, sindano zilizoshirikiwa, mikato/scarification ya kijadi na visu vilivyoshirikiwa), ngono, na kutoka mama kwa mtoto wakati wa kuzaliwa. Mate na mawasiliano ya kawaida (kushiriki chakula, kumkumbatia) kwa ujumla hayasambazi. Wembe na miswaki inaweza ikiwa damu ipo.', sw_mtaa: 'Kupitia blood (unsafe injections, blood transfusion, shared needles, traditional cuts/scarification na shared blades), sex, na kutoka mother kwa baby at birth. Saliva na casual contact (kushiriki food, kumhug) generally hazisambazi. Razors na toothbrushes zinaweza ikiwa blood ipo.' } },
    { q: { en: 'How is hepatitis B treated?', sw: 'Hepatitis B inatibiwaje?' }, a: { en: 'Acute hepatitis B in adults usually resolves on its own — supportive care, rest, avoid alcohol and hepatotoxic drugs. Chronic HBV: regular monitoring of viral load, liver enzymes, and liver fibrosis. Antiviral treatment with tenofovir is started when criteria are met. People with HIV-HBV co-infection get TLD (which includes tenofovir + lamivudine, both active against HBV). Liver cancer surveillance with ultrasound + alpha-fetoprotein every 6 months in those with cirrhosis or other risk.', sw: 'Hepatitis B ya papo hapo kwa watu wazima kawaida hujiponya — huduma ya kuunga mkono, mapumziko, epuka pombe na dawa zenye sumu kwa ini. HBV sugu: ufuatiliaji wa kawaida wa mzigo wa virusi, vimeng\'enya vya ini, na fibrosis ya ini. Matibabu ya antiviral na tenofovir huanzwa wakati vigezo vinapokutana. Watu wenye HIV-HBV co-infection wanapata TLD (ambayo inajumuisha tenofovir + lamivudine, zote zinapambana na HBV). Uangalizi wa saratani ya ini na ultrasound + alpha-fetoprotein kila miezi 6 kwa wenye cirrhosis au hatari nyingine.', sw_mtaa: 'Acute hepatitis B kwa adults usually inajiponya — supportive care, rest, epuka alcohol na hepatotoxic drugs. Chronic HBV: regular monitoring ya viral load, liver enzymes, na liver fibrosis. Antiviral treatment na tenofovir inastarted wakati criteria zimameet. People wenye HIV-HBV co-infection wanapata TLD (ambayo inajumuisha tenofovir + lamivudine, both active against HBV). Liver cancer surveillance na ultrasound + alpha-fetoprotein kila miezi 6 kwa wenye cirrhosis au other risk.' } },
    { q: { en: 'Can hepatitis B be prevented?', sw: 'Hepatitis B inaweza kuzuiwa?' }, a: { en: 'Yes, very effectively. The HBV vaccine is one of the most effective vaccines in medicine — given at birth (within 24 hours) and at 6, 10, 14 weeks in Tanzania\'s routine schedule. Adults at risk (healthcare workers, partners of HBV+ patients, dialysis patients, MSM) should also be vaccinated. Use only sterile injection equipment, avoid sharing razors/toothbrushes, use condoms with HBV+ partners until they have undetectable viral load on treatment, screen all pregnant women.', sw: 'Ndio, kwa ufanisi mkubwa sana. Chanjo ya HBV ni mojawapo ya chanjo zenye ufanisi zaidi katika tiba — inatolewa wakati wa kuzaliwa (ndani ya masaa 24) na kwa wiki 6, 10, 14 katika ratiba ya kawaida ya Tanzania. Watu wazima walio katika hatari (wafanyakazi wa afya, wenza wa wagonjwa wa HBV+, wagonjwa wa dialysis, MSM) pia wanapaswa kupewa chanjo. Tumia vifaa vya sindano vyenye sterile tu, epuka kushiriki wembe/miswaki, tumia kondomu na wenza wa HBV+ hadi wawe na mzigo wa virusi usiowezekana kugunduliwa kwa matibabu, chunguza wanawake wote wajawazito.', sw_mtaa: 'Ndio, very effectively. HBV vaccine ni mojawapo ya most effective vaccines katika medicine — inatolewa at birth (ndani ya masaa 24) na at wiki 6, 10, 14 katika Tanzania\'s routine schedule. Adults at risk (healthcare workers, partners wa HBV+ patients, dialysis patients, MSM) pia wapaswa kupewa chanjo. Use only sterile injection equipment, epuka kushiriki razors/toothbrushes, tumia condoms na HBV+ partners hadi wawe na undetectable viral load on treatment, screen wanawake wote pregnant.' } },
    { q: { en: 'If I have hepatitis B and I am pregnant, what should I do?', sw: 'Nikiwa na hepatitis B na nina mimba, nifanye nini?' }, a: { en: 'Tell your ANC clinician early. You will be monitored with HBV viral load and liver tests. If viral load is high in the third trimester, tenofovir treatment from week 28 reduces mother-to-baby transmission. At birth, the baby receives the HBV vaccine within 24 hours AND, where available, hepatitis B immunoglobulin. The baby continues the full 3-dose vaccine schedule. With these steps, transmission to baby is reduced from >90% (no intervention) to <5%.', sw: 'Mwambie clinician wako wa ANC mapema. Utachunguzwa na mzigo wa virusi vya HBV na vipimo vya ini. Ikiwa mzigo wa virusi ni juu katika trimester ya tatu, matibabu ya tenofovir kutoka wiki ya 28 hupunguza maambukizi ya mama-kwa-mtoto. Wakati wa kuzaliwa, mtoto hupata chanjo ya HBV ndani ya masaa 24 NA, pale inapopatikana, hepatitis B immunoglobulin. Mtoto huendelea na ratiba kamili ya chanjo ya dose 3. Kwa hatua hizi, maambukizi kwa mtoto hupunguzwa kutoka >90% (pasipo kuingilia kati) hadi <5%.', sw_mtaa: 'Mwambie ANC clinician wako early. Utachunguzwa na HBV viral load na liver tests. Ikiwa viral load ni high katika third trimester, tenofovir treatment kutoka week 28 inareduce mother-to-baby transmission. At birth, baby anapata HBV vaccine ndani ya masaa 24 AND, pale inapopatikana, hepatitis B immunoglobulin. Baby anaendelea full 3-dose vaccine schedule. Na hatua hizi, transmission kwa baby inareduced kutoka >90% (no intervention) hadi <5%.' } },
  ],
  selfManagement: [
    { en: 'Get the full HBV vaccine series if not already vaccinated (3 doses).', sw: 'Pata mfululizo kamili wa chanjo ya HBV ikiwa hujapewa chanjo (dose 3).', sw_mtaa: 'Pata full HBV vaccine series ikiwa hujavaccinated (dose 3).' },
    { en: 'If chronic HBV: avoid alcohol entirely, avoid hepatotoxic drugs (some traditional remedies, paracetamol overdose), maintain healthy weight.', sw: 'Ikiwa na HBV sugu: epuka pombe kabisa, epuka dawa zenye sumu kwa ini (baadhi ya dawa za kijadi, overdose ya paracetamol), dumisha uzito wenye afya.', sw_mtaa: 'Ikiwa chronic HBV: epuka pombe entirely, epuka hepatotoxic drugs (some traditional remedies, paracetamol overdose), maintain healthy weight.' },
    { en: 'Attend all follow-up visits — viral load, liver enzymes, ultrasound to monitor liver damage and cancer risk.', sw: 'Hudhuria ziara zote za ufuatiliaji — mzigo wa virusi, vimeng\'enya vya ini, ultrasound kufuatilia uharibifu wa ini na hatari ya saratani.', sw_mtaa: 'Hudhuria all follow-up visits — viral load, liver enzymes, ultrasound kumonitor liver damage na cancer risk.' },
    { en: 'Tell partners and household members so they can be screened and vaccinated.', sw: 'Waambie wenza na wanafamilia ili waweze kupimwa na kupewa chanjo.', sw_mtaa: 'Waambie partners na household members so they can be screened na vaccinated.' },
    { en: 'Use condoms with new partners until they are vaccinated.', sw: 'Tumia kondomu na wenza wapya hadi watakapopewa chanjo.', sw_mtaa: 'Tumia condoms na new partners hadi watakapovaccinated.' },
  ],
  warningTriggers: [
    { en: 'Unprotected sex with new partners', sw: 'Ngono pasipo kinga na wenza wapya', sw_mtaa: 'Unprotected sex na new partners' },
    { en: 'Unsafe injections, sharing needles', sw: 'Sindano zisizo salama, kushiriki sindano', sw_mtaa: 'Unsafe injections, sharing needles' },
    { en: 'Traditional cuts, scarification, tattoos with shared/unsterile equipment', sw: 'Mikato ya kijadi, scarification, tattoos na vifaa vilivyoshirikiwa/visivyosafishwa', sw_mtaa: 'Traditional cuts, scarification, tattoos na shared/unsterile equipment' },
    { en: 'Healthcare workers, dialysis patients, household contacts of HBV+ person', sw: 'Wafanyakazi wa afya, wagonjwa wa dialysis, wanafamilia wa mtu mwenye HBV+', sw_mtaa: 'Healthcare workers, dialysis patients, household contacts wa HBV+ person' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Yellow eyes/skin, dark urine, pale stool, severe abdominal pain — acute hepatitis, urgent assessment', sw: 'Macho/ngozi ya manjano, mkojo mweusi, kinyesi kilichofifia, maumivu makali ya tumbo — hepatitis ya papo hapo, tathmini ya haraka', sw_mtaa: 'Yellow eyes/skin, dark urine, pale stool, severe abdominal pain — acute hepatitis, urgent assessment' }, urgency: 'urgent' },
    { sign: { en: 'Confusion, drowsiness, bleeding tendency in someone with liver disease — possible liver failure, emergency', sw: 'Mkanganyiko, usingizi, mwelekeo wa kutokwa damu kwa mtu mwenye ugonjwa wa ini — uwezekano wa kushindwa kwa ini, dharura', sw_mtaa: 'Confusion, drowsiness, bleeding tendency kwa mtu mwenye liver disease — possible liver failure, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Pregnant woman with HBV+ — early ANC review for transmission prevention', sw: 'Mwanamke mjamzito mwenye HBV+ — mapitio ya mapema ya ANC kwa kuzuia maambukizi', sw_mtaa: 'Pregnant woman mwenye HBV+ — early ANC review kwa transmission prevention' }, urgency: 'urgent' },
    { sign: { en: 'Anyone exposed to HBV+ blood (needlestick, sexual assault, transfusion) — needs urgent post-exposure prophylaxis assessment', sw: 'Mtu yeyote aliyefichuliwa kwa damu ya HBV+ (sindano, ubakaji, kuongezewa damu) — anahitaji tathmini ya haraka ya prophylaxis ya baada ya mfiduo', sw_mtaa: 'Anyone exposed kwa HBV+ blood (needlestick, sexual assault, transfusion) — anahitaji urgent post-exposure prophylaxis assessment' }, urgency: 'urgent' },
  ],
  comorbidityNotes: [
    { coCondition: 'hiv', note: { en: 'HIV-HBV co-infection is common. TLD ART (tenofovir + lamivudine + dolutegravir) treats both — tenofovir + lamivudine are active against HBV. Do not stop ART abruptly in HBV-positive person — HBV flare can occur.', sw: 'HIV-HBV co-infection ni ya kawaida. TLD ART (tenofovir + lamivudine + dolutegravir) hutibu vyote — tenofovir + lamivudine zinapambana na HBV. Usiache ART ghafla kwa mtu mwenye HBV-chanya — HBV flare inaweza kutokea.', sw_mtaa: 'HIV-HBV co-infection ni common. TLD ART (tenofovir + lamivudine + dolutegravir) inatibu both — tenofovir + lamivudine ni active against HBV. Usache ART abruptly kwa HBV-positive person — HBV flare inaweza kuoccur.' } },
    { coCondition: 'maternal_care', note: { en: 'All pregnant women should be screened for HBV. HBV+ mothers need antiviral in third trimester if viral load is high; babies need birth-dose HBV vaccine + immunoglobulin where available.', sw: 'Wanawake wote wajawazito wanapaswa kuchunguzwa kwa HBV. Akina mama wa HBV+ wanahitaji antiviral katika trimester ya tatu ikiwa mzigo wa virusi ni juu; watoto wanahitaji chanjo ya kuzaliwa ya HBV + immunoglobulin pale inapopatikana.', sw_mtaa: 'Wanawake wote pregnant wapaswa kuscreened kwa HBV. HBV+ mothers wanahitaji antiviral katika third trimester ikiwa viral load ni high; babies wanahitaji birth-dose HBV vaccine + immunoglobulin pale inapopatikana.' } },
  ],
  sources: [src('WHO_HEPB_2024'), src('NACP_ART_2024'), src('NTLG_STG_2023'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
