/**
 * Peptic Ulcer Disease — Phase 15. Sources: NTLG STG 2023, WHO, BNF, Maastricht VI.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const PEPTIC_ULCER: ConditionKnowledge = {
  id: 'peptic_ulcer',
  aliases: CONDITION_ALIASES.peptic_ulcer,
  category: 'gastrointestinal',
  whatItIs: {
    en: 'A peptic ulcer is a sore in the lining of the stomach (gastric ulcer) or the first part of the small intestine (duodenal ulcer). The two major causes worldwide are infection with Helicobacter pylori (a stomach bacterium) and regular use of NSAIDs (ibuprofen, diclofenac, aspirin). Symptoms are burning upper abdominal pain — worse with hunger or at night for duodenal ulcers, worse with eating for gastric ulcers — nausea, bloating, and sometimes vomiting. Bleeding ulcers cause black stool, vomiting blood, or anaemia.',
    sw: 'Kidonda cha tumbo (peptic ulcer) ni jeraha katika utando wa tumbo (gastric ulcer) au sehemu ya kwanza ya utumbo mwembamba (duodenal ulcer). Sababu kuu mbili duniani ni maambukizi ya Helicobacter pylori (bakteria ya tumbo) na matumizi ya kawaida ya NSAID (ibuprofen, diclofenac, aspirini). Dalili ni maumivu ya juu ya tumbo ya kuwaka — mabaya zaidi na njaa au usiku kwa duodenal ulcer, mabaya zaidi na kula kwa gastric ulcer — kichefuchefu, kupinda, na wakati mwingine kutapika. Kidonda kinachotoka damu husababisha kinyesi cheusi, kutapika damu, au upungufu wa damu.',
    sw_mtaa: 'Peptic ulcer ni sore katika lining ya stomach (gastric ulcer) au first part ya small intestine (duodenal ulcer). Two major causes worldwide ni infection na Helicobacter pylori (stomach bacterium) na regular use ya NSAIDs (ibuprofen, diclofenac, aspirin). Symptoms ni burning upper abdominal pain — worse na hunger au at night kwa duodenal ulcers, worse na eating kwa gastric ulcers — nausea, bloating, na wakati mwingine vomiting. Bleeding ulcers zinasababisha black stool, vomiting blood, au anaemia.',
  },
  whyItMatters: {
    en: 'Most ulcers heal with the right treatment, but bleeding ulcer or perforation can be life-threatening. H. pylori is the major preventable cause — finding and treating it (with triple or quadruple therapy) cures most ulcers and prevents recurrence. NSAID-induced ulcers are common in older people with arthritis or with diabetes/heart disease who take low-dose aspirin; co-prescribing a PPI is protective. New-onset upper abdominal pain in someone over 55, or with weight loss, vomiting, bleeding, or anaemia, must be investigated to rule out stomach cancer.',
    sw: 'Vidonda vingi hupona kwa matibabu sahihi, lakini kidonda kinachotoka damu au kutoboa kinaweza kutishia maisha. H. pylori ni sababu kuu inayozuilika — kuipata na kuitibu (kwa triple au quadruple therapy) huponya vidonda vingi na huzuia kurudia. Vidonda vinavyosababishwa na NSAID ni vya kawaida kwa watu wakubwa wenye yabisi au na kisukari/ugonjwa wa moyo wanaochukua aspirini ya dose ndogo; kuagiza PPI pamoja kunalindi. Maumivu mapya ya juu ya tumbo kwa mtu zaidi ya miaka 55, au na kupoteza uzito, kutapika, kutokwa damu, au upungufu wa damu, lazima yachunguzwe kuondoa saratani ya tumbo.',
    sw_mtaa: 'Most ulcers zinaponya na right treatment, lakini bleeding ulcer au perforation inaweza kuwa life-threatening. H. pylori ni major preventable cause — kuipata na kuitreat (na triple au quadruple therapy) inacure most ulcers na inazuia recurrence. NSAID-induced ulcers ni common kwa older people wenye arthritis au na diabetes/heart disease wanaochukua low-dose aspirin; co-prescribing PPI ni protective. New-onset upper abdominal pain kwa mtu over 55, au na weight loss, vomiting, bleeding, au anaemia, lazima iinvestigated kurule out stomach cancer.',
  },
  commonQuestions: [
    { q: { en: 'What is H. pylori?', sw: 'H. pylori ni nini?' }, a: { en: 'Helicobacter pylori is a bacterium that lives in the stomach lining and causes most peptic ulcers and chronic gastritis. It is acquired in childhood, usually from contaminated food/water, and persists for life unless treated. Testing is by stool antigen, breath test, or biopsy at endoscopy. Treatment is a 14-day combination (PPI + amoxicillin + clarithromycin, or with metronidazole as second-line). Re-testing 4-8 weeks after treatment confirms cure.', sw: 'Helicobacter pylori ni bakteria inayoishi katika utando wa tumbo na husababisha vidonda vingi vya peptic na gastritis sugu. Hupatikana utotoni, kwa kawaida kutoka chakula/maji yaliyochafuliwa, na hudumu maisha bila matibabu. Upimaji ni kwa antijeni ya kinyesi, jaribio la pumzi, au biopsy katika endoscopy. Matibabu ni mchanganyiko wa siku 14 (PPI + amoxicillin + clarithromycin, au na metronidazole kama ya pili). Upimaji tena wiki 4-8 baada ya matibabu unathibitisha tiba.', sw_mtaa: 'H. pylori ni bacterium inayoishi katika stomach lining na inasababisha most peptic ulcers na chronic gastritis. Inapatikana utotoni, usually kutoka contaminated food/water, na inapersist for life bila treatment. Testing ni kwa stool antigen, breath test, au biopsy at endoscopy. Treatment ni 14-day combination (PPI + amoxicillin + clarithromycin, au na metronidazole kama second-line). Re-testing wiki 4-8 baada ya treatment inaconfirm cure.' } },
    { q: { en: 'How are ulcers treated?', sw: 'Vidonda vinatibiwaje?' }, a: { en: 'If H. pylori positive: 14-day eradication therapy (PPI + 2 antibiotics) followed by PPI alone to heal the ulcer. If NSAID-induced: stop the NSAID if possible, give PPI 4-8 weeks. Lifestyle: avoid alcohol, stop smoking, eat small frequent meals, avoid irritants (very spicy/acidic food only if they trigger symptoms — they do not cause ulcers). Surgery is rare and reserved for complications.', sw: 'Ikiwa H. pylori chanya: tiba ya kutokomeza ya siku 14 (PPI + antibiotic 2) ikifuatiwa na PPI pekee kuponya kidonda. Ikiwa imesababishwa na NSAID: acha NSAID ikiwezekana, toa PPI wiki 4-8. Mtindo wa maisha: epuka pombe, acha sigara, kula milo midogo ya mara kwa mara, epuka inakera (chakula chenye viungo sana/cha asidi tu kama vinasababisha dalili — havisababishi vidonda). Upasuaji ni nadra na umehifadhiwa kwa matatizo.', sw_mtaa: 'Ikiwa H. pylori positive: 14-day eradication therapy (PPI + 2 antibiotics) ifuatiwe na PPI alone kuponya ulcer. Ikiwa NSAID-induced: acha NSAID ikiwezekana, give PPI wiki 4-8. Lifestyle: epuka pombe, acha sigara, kula small frequent meals, epuka irritants (very spicy/acidic food tu kama zinatrigger symptoms — hazisababishi ulcers). Surgery ni rare na inareserved kwa complications.' } },
    { q: { en: 'Does stress cause ulcers?', sw: 'Mfadhaiko husababisha vidonda?' }, a: { en: 'Stress alone does not cause peptic ulcers — H. pylori and NSAIDs do. Stress can worsen symptoms in someone who has an ulcer or functional dyspepsia, but treating only the stress without treating H. pylori or stopping NSAIDs will not heal the ulcer.', sw: 'Mfadhaiko peke yake hausababishi vidonda vya peptic — H. pylori na NSAID hufanya hivyo. Mfadhaiko unaweza kuzidisha dalili kwa mtu mwenye kidonda au functional dyspepsia, lakini kutibu tu mfadhaiko bila kutibu H. pylori au kuacha NSAID hakutaponya kidonda.', sw_mtaa: 'Stress alone haisababishi peptic ulcers — H. pylori na NSAIDs zinasababisha. Stress inaweza kuworsen symptoms kwa mtu mwenye ulcer au functional dyspepsia, lakini kutreating tu stress bila kutreating H. pylori au kustop NSAIDs haitaponya ulcer.' } },
    { q: { en: 'Are NSAIDs dangerous for the stomach?', sw: 'NSAID ni hatari kwa tumbo?' }, a: { en: 'Yes, with regular or long-term use. Ibuprofen, diclofenac, naproxen, and aspirin all damage the stomach lining and can cause ulcers. Risk is highest in older adults, in those with previous ulcer, and with other risk factors. Paracetamol is gentler on the stomach for mild pain. If long-term NSAID is needed (arthritis, cardiovascular protection), a co-prescribed PPI (omeprazole) reduces risk.', sw: 'Ndio, na matumizi ya kawaida au ya muda mrefu. Ibuprofen, diclofenac, naproxen, na aspirini zote zinaharibu utando wa tumbo na zinaweza kusababisha vidonda. Hatari ni juu zaidi kwa watu wazima, kwa wale wenye kidonda cha awali, na na sababu nyingine za hatari. Paracetamol ni mpole zaidi kwa tumbo kwa maumivu madogo. Ikiwa NSAID ya muda mrefu inahitajika (yabisi, ulinzi wa moyo), PPI iliyoamriwa pamoja (omeprazole) hupunguza hatari.', sw_mtaa: 'Ndio, na regular au long-term use. Ibuprofen, diclofenac, naproxen, na aspirin zote zinaharibu stomach lining na zinaweza kusababisha ulcers. Risk ni highest kwa older adults, kwa wenye previous ulcer, na na other risk factors. Paracetamol ni gentler kwa stomach kwa mild pain. Ikiwa long-term NSAID inahitajika (arthritis, cardiovascular protection), co-prescribed PPI (omeprazole) inareduce risk.' } },
  ],
  selfManagement: [
    { en: 'Take PPI (omeprazole) 30 minutes before breakfast for maximum effect.', sw: 'Chukua PPI (omeprazole) dakika 30 kabla ya kifungua kinywa kwa athari kubwa.', sw_mtaa: 'Chukua PPI (omeprazole) dakika 30 kabla ya breakfast kwa maximum effect.' },
    { en: 'Stop NSAIDs entirely while the ulcer is healing; use paracetamol for pain.', sw: 'Acha NSAID kabisa wakati kidonda kinapona; tumia paracetamol kwa maumivu.', sw_mtaa: 'Stop NSAIDs entirely wakati ulcer inaheal; tumia paracetamol kwa pain.' },
    { en: 'Stop smoking — smoking slows ulcer healing and increases recurrence.', sw: 'Acha sigara — sigara hupunguza kupona kwa kidonda na huongeza kurudia.', sw_mtaa: 'Acha sigara — smoking inaslow ulcer healing na inaongeza recurrence.' },
    { en: 'Limit or avoid alcohol — it irritates the stomach and slows healing.', sw: 'Punguza au epuka pombe — inakera tumbo na hupunguza kupona.', sw_mtaa: 'Limit au epuka pombe — inakera stomach na inaslow healing.' },
    { en: 'Eat small frequent meals rather than 2-3 large ones; avoid eating just before sleep.', sw: 'Kula milo midogo ya mara kwa mara badala ya milo 2-3 mikubwa; epuka kula kabla ya kulala.', sw_mtaa: 'Kula small frequent meals badala ya 2-3 large meals; epuka kula just kabla ya sleep.' },
  ],
  warningTriggers: [
    { en: 'H. pylori infection — single biggest cause', sw: 'Maambukizi ya H. pylori — sababu kuu moja', sw_mtaa: 'H. pylori infection — single biggest cause' },
    { en: 'Regular NSAID use (especially ibuprofen, diclofenac, aspirin)', sw: 'Matumizi ya kawaida ya NSAID (hasa ibuprofen, diclofenac, aspirini)', sw_mtaa: 'Regular NSAID use (especially ibuprofen, diclofenac, aspirin)' },
    { en: 'Smoking — slows healing, increases recurrence', sw: 'Sigara — hupunguza kupona, huongeza kurudia', sw_mtaa: 'Smoking — inaslow healing, inaongeza recurrence' },
    { en: 'Heavy alcohol use', sw: 'Matumizi mengi ya pombe', sw_mtaa: 'Heavy alcohol use' },
    { en: 'Severe physical stress (major illness, ICU admission) — "stress ulcers"', sw: 'Mfadhaiko mkubwa wa kimwili (ugonjwa mkubwa, kulazwa ICU) — "stress ulcers"', sw_mtaa: 'Severe physical stress (major illness, ICU admission) — "stress ulcers"' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Vomiting blood (red or coffee-ground), black tarry stool — bleeding ulcer, emergency', sw: 'Kutapika damu (nyekundu au mfano wa misingi ya kahawa), kinyesi cheusi cha lami — kidonda kinatoka damu, dharura', sw_mtaa: 'Vomiting blood (red au coffee-ground), black tarry stool — bleeding ulcer, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Sudden severe abdominal pain like a knife, board-like rigid abdomen — perforation, emergency', sw: 'Maumivu makali ya ghafla ya tumbo kama kisu, tumbo gumu kama ubao — kutoboa, dharura', sw_mtaa: 'Sudden severe abdominal pain kama knife, board-like rigid abdomen — perforation, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Difficulty swallowing, persistent vomiting, weight loss in someone with ulcer symptoms', sw: 'Ugumu wa kumeza, kutapika kwa kuendelea, kupoteza uzito kwa mtu mwenye dalili za kidonda', sw_mtaa: 'Difficulty swallowing, persistent vomiting, weight loss kwa mtu mwenye ulcer symptoms' }, urgency: 'urgent' },
    { sign: { en: 'New upper abdominal pain in someone over 55, especially with anaemia or weight loss', sw: 'Maumivu mapya ya juu ya tumbo kwa mtu zaidi ya miaka 55, hasa na upungufu wa damu au kupoteza uzito', sw_mtaa: 'New upper abdominal pain kwa mtu over 55, especially na anaemia au weight loss' }, urgency: 'urgent' },
  ],
  comorbidityNotes: [
    { coCondition: 'anaemia', note: { en: 'Iron-deficiency anaemia, especially in older adults, can be caused by silent slow GI bleeding from an ulcer or stomach cancer. Endoscopy is part of the workup.', sw: 'Upungufu wa damu wa madini ya chuma, hasa kwa watu wazima, unaweza kusababishwa na kutokwa damu kimya kimya kwa polepole kwa utumbo kutoka kidonda au saratani ya tumbo. Endoscopy ni sehemu ya uchunguzi.', sw_mtaa: 'Iron-deficiency anaemia, especially kwa older adults, inaweza kusababishwa na silent slow GI bleeding kutoka ulcer au stomach cancer. Endoscopy ni sehemu ya workup.' } },
  ],
  sources: [src('NTLG_STG_2023'), src('WHO_AMR_2023'), src('BNF_CURRENT'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
