/**
 * Snake Bite — Phase 15. Sources: WHO Snakebite 2023, NTLG STG 2023, Muhimbili.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const SNAKE_BITE: ConditionKnowledge = {
  id: 'snake_bite',
  aliases: CONDITION_ALIASES.snake_bite,
  category: 'other',
  whatItIs: {
    en: 'Snake bite is a major rural emergency in Tanzania, mostly affecting farmers, herders, and children. Important Tanzanian snakes include: puff adder (Bitis arietans — heavy-bodied, very common, cytotoxic venom causing pain, swelling, tissue necrosis); black mamba (Dendroaspis polylepis — fast neurotoxic venom causing paralysis); spitting cobras (Naja species — neurotoxic + cytotoxic, can spray venom into the eyes); green mambas; boomslangs (tree snakes — haemotoxic). Many bites are by non-venomous snakes; many are "dry bites" with no envenoming. The key clinical question is not "which snake" but "is there envenoming" — venomous bites produce systemic signs (bleeding, drowsiness, paralysis, dark urine) or progressive local signs (rapidly spreading swelling, blistering, necrosis).',
    sw: 'Kuumwa na nyoka ni dharura kubwa ya vijijini Tanzania, hasa huathiri wakulima, wachungaji, na watoto. Nyoka muhimu Tanzania ni pamoja na: puff adder (Bitis arietans — mwili mzito, wa kawaida sana, sumu ya cytotoxic husababisha maumivu, uvimbe, necrosis ya tishu); black mamba (Dendroaspis polylepis — sumu ya haraka ya neurotoxic husababisha kupooza); spitting cobras (aina za Naja — neurotoxic + cytotoxic, zinaweza kunyunyiza sumu machoni); green mambas; boomslangs (nyoka wa mtini — haemotoxic). Kuumwa kwingi ni kwa nyoka wasio na sumu; kuumwa kwingi ni "kuumwa kavu" pasipo envenoming. Swali muhimu la kimatibabu sio "nyoka gani" bali "kuna envenoming" — kuumwa kwa nyoka wenye sumu hutoa ishara za kimfumo (kutokwa damu, usingizi, kupooza, mkojo mweusi) au ishara za ndani zinazoendelea (uvimbe unaoenea haraka, malengelenge, necrosis).',
    sw_mtaa: 'Snake bite ni major rural emergency Tanzania, mostly inaaffect farmers, herders, na watoto. Important Tanzanian snakes ni pamoja na: puff adder (Bitis arietans — heavy-bodied, very common, cytotoxic venom inasababisha pain, swelling, tissue necrosis); black mamba (Dendroaspis polylepis — fast neurotoxic venom inasababisha paralysis); spitting cobras (Naja species — neurotoxic + cytotoxic, zinaweza kuspray venom katika eyes); green mambas; boomslangs (tree snakes — haemotoxic). Many bites ni za non-venomous snakes; many ni "dry bites" bila envenoming. Key clinical question sio "which snake" bali "is there envenoming" — venomous bites zinaproduce systemic signs (bleeding, drowsiness, paralysis, dark urine) au progressive local signs (rapidly spreading swelling, blistering, necrosis).',
  },
  whyItMatters: {
    en: 'Snake bite kills thousands across sub-Saharan Africa every year and disables many more through tissue loss. Tanzania has polyvalent antivenom at district hospitals and regional referral hospitals, but delays in reaching care, harmful traditional first-aid (cutting, sucking, applying herbs), and panic-driven over-tight tourniquets cause many deaths and amputations. The right first aid is simple and saves limbs and lives: keep the patient still, immobilise the bitten limb at heart level or slightly below, remove rings/watches, transport urgently to a hospital with antivenom. DO NOT cut, suck, apply ice, apply herbs, apply tight tourniquet, or give alcohol. DO NOT try to catch the snake — a photo from a safe distance is enough.',
    sw: 'Kuumwa na nyoka huua maelfu Afrika kusini mwa jangwa la Sahara kila mwaka na hulemaza wengine wengi kupitia kupoteza tishu. Tanzania ina polyvalent antivenom katika hospitali za wilaya na hospitali za rufaa za mkoa, lakini kucheleweshwa kufikia huduma, msaada wa kwanza wa kijadi unaodhuru (kukata, kunyonya, kuweka mimea), na tourniquet zilizobana sana zinazochochewa na hofu husababisha vifo vingi na kukatwa viungo. Msaada sahihi wa kwanza ni rahisi na unaokoa viungo na maisha: weka mgonjwa tulivu, simamisha kiungo kilichoumwa kwa kiwango cha moyo au kidogo chini, ondoa pete/saa, peleka haraka hospitalini iliyo na antivenom. USIKATE, usinyonye, usitie barafu, usiweke mimea, usifunge tourniquet kali, au usimpe pombe. USIJARIBU kushika nyoka — picha kutoka umbali salama inatosha.',
    sw_mtaa: 'Snake bite inaua thousands across sub-Saharan Africa kila mwaka na inadisable wengi zaidi through tissue loss. Tanzania ina polyvalent antivenom katika district hospitals na regional referral hospitals, lakini delays kufikia care, harmful traditional first-aid (kukata, kunyonya, kuapply herbs), na panic-driven over-tight tourniquets zinasababisha many deaths na amputations. Right first aid ni simple na inaokoa limbs na lives: keep patient still, immobilise bitten limb at heart level au kidogo below, remove rings/watches, transport urgently kwenda hospital yenye antivenom. DO NOT kata, nyonya, weka ice, weka herbs, funga tight tourniquet, au give alcohol. DO NOT jaribu kushika nyoka — photo kutoka safe distance inatosha.',
  },
  commonQuestions: [
    { q: { en: 'What is the correct first aid for snake bite?', sw: 'Msaada gani sahihi wa kwanza wa kuumwa na nyoka?' }, a: { en: 'Keep calm and minimise movement. Remove rings, watches, tight clothing from the affected limb. Immobilise the bitten limb (a splint or sling) and keep it at or just below heart level. Mark the leading edge of any swelling with the time. Transport urgently to the nearest hospital with antivenom. Do NOT cut the bite, do NOT try to suck out venom, do NOT apply tight tourniquet, do NOT apply ice or herbs, do NOT give alcohol or food. For spitting cobra venom in the eye: rinse with copious clean water for 15 minutes and seek urgent eye care.', sw: 'Tulia na punguza harakati. Ondoa pete, saa, nguo zilizobana kutoka kiungo kilichoathirika. Simamisha kiungo kilichoumwa (splint au sling) na kihifadhi kwa kiwango cha moyo au tu chini. Onyesha ukingo unaoongoza wa uvimbe wowote kwa wakati. Peleka haraka hospitali ya karibu zaidi yenye antivenom. USIKATE kuumwa, usijaribu kunyonya sumu, usifunge tourniquet kali, usitie barafu au mimea, usimpe pombe au chakula. Kwa sumu ya cobra inayonyunyiza machoni: suuza na maji safi mengi kwa dakika 15 na tafuta huduma ya haraka ya macho.', sw_mtaa: 'Stay calm na punguza movement. Ondoa rings, watches, tight clothing kutoka affected limb. Immobilise bitten limb (splint au sling) na uihifadhi at au kidogo below heart level. Mark leading edge ya swelling yoyote na time. Transport urgently kwenda nearest hospital yenye antivenom. Do NOT kata bite, do NOT jaribu kunyonya venom, do NOT funga tight tourniquet, do NOT weka ice au herbs, do NOT mpe pombe au food. Kwa spitting cobra venom katika eye: rinse na copious clean water kwa dakika 15 na utafute urgent eye care.' } },
    { q: { en: 'How do I know if envenoming has happened?', sw: 'Najuaje kama envenoming imetokea?' }, a: { en: 'Systemic envenoming signs: drowsiness, drooping eyelids, difficulty swallowing or speaking, weakness, paralysis (neurotoxic — mamba, cobra); bleeding from gums, nose, urine, or bite site (haemotoxic — boomslang); dark urine, weakness, kidney failure (cytotoxic — some adders). Local envenoming signs: rapidly spreading swelling, severe pain, blistering, dark discoloured tissue, regional lymphadenopathy. Any of these means antivenom is needed urgently. If after 24 hours there are no symptoms, it was likely a dry bite or non-venomous snake.', sw: 'Ishara za envenoming ya kimfumo: usingizi, kupungua kwa kope, ugumu wa kumeza au kuongea, udhaifu, kupooza (neurotoxic — mamba, cobra); kutokwa damu kutoka ufizi, pua, mkojo, au sehemu ya kuumwa (haemotoxic — boomslang); mkojo mweusi, udhaifu, kushindwa kwa figo (cytotoxic — baadhi ya adder). Ishara za envenoming za ndani: uvimbe unaoenea haraka, maumivu makali, malengelenge, tishu zilizobadilika rangi nyeusi, lymphadenopathy ya kanda. Yoyote ya hizi inamaanisha antivenom inahitajika haraka. Ikiwa baada ya masaa 24 hakuna dalili, ilikuwa labda kuumwa kavu au nyoka asiye na sumu.', sw_mtaa: 'Systemic envenoming signs: drowsiness, drooping eyelids, difficulty swallowing au speaking, weakness, paralysis (neurotoxic — mamba, cobra); bleeding kutoka gums, nose, urine, au bite site (haemotoxic — boomslang); dark urine, weakness, kidney failure (cytotoxic — some adders). Local envenoming signs: rapidly spreading swelling, severe pain, blistering, dark discoloured tissue, regional lymphadenopathy. Yoyote ya hizi inamaanisha antivenom inahitajika urgently. Ikiwa baada ya masaa 24 hakuna symptoms, ilikuwa likely dry bite au non-venomous snake.' } },
    { q: { en: 'Where can I get antivenom in Tanzania?', sw: 'Naweza kupata antivenom wapi Tanzania?' }, a: { en: 'Polyvalent antivenom is stocked at district hospitals and regional referral hospitals in Tanzania. Health centres usually do not have it and patients must be transferred. The closer the hospital with stock, the better the outcome — never spend time on home or traditional remedies. Call ahead if possible. Antivenom is given as a slow IV infusion under medical supervision because of reaction risk; clinicians give adrenaline at the bedside in case of anaphylaxis.', sw: 'Antivenom ya polyvalent inahifadhiwa katika hospitali za wilaya na hospitali za rufaa za mkoa Tanzania. Vituo vya afya kawaida havina na wagonjwa lazima wahamishwe. Karibu zaidi hospitali yenye akiba, matokeo bora — kamwe usitumie muda kwenye dawa za nyumbani au za kijadi. Piga simu mapema ikiwezekana. Antivenom hutolewa kama IV infusion ya polepole chini ya usimamizi wa kimatibabu kwa sababu ya hatari ya athari; madaktari hutoa adrenaline pembeni mwa kitanda kwa hali ya anaphylaxis.', sw_mtaa: 'Polyvalent antivenom inahifadhiwa katika district hospitals na regional referral hospitals Tanzania. Health centres usually hazina na patients lazima watransferred. Closer hospital yenye stock, better outcome — never spend time kwa home au traditional remedies. Call ahead ikiwezekana. Antivenom inatolewa kama slow IV infusion chini ya medical supervision kwa sababu ya reaction risk; clinicians wanagive adrenaline at bedside in case ya anaphylaxis.' } },
    { q: { en: 'Should I try to kill or catch the snake?', sw: 'Nijaribu kuua au kushika nyoka?' }, a: { en: 'No — trying to catch the snake leads to second bites and delays transport. A photo from a safe distance is much more useful and is enough for identification. Polyvalent antivenom in Tanzania covers the major dangerous species, so exact identification is not required for treatment. Time matters far more than species.', sw: 'Hapana — kujaribu kushika nyoka husababisha kuumwa mara ya pili na kuchelewa kwa usafiri. Picha kutoka umbali salama ni ya manufaa zaidi na inatosha kwa utambulisho. Antivenom ya polyvalent Tanzania inafunika aina kuu hatari, kwa hivyo utambulisho kamili hauhitajiki kwa matibabu. Muda ni muhimu zaidi sana kuliko aina.', sw_mtaa: 'Hapana — kujaribu kushika nyoka inasababisha second bites na delays katika transport. Photo kutoka safe distance ni much more useful na inatosha kwa identification. Polyvalent antivenom Tanzania inafunika major dangerous species, kwa hivyo exact identification hairequired kwa treatment. Time inamatter far more kuliko species.' } },
  ],
  selfManagement: [
    { en: 'Wear closed shoes and trousers when working in fields or grasslands, especially at dawn and dusk.', sw: 'Vaa viatu vilivyofungwa na suruali unapofanya kazi mashambani au katika malisho, hasa alfajiri na jioni.', sw_mtaa: 'Vaa closed shoes na trousers unapofanya kazi katika fields au grasslands, especially dawn na dusk.' },
    { en: 'Use a torch at night — many bites happen when stepping on snakes in the dark.', sw: 'Tumia tochi usiku — kuumwa kwingi hutokea unapokanyaga nyoka gizani.', sw_mtaa: 'Tumia torch usiku — many bites zinatokea unapostep on snakes gizani.' },
    { en: 'Sleep under a tucked-in bednet — snakes sometimes enter houses at night.', sw: 'Lala chini ya neti iliyofungwa ndani — nyoka wakati mwingine huingia majumbani usiku.', sw_mtaa: 'Lala chini ya tucked-in bednet — snakes wakati mwingine zinaingia katika houses usiku.' },
    { en: 'Keep grass cut short around the house and store firewood away from sleeping areas.', sw: 'Kata nyasi karibu na nyumba ziwe fupi na hifadhi kuni mbali na maeneo ya kulala.', sw_mtaa: 'Keep nyasi cut short karibu na nyumba na store firewood mbali na sleeping areas.' },
    { en: 'Know where your nearest hospital with antivenom is BEFORE you need it — and a transport plan.', sw: 'Jua hospitali yako ya karibu zaidi yenye antivenom KABLA ya kuihitaji — na mpango wa usafiri.', sw_mtaa: 'Know wapi nearest hospital yako yenye antivenom iko KABLA ya kuihitaji — na transport plan.' },
  ],
  warningTriggers: [
    { en: 'Walking in long grass, near water, or in fields at dawn/dusk', sw: 'Kutembea katika nyasi ndefu, karibu na maji, au mashambani alfajiri/jioni', sw_mtaa: 'Walking katika long grass, karibu na water, au katika fields dawn/dusk' },
    { en: 'Gathering firewood — common bite location', sw: 'Kukusanya kuni — eneo la kawaida la kuumwa', sw_mtaa: 'Gathering firewood — common bite location' },
    { en: 'Sleeping on the floor without a bednet', sw: 'Kulala sakafuni pasipo neti', sw_mtaa: 'Sleeping floor bila bednet' },
    { en: 'Reaching into rodent holes, woodpiles, or storage areas without checking', sw: 'Kuingia mashimo ya panya, marundo ya kuni, au maeneo ya hifadhi pasipo kuchunguza', sw_mtaa: 'Reaching katika rodent holes, woodpiles, au storage areas bila checking' },
  ],
  whenToSeekCare: [
    { sign: { en: 'ANY snake bite — go to hospital immediately. Even if it looks dry/mild, observe for 24 hours.', sw: 'Kuumwa na nyoka YOYOTE — nenda hospitali mara moja. Hata ikiwa inaonekana kavu/ndogo, chunguza kwa masaa 24.', sw_mtaa: 'ANY snake bite — nenda hospital immediately. Hata ikiwa inaonekana dry/mild, observe kwa masaa 24.' }, urgency: 'emergency' },
    { sign: { en: 'Drowsiness, drooping eyelids, weakness, difficulty breathing — neurotoxic envenoming, emergency', sw: 'Usingizi, kushuka kwa kope, udhaifu, ugumu wa kupumua — envenoming ya neurotoxic, dharura', sw_mtaa: 'Drowsiness, drooping eyelids, weakness, difficulty breathing — neurotoxic envenoming, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Bleeding from gums, nose, or urine; large bruises; dark urine — haemotoxic envenoming, emergency', sw: 'Kutokwa damu kutoka ufizi, pua, au mkojo; alama kubwa za michubuko; mkojo mweusi — envenoming ya haemotoxic, dharura', sw_mtaa: 'Bleeding kutoka gums, nose, au urine; large bruises; dark urine — haemotoxic envenoming, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Venom in the eye (spitting cobra) — rinse with water 15 minutes and seek emergency eye care', sw: 'Sumu jichoni (cobra anayenyunyiza) — suuza na maji dakika 15 na utafute huduma ya dharura ya jicho', sw_mtaa: 'Venom katika eye (spitting cobra) — rinse na water dakika 15 na utafute emergency eye care' }, urgency: 'emergency' },
  ],
  comorbidityNotes: [],
  sources: [src('WHO_SNAKEBITE_2023'), src('NTLG_STG_2023'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
