/**
 * Typhoid Fever — Phase 15. Sources: NTLG STG 2023, WHO Typhoid 2018, WHO AMR.
 * GOVERNANCE: DRAFT.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const TYPHOID: ConditionKnowledge = {
  id: 'typhoid',
  aliases: CONDITION_ALIASES.typhoid,
  category: 'infectious',
  whatItIs: {
    en: 'Typhoid fever is a serious bloodstream and gut infection caused by Salmonella Typhi, spread through food or water contaminated by faeces. It causes prolonged fever (rising step-by-step over a week), headache, abdominal pain, constipation or diarrhoea, weakness, and sometimes a faint pink rash on the trunk. Untreated typhoid can perforate the bowel or cause sepsis. It remains endemic in many parts of Tanzania, especially where water and sanitation are limited.',
    sw: 'Homa ya matumbo (typhoid) ni maambukizi makali ya damu na utumbo yanayosababishwa na Salmonella Typhi, yanayoenea kupitia chakula au maji yaliyochafuliwa na kinyesi. Husababisha homa ya muda mrefu (inayopanda hatua kwa hatua kwa wiki), maumivu ya kichwa, maumivu ya tumbo, kufunga choo au kuhara, udhaifu, na wakati mwingine vipele vya pink kwenye shina. Typhoid isiyotibiwa inaweza kutoboa utumbo au kusababisha sepsis. Inabaki kuwa endemic katika sehemu nyingi za Tanzania, hasa ambapo maji na usafi ni mdogo.',
    sw_mtaa: 'Typhoid ni serious bloodstream na gut infection inayosababishwa na Salmonella Typhi, inayoenea kupitia food au water iliyo-contaminated na faeces. Inasababisha prolonged fever (inayorise step-by-step over week), headache, abdominal pain, constipation au diarrhoea, weakness, na wakati mwingine faint pink rash kwenye trunk. Untreated typhoid inaweza kuperforate bowel au kusababisha sepsis. Inabaki endemic katika sehemu nyingi za Tanzania, especially ambapo water na sanitation ni limited.',
  },
  whyItMatters: {
    en: 'Typhoid is one of the major causes of "fever without malaria" in Tanzania. It needs antibiotics — but the right choice has changed because of resistance: chloramphenicol and amoxicillin are no longer reliable, and resistance to ciprofloxacin is rising. WHO and Tanzania now favour azithromycin or ceftriaxone in many settings, but local resistance patterns guide choice. Blood culture confirms; Widal test alone is unreliable. Family contacts may need treatment if symptomatic, and water/food hygiene prevents spread. A typhoid conjugate vaccine is available and increasingly used.',
    sw: 'Typhoid ni mojawapo ya sababu kuu za "homa pasipo malaria" Tanzania. Inahitaji antibiotic — lakini chaguo sahihi limebadilika kwa sababu ya upinzani: chloramphenicol na amoxicillin si za kuaminika tena, na upinzani wa ciprofloxacin unaongezeka. WHO na Tanzania sasa hupendelea azithromycin au ceftriaxone katika hali nyingi, lakini muundo wa upinzani wa ndani huongoza chaguo. Utamaduni wa damu huthibitisha; jaribio la Widal pekee si la kuaminika. Watu wa familia waliokutana wanaweza kuhitaji matibabu ikiwa wana dalili, na usafi wa maji/chakula huzuia kuenea. Chanjo ya conjugate ya typhoid inapatikana na inatumika zaidi.',
    sw_mtaa: 'Typhoid ni mojawapo ya major causes ya "fever without malaria" Tanzania. Inahitaji antibiotics — lakini right choice imebadilika kwa sababu ya resistance: chloramphenicol na amoxicillin sio reliable tena, na resistance kwa ciprofloxacin inaongezeka. WHO na Tanzania sasa zinafavour azithromycin au ceftriaxone katika settings nyingi, lakini local resistance patterns zinaguide choice. Blood culture inaconfirm; Widal test alone ni unreliable. Family contacts wanaweza kuhitaji treatment ikiwa symptomatic, na water/food hygiene inazuia spread. Typhoid conjugate vaccine inapatikana na inatumika zaidi.',
  },
  commonQuestions: [
    { q: { en: 'How do I know if I have typhoid?', sw: 'Nitajuaje kama nina typhoid?' }, a: { en: 'Suspect typhoid in anyone with fever for more than a week, especially with headache, abdominal pain, constipation/diarrhoea, weakness, and a negative malaria test. Blood culture is the most reliable test. Widal test alone is unreliable in endemic areas — it can be positive from past exposure.', sw: 'Shuku typhoid kwa yeyote mwenye homa kwa zaidi ya wiki, hasa na maumivu ya kichwa, maumivu ya tumbo, kufunga choo/kuhara, udhaifu, na MRDT hasi. Utamaduni wa damu ni jaribio la kuaminika zaidi. Jaribio la Widal pekee si la kuaminika katika maeneo endemic — linaweza kuwa chanya kutoka mfiduo wa zamani.', sw_mtaa: 'Suspect typhoid kwa yeyote mwenye fever kwa zaidi ya wiki, especially na headache, abdominal pain, constipation/diarrhoea, weakness, na negative malaria test. Blood culture ni most reliable test. Widal test alone ni unreliable katika endemic areas — inaweza kuwa positive kutoka past exposure.' } },
    { q: { en: 'How is typhoid treated?', sw: 'Typhoid inatibiwaje?' }, a: { en: 'First-line per local resistance: azithromycin (oral, 7 days) for uncomplicated typhoid; ceftriaxone IV for severe/complicated cases. Ciprofloxacin only if local sensitivity confirms. Full course is essential; relapse is common with short courses. Hydration, fever control, soft food. Hospital admission if vomiting, bleeding, perforation, or altered mental state.', sw: 'Ya kwanza kulingana na upinzani wa ndani: azithromycin (kumeza, siku 7) kwa typhoid isiyo na matatizo; ceftriaxone IV kwa kesi kali/zenye matatizo. Ciprofloxacin tu ikiwa unyeti wa ndani unathibitisha. Kozi kamili ni muhimu; kurudi ni kawaida na kozi fupi. Hidratisheni, kudhibiti homa, chakula laini. Kulazwa hospitalini ikiwa kutapika, kutokwa damu, kutoboa, au mabadiliko ya hali ya akili.', sw_mtaa: 'First-line per local resistance: azithromycin (oral, siku 7) kwa uncomplicated typhoid; ceftriaxone IV kwa severe/complicated cases. Ciprofloxacin tu ikiwa local sensitivity inaconfirm. Full course ni essential; relapse ni common na short courses. Hydration, fever control, soft food. Hospital admission ikiwa vomiting, bleeding, perforation, au altered mental state.' } },
    { q: { en: 'Should I get the typhoid vaccine?', sw: 'Niitumie chanjo ya typhoid?' }, a: { en: 'Yes, especially for children and people in high-risk areas. The newer typhoid conjugate vaccine (TCV) gives long-lasting protection from age 6 months and is being introduced in routine immunisation in Tanzania. Travellers to endemic areas should also be vaccinated. Vaccine doesn\'t replace good hygiene but adds an extra layer.', sw: 'Ndio, hasa kwa watoto na watu katika maeneo ya hatari kubwa. Chanjo mpya ya typhoid conjugate (TCV) inatoa ulinzi wa muda mrefu kutoka umri wa miezi 6 na inaingizwa katika chanjo za kawaida Tanzania. Wasafiri kwenda maeneo endemic pia wanapaswa kupewa chanjo. Chanjo haibadilishi usafi mzuri lakini huongeza safu ya ziada.', sw_mtaa: 'Ndio, especially kwa children na watu katika high-risk areas. Newer typhoid conjugate vaccine (TCV) inatoa long-lasting protection from age miezi 6 na inaingizwa katika routine immunisation Tanzania. Travellers to endemic areas pia wanapaswa kupewa chanjo. Vaccine hairepalce good hygiene lakini inaongeza extra layer.' } },
    { q: { en: 'How can typhoid be prevented?', sw: 'Typhoid inawezaje kuzuiwa?' }, a: { en: 'Drink only safe water (boiled, bottled, or treated), wash hands with soap, eat hot freshly-cooked food, peel fruit yourself, avoid ice from unknown sources, avoid raw shellfish. Improving sanitation at home and in the community is the long-term solution. Vaccination adds protection.', sw: 'Kunywa maji salama tu (yaliyochemshwa, ya chupa, au yaliyotibiwa), osha mikono na sabuni, kula chakula moto kilichopikwa hivi karibuni, menya matunda mwenyewe, epuka barafu kutoka vyanzo visivyojulikana, epuka samaki gamba mbichi. Kuboresha usafi nyumbani na katika jamii ni suluhisho la muda mrefu. Chanjo huongeza ulinzi.', sw_mtaa: 'Kunywa safe water tu (boiled, bottled, au treated), wash hands na sabuni, kula hot freshly-cooked food, menya matunda mwenyewe, epuka ice kutoka unknown sources, epuka raw shellfish. Improving sanitation nyumbani na katika community ni long-term solution. Vaccination inaongeza protection.' } },
  ],
  selfManagement: [
    { en: 'Take the full antibiotic course exactly as prescribed — short courses cause relapse.', sw: 'Chukua kozi kamili ya antibiotic kama ilivyoamriwa — kozi fupi husababisha kurudi.', sw_mtaa: 'Chukua full antibiotic course exactly kama prescribed — short courses zinasababisha relapse.' },
    { en: 'Drink plenty of fluids; fever and sweating cause dehydration.', sw: 'Kunywa maji mengi; homa na jasho husababisha kukosa maji.', sw_mtaa: 'Kunywa maji mengi; fever na sweating zinasababisha dehydration.' },
    { en: 'Eat soft, easily digested food — typhoid affects the gut; spicy or rough food can worsen abdominal pain.', sw: 'Kula chakula laini, kinachoyeyuka kwa urahisi — typhoid huathiri utumbo; chakula chenye viungo au kigumu kinaweza kuzidisha maumivu ya tumbo.', sw_mtaa: 'Kula soft, easily digested food — typhoid inaaffect gut; spicy au rough food inaweza kuworsen abdominal pain.' },
    { en: 'Boil all drinking water at home until family contacts are tested.', sw: 'Chemsha maji yote ya kunywa nyumbani hadi watu wa familia waliokutana wapimwe.', sw_mtaa: 'Boil drinking water yote nyumbani hadi family contacts wapimwe.' },
    { en: 'Wash hands with soap before eating and after toilet — typhoid spreads through faeces.', sw: 'Osha mikono na sabuni kabla ya kula na baada ya choo — typhoid inaenea kupitia kinyesi.', sw_mtaa: 'Wash hands na soap kabla ya kula na baada ya toilet — typhoid inaenea kupitia faeces.' },
  ],
  warningTriggers: [
    { en: 'Contaminated water — especially during rainy season floods', sw: 'Maji yaliyochafuliwa — hasa wakati wa mafuriko ya msimu wa mvua', sw_mtaa: 'Contaminated water — especially wakati wa rainy season floods' },
    { en: 'Street food in poor sanitation areas', sw: 'Chakula cha barabarani katika maeneo yenye usafi mbaya', sw_mtaa: 'Street food katika poor sanitation areas' },
    { en: 'Recent travel to typhoid-endemic area without vaccination', sw: 'Safari ya hivi karibuni katika eneo la typhoid-endemic bila chanjo', sw_mtaa: 'Recent travel kwenda typhoid-endemic area bila vaccination' },
    { en: 'Crowded living conditions, poor hand hygiene', sw: 'Hali ya kuishi yenye msongamano, usafi mbaya wa mikono', sw_mtaa: 'Crowded living conditions, poor hand hygiene' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Severe abdominal pain, distension, or rigidity — possible bowel perforation, emergency', sw: 'Maumivu makali ya tumbo, kuvimba, au ugumu — uwezekano wa kutoboa utumbo, dharura', sw_mtaa: 'Severe abdominal pain, distension, au rigidity — possible bowel perforation, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Black or bloody stools, vomiting blood — GI bleeding, emergency', sw: 'Kinyesi cheusi au chenye damu, kutapika damu — kutokwa damu kwa utumbo, dharura', sw_mtaa: 'Black au bloody stools, vomiting blood — GI bleeding, emergency' }, urgency: 'emergency' },
    { sign: { en: 'Confusion, drowsiness, very high fever — severe typhoid, admit', sw: 'Mkanganyiko, usingizi, homa ya juu sana — typhoid kali, laze', sw_mtaa: 'Confusion, drowsiness, very high fever — severe typhoid, admit' }, urgency: 'emergency' },
    { sign: { en: 'Fever > 7 days with negative malaria test — investigate for typhoid', sw: 'Homa > siku 7 na MRDT hasi — chunguza kwa typhoid', sw_mtaa: 'Fever > siku 7 na negative malaria test — investigate kwa typhoid' }, urgency: 'urgent' },
  ],
  comorbidityNotes: [
    { coCondition: 'malaria', note: { en: 'Typhoid and malaria can co-exist. A "negative malaria + ongoing fever" picture should prompt typhoid investigation. Conversely, fever in a malaria-endemic area without bowel symptoms is more often malaria.', sw: 'Typhoid na malaria zinaweza kuwepo pamoja. Picha ya "MRDT hasi + homa inaendelea" inapaswa kuhamasisha uchunguzi wa typhoid. Kinyume chake, homa katika eneo malaria-endemic bila dalili za utumbo mara nyingi ni malaria.', sw_mtaa: 'Typhoid na malaria zinaweza kuco-exist. "Negative malaria + ongoing fever" picture inapaswa kuprompt typhoid investigation. Conversely, fever katika malaria-endemic area bila bowel symptoms mara nyingi ni malaria.' } },
  ],
  sources: [src('WHO_TYPHOID_2018'), src('NTLG_STG_2023'), src('WHO_AMR_2023'), src('MUHIMBILI_PROTOCOLS')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
