/**
 * Urinary Tract Infection (UTI) — Phase 15
 * Sources: WHO, NTLG STG 2023, WHO AMR 2023, BNF.
 */
import { ConditionKnowledge } from '../../types';
import { CONDITION_ALIASES } from '../../engine/synonyms';
import { src } from '../../governance/sources';

export const UTI: ConditionKnowledge = {
  id: 'uti',
  aliases: CONDITION_ALIASES.uti,
  category: 'infectious',
  whatItIs: {
    en: 'A urinary tract infection (UTI) is a bacterial infection of the bladder (cystitis), urethra, or — more seriously — the kidneys (pyelonephritis). Most are caused by E. coli. Symptoms include burning on urination, frequency, urgency, lower abdominal pain, and sometimes blood in the urine. Pyelonephritis adds fever, flank pain, nausea/vomiting and is a more serious illness needing antibiotics by mouth or sometimes IV. UTIs are common in women (short urethra), in pregnancy (where untreated UTI can cause preterm labour), in elderly men with prostate enlargement, and in people with diabetes or kidney stones.',
    sw: 'Maambukizi ya njia ya mkojo (UTI) ni maambukizi ya bakteria ya kibofu (cystitis), urethra, au — kwa uzito zaidi — figo (pyelonephritis). Mengi husababishwa na E. coli. Dalili ni pamoja na kuwaka wakati wa kukojoa, mara kwa mara, haraka, maumivu ya tumbo la chini, na wakati mwingine damu kwenye mkojo. Pyelonephritis huongeza homa, maumivu ya kiunoni, kichefuchefu/kutapika na ni ugonjwa mkali zaidi unaohitaji antibiotic ya kumeza au wakati mwingine IV. UTI ni za kawaida kwa wanawake (urethra fupi), katika mimba (ambapo UTI isiyotibiwa inaweza kusababisha kuzaa mapema), kwa wanaume wakubwa wenye prostate iliyoongezeka, na kwa watu wenye kisukari au mawe ya figo.',
    sw_mtaa: 'UTI ni bacterial infection ya bladder (cystitis), urethra, au — more seriously — kidneys (pyelonephritis). Most zinasababishwa na E. coli. Symptoms ni pamoja na burning on urination, frequency, urgency, lower abdominal pain, na wakati mwingine blood katika urine. Pyelonephritis inaongeza fever, flank pain, nausea/vomiting na ni more serious illness inayohitaji oral antibiotics au wakati mwingine IV. UTIs ni common kwa wanawake (short urethra), katika pregnancy (ambapo untreated UTI inaweza kusababisha preterm labour), kwa elderly men wenye prostate enlargement, na kwa watu wenye diabetes au kidney stones.',
  },
  whyItMatters: {
    en: 'Most UTIs respond well to short antibiotic courses, but untreated UTI in pregnancy can cause preterm birth and low birth weight; untreated pyelonephritis can cause sepsis or kidney damage. Recurrent UTIs in men, in women under 5 or over 50, or with haematuria should be investigated for stones, anatomical abnormalities, prostate enlargement, or rarely bladder cancer. UTI symptoms can also be the first sign of diabetes — checking urine and blood sugar at the first UTI is good practice.',
    sw: 'UTI nyingi hujibu vyema kwa kozi fupi za antibiotic, lakini UTI isiyotibiwa katika mimba inaweza kusababisha kuzaa mapema na uzito mdogo wa kuzaliwa; pyelonephritis isiyotibiwa inaweza kusababisha sepsis au uharibifu wa figo. UTI za mara kwa mara kwa wanaume, kwa wanawake chini ya 5 au juu ya 50, au na haematuria zinapaswa kuchunguzwa kwa mawe, hali zisizo za kawaida za kianatomia, prostate iliyoongezeka, au mara chache saratani ya kibofu. Dalili za UTI pia zinaweza kuwa ishara ya kwanza ya kisukari — kupima mkojo na sukari ya damu katika UTI ya kwanza ni utendaji mzuri.',
    sw_mtaa: 'Most UTIs zinarespond vizuri kwa short antibiotic courses, lakini untreated UTI katika pregnancy inaweza kusababisha preterm birth na low birth weight; untreated pyelonephritis inaweza kusababisha sepsis au kidney damage. Recurrent UTIs kwa men, kwa women under 5 au over 50, au na haematuria zinapaswa kuinvestigated kwa stones, anatomical abnormalities, prostate enlargement, au rarely bladder cancer. UTI symptoms pia zinaweza kuwa first sign ya diabetes — checking urine na blood sugar at first UTI ni good practice.',
  },
  commonQuestions: [
    { q: { en: 'What is a UTI?', sw: 'UTI ni nini?' }, a: { en: 'A bacterial infection of the urinary tract — bladder, urethra, or kidneys. Causes burning on urination, frequency, lower abdominal pain. Treatable with antibiotics.', sw: 'Maambukizi ya bakteria ya njia ya mkojo — kibofu, urethra, au figo. Husababisha kuwaka wakati wa kukojoa, mara kwa mara, maumivu ya tumbo la chini. Inatibika na antibiotic.', sw_mtaa: 'Bacterial infection ya urinary tract — bladder, urethra, au kidneys. Inasababisha burning on urination, frequency, lower abdominal pain. Inatibika na antibiotics.' } },
    { q: { en: 'How is UTI treated?', sw: 'UTI inatibiwaje?' }, a: { en: 'Uncomplicated cystitis in women: nitrofurantoin 5 days, or trimethoprim, or fosfomycin single dose, per local resistance patterns. Pyelonephritis: longer course of stronger antibiotic (often cefixime or ciprofloxacin), with admission if severe. Always full course, plenty of fluids, paracetamol for pain. In pregnancy, antibiotic choice changes — avoid ciprofloxacin and trimethoprim in early pregnancy.', sw: 'Cystitis isiyo na matatizo kwa wanawake: nitrofurantoin siku 5, au trimethoprim, au fosfomycin dose moja, kulingana na muundo wa upinzani wa ndani. Pyelonephritis: kozi ndefu zaidi ya antibiotic kali zaidi (mara nyingi cefixime au ciprofloxacin), na kulazwa ikiwa kali. Daima kozi kamili, maji mengi, paracetamol kwa maumivu. Katika mimba, chaguo la antibiotic linabadilika — epuka ciprofloxacin na trimethoprim katika mimba ya mapema.', sw_mtaa: 'Uncomplicated cystitis kwa women: nitrofurantoin siku 5, au trimethoprim, au fosfomycin single dose, per local resistance patterns. Pyelonephritis: longer course ya stronger antibiotic (mara nyingi cefixime au ciprofloxacin), na admission ikiwa severe. Always full course, plenty of fluids, paracetamol kwa pain. Katika pregnancy, antibiotic choice inabadilika — epuka ciprofloxacin na trimethoprim katika early pregnancy.' } },
    { q: { en: 'Is UTI dangerous in pregnancy?', sw: 'UTI ni hatari katika mimba?' }, a: { en: 'Yes — untreated UTI in pregnancy raises the risk of preterm labour, low birth weight, and pyelonephritis. Even ASYMPTOMATIC bacteriuria (bacteria in urine without symptoms) needs treatment in pregnancy. ANC visits should include urine dipstick screening.', sw: 'Ndio — UTI isiyotibiwa katika mimba huongeza hatari ya kuzaa mapema, uzito mdogo wa kuzaliwa, na pyelonephritis. Hata bakteria katika mkojo BILA dalili inahitaji matibabu katika mimba. Ziara za ANC zinapaswa kujumuisha uchunguzi wa dipstick ya mkojo.', sw_mtaa: 'Ndio — untreated UTI katika pregnancy inaraise risk ya preterm labour, low birth weight, na pyelonephritis. Even ASYMPTOMATIC bacteriuria (bacteria katika urine bila symptoms) inahitaji treatment katika pregnancy. ANC visits zinapaswa kujumuisha urine dipstick screening.' } },
    { q: { en: 'How can I prevent UTIs?', sw: 'Nawezaje kuzuia UTI?' }, a: { en: 'Drink plenty of water (target clear urine), pass urine when you feel the urge (don\'t hold it), wipe front-to-back after toilet (women), pass urine after sex, treat constipation. There is no strong evidence that cranberry juice prevents UTIs, but it does no harm.', sw: 'Kunywa maji mengi (lenga mkojo safi), kojoa unapohisi haja (usizuie), futa mbele kwenda nyuma baada ya choo (wanawake), kojoa baada ya kufanya mapenzi, tibu kufunga choo. Hakuna ushahidi mkubwa kwamba juisi ya cranberry inazuia UTI, lakini haifanyi madhara.', sw_mtaa: 'Kunywa maji mengi (target clear urine), kojoa unapohisi urge (usihold it), wipe front-to-back baada ya toilet (women), kojoa baada ya sex, treat constipation. Hakuna strong evidence kwamba cranberry juice inazuia UTIs, lakini haifanyi harm.' } },
  ],
  selfManagement: [
    { en: 'Drink plenty of water during a UTI — dilute urine flushes bacteria.', sw: 'Kunywa maji mengi wakati wa UTI — mkojo wa kuyeyuka unaondoa bakteria.', sw_mtaa: 'Kunywa maji mengi wakati wa UTI — dilute urine inaflush bacteria.' },
    { en: 'Take the full antibiotic course even when symptoms settle.', sw: 'Chukua kozi kamili ya antibiotic hata wakati dalili zinatulia.', sw_mtaa: 'Chukua full antibiotic course hata wakati symptoms zinasettle.' },
    { en: 'Paracetamol for pain and any fever — avoid NSAIDs if kidney function is uncertain.', sw: 'Paracetamol kwa maumivu na homa yoyote — epuka NSAID ikiwa utendaji wa figo si wa uhakika.', sw_mtaa: 'Paracetamol kwa pain na fever yoyote — epuka NSAIDs ikiwa kidney function ni uncertain.' },
    { en: 'Empty your bladder fully each time and after sex.', sw: 'Mwage kibofu kabisa kila wakati na baada ya kufanya mapenzi.', sw_mtaa: 'Empty bladder kabisa kila time na baada ya sex.' },
    { en: 'If symptoms persist after 48 hours of antibiotics, return to clinic — possible resistant organism or wrong diagnosis.', sw: 'Ikiwa dalili zinaendelea baada ya masaa 48 ya antibiotic, rudi kliniki — uwezekano wa kiumbe sugu au utambuzi mbaya.', sw_mtaa: 'Ikiwa symptoms zinapersist baada ya masaa 48 ya antibiotics, rudi clinic — possible resistant organism au wrong diagnosis.' },
  ],
  warningTriggers: [
    { en: 'Sexual activity (especially in women — "honeymoon cystitis")', sw: 'Shughuli za kingono (hasa kwa wanawake — "honeymoon cystitis")', sw_mtaa: 'Sexual activity (especially kwa women — "honeymoon cystitis")' },
    { en: 'Pregnancy (raised urinary stasis and immunological changes)', sw: 'Mimba (kuongezeka kwa stasis ya mkojo na mabadiliko ya kinga)', sw_mtaa: 'Pregnancy (raised urinary stasis na immunological changes)' },
    { en: 'Diabetes (high sugar in urine feeds bacteria)', sw: 'Kisukari (sukari ya juu katika mkojo hulisha bakteria)', sw_mtaa: 'Diabetes (high sugar katika urine inafeed bacteria)' },
    { en: 'Catheter use or other instrumentation of the urinary tract', sw: 'Matumizi ya catheter au mengineyo ya njia ya mkojo', sw_mtaa: 'Catheter use au other instrumentation ya urinary tract' },
    { en: 'Kidney stones, prostate enlargement, structural abnormalities', sw: 'Mawe ya figo, prostate iliyoongezeka, hali zisizo za kawaida za kimuundo', sw_mtaa: 'Kidney stones, prostate enlargement, structural abnormalities' },
  ],
  whenToSeekCare: [
    { sign: { en: 'Fever, chills, flank pain, vomiting — pyelonephritis, needs urgent antibiotic and assessment', sw: 'Homa, kutetemeka, maumivu ya kiunoni, kutapika — pyelonephritis, inahitaji antibiotic ya haraka na tathmini', sw_mtaa: 'Fever, chills, flank pain, vomiting — pyelonephritis, inahitaji urgent antibiotic na assessment' }, urgency: 'urgent' },
    { sign: { en: 'Blood in urine (especially without burning) — investigate for stones, infection, or rarely cancer', sw: 'Damu kwenye mkojo (hasa pasipo kuwaka) — chunguza mawe, maambukizi, au mara chache saratani', sw_mtaa: 'Blood katika urine (especially bila burning) — investigate kwa stones, infection, au rarely cancer' }, urgency: 'urgent' },
    { sign: { en: 'Pregnancy with any UTI symptoms — treat early to prevent preterm labour', sw: 'Mimba na dalili yoyote ya UTI — tibu mapema kuzuia kuzaa mapema', sw_mtaa: 'Pregnancy na UTI symptoms yoyote — treat early kuzuia preterm labour' }, urgency: 'urgent' },
    { sign: { en: 'Confusion in an elderly person — UTI can present as confusion in older adults, especially with fever', sw: 'Mkanganyiko kwa mtu mzee — UTI inaweza kujitokeza kama mkanganyiko kwa watu wazee, hasa na homa', sw_mtaa: 'Confusion kwa elderly person — UTI inaweza kupresent kama confusion kwa older adults, especially na fever' }, urgency: 'urgent' },
    { sign: { en: 'UTI symptoms persisting > 48 hours after starting antibiotics', sw: 'Dalili za UTI zinaendelea > masaa 48 baada ya kuanza antibiotic', sw_mtaa: 'UTI symptoms persisting > masaa 48 baada ya kuanza antibiotics' }, urgency: 'urgent' },
  ],
  comorbidityNotes: [
    { coCondition: 'maternal_care', note: { en: 'UTI in pregnancy must be treated even when asymptomatic; choose pregnancy-safe antibiotics. Recheck urine after treatment.', sw: 'UTI katika mimba lazima itibiwe hata bila dalili; chagua antibiotic salama kwa mimba. Pima tena mkojo baada ya matibabu.', sw_mtaa: 'UTI katika pregnancy lazima itibiwe hata asymptomatic; chagua pregnancy-safe antibiotics. Recheck urine baada ya treatment.' } },
    { coCondition: 'diabetes', note: { en: 'UTIs are more common, more severe, and more recurrent in diabetes. Good glucose control reduces them. Any new UTI in someone over 40 should prompt diabetes screening.', sw: 'UTI ni za kawaida zaidi, kali zaidi, na za kurudia zaidi katika kisukari. Udhibiti mzuri wa glukosi hupunguza. UTI yoyote mpya kwa mtu zaidi ya miaka 40 inapaswa kuhamasisha uchunguzi wa kisukari.', sw_mtaa: 'UTIs ni more common, more severe, na more recurrent katika diabetes. Good glucose control inareduce them. New UTI yoyote kwa mtu over 40 inapaswa kuprompt diabetes screening.' } },
  ],
  sources: [src('NTLG_STG_2023'), src('WHO_AMR_2023'), src('MUHIMBILI_PROTOCOLS'), src('BNF_CURRENT')],
  governance: { status: 'draft', draftedBy: 'TibaAI-engine', contentVersion: '0.1.0' },
};
