// icd11Sw.ts — ICD-11 codes (Ch.6 mental + chronic + perinatal + addiction) in Swahili.
// 100 entries. Source: WHO ICD-11 (https://icd.who.int/) — Swahili translations curated.

export interface Icd11Entry {
  code: string;
  name_sw: string;
  name_en: string;
  chapter: string;
  source: 'WHO ICD-11';
}

export const ICD11_SW: Icd11Entry[] = [
  // Ch.6 Mental, behavioural and neurodevelopmental
  { code: '6A00', name_sw: 'Matatizo ya ukuaji wa kiakili', name_en: 'Disorders of intellectual development', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A01', name_sw: 'Matatizo ya ukuaji wa lugha', name_en: 'Developmental speech or language disorders', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A02', name_sw: 'Tawahudi (Autism)', name_en: 'Autism spectrum disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A03', name_sw: 'Matatizo ya ukuaji wa stadi za masomo', name_en: 'Developmental learning disorders', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A04', name_sw: 'Matatizo ya ukuaji wa uratibu wa mwendo', name_en: 'Developmental motor coordination disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A05', name_sw: 'Ugonjwa wa kukosa umakini na utiifu (ADHD)', name_en: 'Attention deficit hyperactivity disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A06', name_sw: 'Stereotyped movement disorder', name_en: 'Stereotyped movement disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A20', name_sw: 'Schizophrenia', name_en: 'Schizophrenia', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A21', name_sw: 'Schizoaffective disorder', name_en: 'Schizoaffective disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A22', name_sw: 'Schizotypal disorder', name_en: 'Schizotypal disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A23', name_sw: 'Acute and transient psychotic disorder', name_en: 'Acute and transient psychotic disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A24', name_sw: 'Delusional disorder', name_en: 'Delusional disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A40', name_sw: 'Bipolar aina I', name_en: 'Bipolar type I disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A41', name_sw: 'Bipolar aina II', name_en: 'Bipolar type II disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A42', name_sw: 'Cyclothymic disorder', name_en: 'Cyclothymic disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A70', name_sw: 'Mfadhaiko wa kipindi kimoja', name_en: 'Single episode depressive disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A71', name_sw: 'Mfadhaiko unaorudia rudia', name_en: 'Recurrent depressive disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A72', name_sw: 'Dysthymic disorder', name_en: 'Dysthymic disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6A73', name_sw: 'Mfadhaiko wa kabla ya hedhi', name_en: 'Mixed depressive and anxiety disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B00', name_sw: 'Generalized anxiety disorder', name_en: 'Generalized anxiety disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B01', name_sw: 'Panic disorder', name_en: 'Panic disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B02', name_sw: 'Agoraphobia', name_en: 'Agoraphobia', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B03', name_sw: 'Specific phobia', name_en: 'Specific phobia', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B04', name_sw: 'Social anxiety disorder', name_en: 'Social anxiety disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B05', name_sw: 'Separation anxiety disorder', name_en: 'Separation anxiety disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B06', name_sw: 'Selective mutism', name_en: 'Selective mutism', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B20', name_sw: 'OCD', name_en: 'Obsessive-compulsive disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B21', name_sw: 'Body dysmorphic disorder', name_en: 'Body dysmorphic disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B22', name_sw: 'Olfactory reference disorder', name_en: 'Olfactory reference disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B23', name_sw: 'Hypochondriasis', name_en: 'Hypochondriasis', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B24', name_sw: 'Hoarding disorder', name_en: 'Hoarding disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B40', name_sw: 'PTSD', name_en: 'Post traumatic stress disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B41', name_sw: 'Complex PTSD', name_en: 'Complex post traumatic stress disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B42', name_sw: 'Prolonged grief disorder', name_en: 'Prolonged grief disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B43', name_sw: 'Adjustment disorder', name_en: 'Adjustment disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B44', name_sw: 'Reactive attachment disorder', name_en: 'Reactive attachment disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B60', name_sw: 'Dissociative neurological symptom disorder', name_en: 'Dissociative neurological symptom disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B61', name_sw: 'Dissociative amnesia', name_en: 'Dissociative amnesia', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B64', name_sw: 'Dissociative identity disorder', name_en: 'Dissociative identity disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B80', name_sw: 'Anorexia nervosa', name_en: 'Anorexia nervosa', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B81', name_sw: 'Bulimia nervosa', name_en: 'Bulimia nervosa', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B82', name_sw: 'Binge eating disorder', name_en: 'Binge eating disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6B83', name_sw: 'Avoidant-restrictive food intake disorder', name_en: 'Avoidant-restrictive food intake disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C00', name_sw: 'Enuresis', name_en: 'Enuresis', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C40', name_sw: 'Matatizo ya pombe', name_en: 'Disorders due to use of alcohol', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C41', name_sw: 'Matatizo ya bangi', name_en: 'Disorders due to use of cannabis', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C42', name_sw: 'Matatizo ya opioids', name_en: 'Disorders due to use of opioids', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C43', name_sw: 'Matatizo ya sedatives', name_en: 'Disorders due to use of sedatives', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C44', name_sw: 'Matatizo ya kokeni', name_en: 'Disorders due to use of cocaine', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C45', name_sw: 'Matatizo ya stimulants', name_en: 'Disorders due to use of stimulants', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C46', name_sw: 'Matatizo ya hallucinogens', name_en: 'Disorders due to use of hallucinogens', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C47', name_sw: 'Matatizo ya tumbaku', name_en: 'Disorders due to use of nicotine', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C48', name_sw: 'Matatizo ya inhalants', name_en: 'Disorders due to use of volatile inhalants', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C50', name_sw: 'Kamari ya hatari', name_en: 'Gambling disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C51', name_sw: 'Michezo ya tarakilishi ya hatari', name_en: 'Gaming disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C70', name_sw: 'Impulse control disorder', name_en: 'Impulse control disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C71', name_sw: 'Pyromania', name_en: 'Pyromania', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C72', name_sw: 'Kleptomania', name_en: 'Kleptomania', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C90', name_sw: 'Oppositional defiant disorder', name_en: 'Oppositional defiant disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6C91', name_sw: 'Conduct-dissocial disorder', name_en: 'Conduct-dissocial disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D10', name_sw: 'Personality disorder', name_en: 'Personality disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D11', name_sw: 'Borderline pattern', name_en: 'Borderline pattern', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D30', name_sw: 'Paraphilic disorders', name_en: 'Paraphilic disorders', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D50', name_sw: 'Factitious disorder', name_en: 'Factitious disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D70', name_sw: 'Delirium', name_en: 'Delirium', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D71', name_sw: 'Mild neurocognitive disorder', name_en: 'Mild neurocognitive disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D72', name_sw: 'Amnestic disorder', name_en: 'Amnestic disorder', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D80', name_sw: 'Dementia ya Alzheimer', name_en: 'Dementia due to Alzheimer disease', chapter: '6', source: 'WHO ICD-11' },
  { code: '6D81', name_sw: 'Vascular dementia', name_en: 'Vascular dementia', chapter: '6', source: 'WHO ICD-11' },
  { code: '6E20', name_sw: 'Mental disorder due to HIV', name_en: 'Mental disorder due to HIV', chapter: '6', source: 'WHO ICD-11' },
  { code: '6E40', name_sw: 'Postpartum depression', name_en: 'Mental disorder associated with pregnancy', chapter: '6', source: 'WHO ICD-11' },

  // Chronic — Ch.5 endocrine / Ch.BA cardiovascular / Ch.CA respiratory / Ch.GB renal
  { code: '5A11', name_sw: 'Kisukari aina 1', name_en: 'Type 1 diabetes mellitus', chapter: '5', source: 'WHO ICD-11' },
  { code: '5A12', name_sw: 'Kisukari aina 2', name_en: 'Type 2 diabetes mellitus', chapter: '5', source: 'WHO ICD-11' },
  { code: 'BA00', name_sw: 'Shinikizo la juu la msingi', name_en: 'Essential hypertension', chapter: 'BA', source: 'WHO ICD-11' },
  { code: 'BA40', name_sw: 'Moyo kushindwa kufanya kazi', name_en: 'Heart failure', chapter: 'BA', source: 'WHO ICD-11' },
  { code: 'BA41', name_sw: 'Ugonjwa wa moyo wa ischaemic', name_en: 'Ischaemic heart disease', chapter: 'BA', source: 'WHO ICD-11' },
  { code: 'CA22', name_sw: 'Pumu', name_en: 'Asthma', chapter: 'CA', source: 'WHO ICD-11' },
  { code: 'CA23', name_sw: 'COPD', name_en: 'Chronic obstructive pulmonary disease', chapter: 'CA', source: 'WHO ICD-11' },
  { code: 'GB61', name_sw: 'Ugonjwa sugu wa figo (CKD)', name_en: 'Chronic kidney disease', chapter: 'GB', source: 'WHO ICD-11' },
  { code: 'GB62', name_sw: 'CKD hatua ya 5 (ESRD)', name_en: 'End stage renal disease', chapter: 'GB', source: 'WHO ICD-11' },
  { code: '2A00', name_sw: 'Saratani ya matiti', name_en: 'Malignant neoplasm of breast', chapter: '2', source: 'WHO ICD-11' },
  { code: '2B00', name_sw: 'Saratani ya shingo ya kizazi', name_en: 'Malignant neoplasm of cervix uteri', chapter: '2', source: 'WHO ICD-11' },
  { code: '2C00', name_sw: 'Saratani ya tezi dume', name_en: 'Malignant neoplasm of prostate', chapter: '2', source: 'WHO ICD-11' },
  { code: '2D00', name_sw: 'Saratani ya ini', name_en: 'Malignant neoplasm of liver', chapter: '2', source: 'WHO ICD-11' },
  { code: '1B10', name_sw: 'Kifua kikuu', name_en: 'Tuberculosis', chapter: '1', source: 'WHO ICD-11' },
  { code: '1C62', name_sw: 'VVU', name_en: 'HIV disease', chapter: '1', source: 'WHO ICD-11' },
  { code: '1C60', name_sw: 'UKIMWI', name_en: 'AIDS-defining condition', chapter: '1', source: 'WHO ICD-11' },
  { code: '3A00', name_sw: 'Sickle cell', name_en: 'Sickle cell disease', chapter: '3', source: 'WHO ICD-11' },
  { code: '3A01', name_sw: 'Anemia ya upungufu wa chuma', name_en: 'Iron deficiency anaemia', chapter: '3', source: 'WHO ICD-11' },
  { code: '8A60', name_sw: 'Kifafa', name_en: 'Epilepsy', chapter: '8', source: 'WHO ICD-11' },
  { code: '8A80', name_sw: 'Kiharusi', name_en: 'Stroke', chapter: '8', source: 'WHO ICD-11' },

  // Perinatal — Ch.JA pregnancy
  { code: 'JA00', name_sw: 'Mimba ya kawaida', name_en: 'Pregnancy', chapter: 'JA', source: 'WHO ICD-11' },
  { code: 'JA20', name_sw: 'Pre-eclampsia', name_en: 'Pre-eclampsia', chapter: 'JA', source: 'WHO ICD-11' },
  { code: 'JA21', name_sw: 'Eclampsia', name_en: 'Eclampsia', chapter: 'JA', source: 'WHO ICD-11' },
  { code: 'JA40', name_sw: 'Postpartum haemorrhage', name_en: 'Postpartum haemorrhage', chapter: 'JA', source: 'WHO ICD-11' },
  { code: 'JA60', name_sw: 'Postpartum depression (perinatal)', name_en: 'Mood disorder associated with pregnancy', chapter: 'JA', source: 'WHO ICD-11' },
  { code: 'JB00', name_sw: 'Gestational diabetes', name_en: 'Gestational diabetes', chapter: 'JA', source: 'WHO ICD-11' },

  // Sleep
  { code: '7A00', name_sw: 'Insomnia', name_en: 'Insomnia disorders', chapter: '7', source: 'WHO ICD-11' },
  { code: '7A20', name_sw: 'Hypersomnia', name_en: 'Hypersomnolence disorders', chapter: '7', source: 'WHO ICD-11' },
  { code: '7A40', name_sw: 'Sleep-related breathing disorders', name_en: 'Sleep-related breathing disorders', chapter: '7', source: 'WHO ICD-11' },

  // Self-harm (Ch.PB)
  { code: 'PB20', name_sw: 'Kujidhuru kwa kukusudia', name_en: 'Intentional self-harm', chapter: 'PB', source: 'WHO ICD-11' },
  { code: 'PB21', name_sw: 'Mawazo ya kujiua', name_en: 'Suicidal ideation', chapter: 'PB', source: 'WHO ICD-11' },
  { code: 'QE00', name_sw: 'Tatizo la kifamilia / mahusiano', name_en: 'Problems associated with family relationships', chapter: 'QE', source: 'WHO ICD-11' },
  { code: 'QE82', name_sw: 'Ukosefu wa ajira', name_en: 'Problem associated with unemployment', chapter: 'QE', source: 'WHO ICD-11' },
  { code: 'QE85', name_sw: 'Tatizo la makazi', name_en: 'Problem associated with housing or economic circumstances', chapter: 'QE', source: 'WHO ICD-11' },
];
