// redFlags.ts — top conditions with urgency triggers requiring ER referral.

export interface RedFlag {
  id: string;
  condition_sw: string;
  condition_en: string;
  triggers_sw: string[];
  triggers_en: string[];
  action_sw: string;
  urgency: 'urgent' | 'emergency';
  source: string;
}

export const RED_FLAGS: RedFlag[] = [
  { id: 'suicide', condition_sw: 'Mawazo ya kujiua', condition_en: 'Suicidal crisis',
    triggers_sw: ['Mpango wa kujiua', 'Njia ipo', 'Tarehe imewekwa', 'Maandalizi (wosia, kuagana)'],
    triggers_en: ['Active plan', 'Means available', 'Date set', 'Preparation (will, goodbyes)'],
    action_sw: 'Piga 112 au nenda hospitali ya rufaa moja kwa moja. Usiwe peke yako.', urgency: 'emergency',
    source: 'WHO mhGAP-IG SUI module + Tanzania STG' },
  { id: 'self-harm', condition_sw: 'Kujidhuru kwa nguvu', condition_en: 'Severe self-harm',
    triggers_sw: ['Damu nyingi', 'Jeraha kubwa', 'Sumu', 'Kuzimia'],
    triggers_en: ['Heavy bleeding', 'Deep wound', 'Poisoning', 'Loss of consciousness'],
    action_sw: 'Hospitali ya karibu sasa hivi. Piga 112.', urgency: 'emergency',
    source: 'WHO mhGAP-IG' },
  { id: 'psychosis-acute', condition_sw: 'Psychosis ya papo hapo', condition_en: 'Acute psychosis',
    triggers_sw: ['Vurugu', 'Hatari kwa wengine', 'Kushindwa kula/kunywa'],
    triggers_en: ['Violence', 'Danger to others', 'Refusal of food/water'],
    action_sw: 'Mwite mtaalamu wa afya ya akili au piga 112.', urgency: 'urgent',
    source: 'WHO mhGAP-IG PSY module' },
  { id: 'stroke', condition_sw: 'Kiharusi', condition_en: 'Stroke',
    triggers_sw: ['Uso umejipinda', 'Mkono mmoja dhaifu', 'Maneno hayatoki', 'Ghafla'],
    triggers_en: ['Face droop', 'Arm weakness', 'Speech slurred', 'Sudden onset'],
    action_sw: 'FAST → piga 112 ndani ya saa 4.', urgency: 'emergency',
    source: 'WHO STG + AHA' },
  { id: 'mi', condition_sw: 'Mshtuko wa moyo', condition_en: 'Myocardial infarction',
    triggers_sw: ['Maumivu makali kifuani', 'Yanasambaa mkono wa kushoto/taya', 'Jasho baridi', 'Kupumua kwa shida'],
    triggers_en: ['Severe chest pain', 'Radiates to left arm/jaw', 'Cold sweat', 'Shortness of breath'],
    action_sw: 'Piga 112 sasa. Aspirin 300mg ikitafunwa (kama haina mzio).', urgency: 'emergency',
    source: 'WHO STG' },
  { id: 'eclampsia', condition_sw: 'Eclampsia (mimba)', condition_en: 'Eclampsia',
    triggers_sw: ['Mshtuko (kifafa)', 'Maumivu makali ya kichwa + mimba', 'Kutoona vizuri', 'Maumivu ya tumbo la juu'],
    triggers_en: ['Seizure', 'Severe headache + pregnancy', 'Visual changes', 'Upper abdominal pain'],
    action_sw: 'Hospitali ya rufaa ya uzazi. MgSO4 IV mara moja.', urgency: 'emergency',
    source: 'Tanzania STG Maternal' },
  { id: 'pph', condition_sw: 'Kutokwa damu baada ya kujifungua', condition_en: 'Postpartum haemorrhage',
    triggers_sw: ['Damu >500mL', 'Wepesi', 'Mapigo ya haraka'],
    triggers_en: ['Bleeding >500mL', 'Light-headedness', 'Tachycardia'],
    action_sw: 'Oxytocin + uterine massage + rufaa ya haraka.', urgency: 'emergency',
    source: 'Tanzania STG Maternal' },
  { id: 'dka', condition_sw: 'DKA (kisukari)', condition_en: 'Diabetic ketoacidosis',
    triggers_sw: ['Pumzi ya matunda', 'Kichefuchefu', 'Kupumua kwa kasi', 'Sukari >15mmol/L'],
    triggers_en: ['Fruity breath', 'Nausea', 'Kussmaul breathing', 'Glucose >15mmol/L'],
    action_sw: 'Hospitali sasa. Maji ya IV + insulini IV.', urgency: 'emergency',
    source: 'WHO STG' },
  { id: 'severe-hypo', condition_sw: 'Hypoglycemia kali', condition_en: 'Severe hypoglycemia',
    triggers_sw: ['Kuzimia', 'Mshtuko', 'Sukari <3mmol/L'],
    triggers_en: ['Loss of consciousness', 'Seizure', 'Glucose <3mmol/L'],
    action_sw: 'Sukari ya haraka (juice/sukari) kama anaweza kumeza. Hospitali kama hapana.', urgency: 'emergency',
    source: 'WHO STG' },
  { id: 'hypertensive-crisis', condition_sw: 'Shinikizo la hatari (>180/120)', condition_en: 'Hypertensive emergency',
    triggers_sw: ['BP >180/120 na dalili (kichwa kuuma sana, kifua, mabadiliko ya maono)'],
    triggers_en: ['BP >180/120 with symptoms (severe headache, chest pain, vision changes)'],
    action_sw: 'Hospitali ya karibu kwa BP control ya IV.', urgency: 'emergency',
    source: 'WHO STG + NICE NG136' },
  { id: 'sepsis', condition_sw: 'Sepsis', condition_en: 'Sepsis',
    triggers_sw: ['Homa + kupumua haraka >22', 'BP <90', 'Akili imechanganyikiwa'],
    triggers_en: ['Fever + RR >22', 'SBP <90', 'Altered mental state'],
    action_sw: 'Hospitali sasa. Antibiotics ndani ya saa 1.', urgency: 'emergency',
    source: 'Surviving Sepsis 2021' },
  { id: 'asthma-severe', condition_sw: 'Pumu kali', condition_en: 'Severe asthma',
    triggers_sw: ['Kushindwa kuongea sentensi nzima', 'SpO2 <92%', 'Salbutamol haitoshi'],
    triggers_en: ['Cannot complete sentences', 'SpO2 <92%', 'Salbutamol not working'],
    action_sw: 'Salbutamol + steroids + oxygen. Hospitali ya karibu.', urgency: 'emergency',
    source: 'GINA 2024 + Tanzania STG' },
  { id: 'tb-haemoptysis', condition_sw: 'TB + kutema damu', condition_en: 'TB with haemoptysis',
    triggers_sw: ['Damu nyingi kupitia mdomo', 'Kupungua nguvu kwa kasi'],
    triggers_en: ['Massive haemoptysis', 'Rapid deterioration'],
    action_sw: 'Hospitali ya rufaa ya TB.', urgency: 'urgent',
    source: 'NTLP Tanzania' },
  { id: 'hiv-oi', condition_sw: 'OI ya VVU (CD4 chini)', condition_en: 'HIV opportunistic infection',
    triggers_sw: ['Homa ndefu', 'Kupungua uzito haraka', 'Kuhara kwa wiki', 'Kifua kibaya'],
    triggers_en: ['Persistent fever', 'Rapid weight loss', 'Chronic diarrhoea', 'Severe respiratory illness'],
    action_sw: 'CTC kwa tathmini. Anza/rejea ART + cotrimoxazole.', urgency: 'urgent',
    source: 'NACP Tanzania' },
  { id: 'ckd-emergency', condition_sw: 'Dharura ya figo', condition_en: 'Renal emergency',
    triggers_sw: ['Hakuna mkojo masaa 12', 'Uvimbe wa mwili mzima', 'Kupumua kwa shida', 'K >6'],
    triggers_en: ['Anuria 12h', 'Anasarca', 'SOB (pulmonary oedema)', 'K >6'],
    action_sw: 'Hospitali ya rufaa kwa dialysis tathmini.', urgency: 'emergency',
    source: 'KDIGO + Tanzania STG' },
  { id: 'sickle-crisis', condition_sw: 'Mgogoro wa sickle cell', condition_en: 'Sickle cell crisis',
    triggers_sw: ['Maumivu makali', 'Kifua kuuma + homa', 'Splenic sequestration'],
    triggers_en: ['Severe pain', 'Acute chest syndrome', 'Splenic sequestration'],
    action_sw: 'Hospitali — analgesia, maji ya IV, oxygen.', urgency: 'emergency',
    source: 'WHO + MUHAS sickle guidelines' },
  { id: 'overdose', condition_sw: 'Overdose ya dawa/opioids', condition_en: 'Drug overdose',
    triggers_sw: ['Kupumua polepole', 'Vidonge vya jicho vidogo (opioid)', 'Kuzimia'],
    triggers_en: ['Slow breathing', 'Pinpoint pupils (opioid)', 'Unresponsive'],
    action_sw: 'Naloxone ikipatikana. Piga 112 mara moja.', urgency: 'emergency',
    source: 'WHO STG' },
  { id: 'ipv-imminent', condition_sw: 'Hatari ya unyanyasaji wa karibu', condition_en: 'Imminent IPV',
    triggers_sw: ['Tishio la sasa', 'Silaha nyumbani', 'Watoto hatarini'],
    triggers_en: ['Active threat', 'Weapon at home', 'Children at risk'],
    action_sw: 'Polisi 112 / Gender Desk. Safe place sasa.', urgency: 'emergency',
    source: 'WHO LIVES + Tanzania Gender Desk protocol' },
  { id: 'child-severe', condition_sw: 'Mtoto mgonjwa sana', condition_en: 'Severely ill child',
    triggers_sw: ['Hawezi kunyonya/kunywa', 'Kupumua kwa shida', 'Kifafa', 'Joto sana'],
    triggers_en: ['Cannot drink/breastfeed', 'Respiratory distress', 'Seizure', 'High fever'],
    action_sw: 'IMCI danger signs → hospitali ya karibu.', urgency: 'emergency',
    source: 'WHO IMCI Tanzania' },
  { id: 'pregnancy-bleed', condition_sw: 'Kutokwa damu wakati wa mimba', condition_en: 'Pregnancy bleeding',
    triggers_sw: ['Damu kwenye T2/T3', 'Maumivu ya tumbo', 'Hakuna mwendo wa mtoto'],
    triggers_en: ['Bleeding T2/T3', 'Abdominal pain', 'Decreased fetal movement'],
    action_sw: 'Hospitali ya uzazi mara moja.', urgency: 'emergency',
    source: 'Tanzania STG Maternal' },
];
