// tmdaMeds.ts — Tanzania EML medication knowledge, sovereign.
// 50 real entries used by Tumaini. Source: TMDA + Tanzania STG + WHO EML.

export interface TmdaMed {
  id: string;
  name_sw: string;
  name_en: string;
  generic: string;
  class: string;
  indications: string[];
  contraindications: string[];
  side_effects: string[];
  interactions: string[];
  source: 'TMDA Tanzania EML';
  verified: boolean;
}

export const TMDA_MEDS: TmdaMed[] = [
  // === HIV ART ===
  { id: 'tdf', name_sw: 'Tenofoviri (TDF)', name_en: 'Tenofovir disoproxil', generic: 'Tenofovir DF 300mg', class: 'NRTI',
    indications: ['VVU/UKIMWI', 'PrEP', 'Hepatitis B'],
    contraindications: ['Ugonjwa wa figo (CrCl <50)', 'Mzio wa tenofoviri'],
    side_effects: ['Kichefuchefu', 'Maumivu ya kichwa', 'Kupungua kwa kazi ya figo', 'Kupungua wiani wa mfupa'],
    interactions: ['Didanosine', 'Adefovir', 'NSAIDs ndefu'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: '3tc', name_sw: 'Lamivudini (3TC)', name_en: 'Lamivudine', generic: 'Lamivudine 300mg', class: 'NRTI',
    indications: ['VVU', 'Hepatitis B'],
    contraindications: ['Mzio'],
    side_effects: ['Kichwa kuuma', 'Uchovu', 'Kichefuchefu'],
    interactions: ['Trimethoprim'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'dtg', name_sw: 'Dolutegraviri (DTG)', name_en: 'Dolutegravir', generic: 'Dolutegravir 50mg', class: 'INSTI',
    indications: ['VVU — mstari wa kwanza'],
    contraindications: ['Matumizi pamoja na dofetilide'],
    side_effects: ['Kukosa usingizi', 'Maumivu ya kichwa', 'Kuongezeka uzito'],
    interactions: ['Metformini (fuatilia)', 'Rifampicin', 'Antacids zenye chuma/kalsiamu'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'efv', name_sw: 'Efavirenzi (EFV)', name_en: 'Efavirenz', generic: 'Efavirenz 600mg', class: 'NNRTI',
    indications: ['VVU'],
    contraindications: ['Mimba ya mapema (kihistoria)', 'Magonjwa makubwa ya akili'],
    side_effects: ['Ndoto za kushtua', 'Kizunguzungu', 'Upele', 'Mabadiliko ya hisia'],
    interactions: ['Rifampicin', 'Methadone', 'Warfarin'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'azt', name_sw: 'Zidovudini (AZT)', name_en: 'Zidovudine', generic: 'Zidovudine 300mg', class: 'NRTI',
    indications: ['VVU', 'PMTCT'],
    contraindications: ['Anemia kali (Hb<8)', 'Neutropenia'],
    side_effects: ['Anemia', 'Kichefuchefu', 'Maumivu ya kichwa'],
    interactions: ['Stavudine', 'Ganciclovir'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'abc', name_sw: 'Abacaviri (ABC)', name_en: 'Abacavir', generic: 'Abacavir 600mg', class: 'NRTI',
    indications: ['VVU'],
    contraindications: ['HLA-B*5701 chanya', 'Mzio uliopita'],
    side_effects: ['Mzio wa kuhatarisha maisha', 'Homa', 'Upele'],
    interactions: ['Methadone'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'atv-r', name_sw: 'Atazanaviri/Ritonaviri', name_en: 'Atazanavir/Ritonavir', generic: 'ATV 300mg + RTV 100mg', class: 'PI',
    indications: ['VVU — mstari wa pili'],
    contraindications: ['PPI ya muda mrefu', 'Ugonjwa mkubwa wa ini'],
    side_effects: ['Manjano (hyperbilirubinemia)', 'Vijiwe vya figo', 'Kichefuchefu'],
    interactions: ['PPIs', 'Rifampicin', 'Simvastatin'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'lpv-r', name_sw: 'Lopinaviri/Ritonaviri', name_en: 'Lopinavir/Ritonavir', generic: 'LPV/r 200/50mg', class: 'PI',
    indications: ['VVU watoto', 'VVU mstari wa pili'],
    contraindications: ['Ergot alkaloids'],
    side_effects: ['Kuhara', 'Kichefuchefu', 'Lipid kuongezeka'],
    interactions: ['Rifampicin', 'Statins', 'Methadone'],
    source: 'TMDA Tanzania EML', verified: true },

  // === BP ===
  { id: 'amlodipine', name_sw: 'Amlodipini', name_en: 'Amlodipine', generic: 'Amlodipine 5/10mg', class: 'CCB',
    indications: ['Shinikizo la juu', 'Angina'],
    contraindications: ['Mshtuko wa moyo', 'Shinikizo la chini sana'],
    side_effects: ['Uvimbe wa miguu', 'Kichwa kuuma', 'Kuwaka usoni'],
    interactions: ['Simvastatin (zaidi ya 20mg)', 'Diltiazem'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'enalapril', name_sw: 'Enalaprili', name_en: 'Enalapril', generic: 'Enalapril 5/10/20mg', class: 'ACE-I',
    indications: ['Shinikizo la juu', 'Moyo kushindwa kufanya kazi', 'Nephroprotection'],
    contraindications: ['Mimba', 'Angioedema', 'Hyperkalemia'],
    side_effects: ['Kikohozi kikavu', 'Hyperkalemia', 'Angioedema (nadra)'],
    interactions: ['Potassium-sparing diuretics', 'NSAIDs', 'Lithium'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'losartan', name_sw: 'Losartani', name_en: 'Losartan', generic: 'Losartan 50/100mg', class: 'ARB',
    indications: ['Shinikizo', 'Nephroprotection ya kisukari'],
    contraindications: ['Mimba'],
    side_effects: ['Kichwa kuuma', 'Kizunguzungu', 'Hyperkalemia'],
    interactions: ['NSAIDs', 'Potassium supplements'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'hctz', name_sw: 'Hydrochlorothiazide', name_en: 'Hydrochlorothiazide', generic: 'HCTZ 25mg', class: 'Thiazide diuretic',
    indications: ['Shinikizo', 'Edema'],
    contraindications: ['Anuria', 'Mzio wa sulfa'],
    side_effects: ['Hypokalemia', 'Hyperuricemia', 'Hyperglycemia'],
    interactions: ['Digoxin', 'Lithium'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'atenolol', name_sw: 'Atenoloi', name_en: 'Atenolol', generic: 'Atenolol 50/100mg', class: 'Beta-blocker',
    indications: ['Shinikizo', 'Angina', 'Mapigo ya haraka'],
    contraindications: ['Pumu kali', 'Heart block', 'Bradycardia'],
    side_effects: ['Uchovu', 'Mikono baridi', 'Bradycardia'],
    interactions: ['Verapamil', 'Insulin (huficha hypo)'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'furosemide', name_sw: 'Furosemidi (Lasix)', name_en: 'Furosemide', generic: 'Furosemide 40mg', class: 'Loop diuretic',
    indications: ['Moyo kushindwa', 'Edema', 'CKD overload'],
    contraindications: ['Anuria', 'Hypokalemia kali'],
    side_effects: ['Hypokalemia', 'Hypotension', 'Ototoxicity (IV haraka)'],
    interactions: ['Aminoglycosides', 'Lithium', 'Digoxin'],
    source: 'TMDA Tanzania EML', verified: true },

  // === DM ===
  { id: 'metformin', name_sw: 'Metformini', name_en: 'Metformin', generic: 'Metformin 500/1000mg', class: 'Biguanide',
    indications: ['Kisukari aina 2', 'PCOS'],
    contraindications: ['eGFR <30', 'Lactic acidosis hatari', 'Hepatic failure'],
    side_effects: ['Kuhara', 'Kichefuchefu', 'B12 deficiency'],
    interactions: ['Contrast IV', 'Alcohol nyingi', 'Dolutegravir (fuatilia)'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'glibenclamide', name_sw: 'Glibenkalamidi', name_en: 'Glibenclamide', generic: 'Glibenclamide 5mg', class: 'Sulfonylurea',
    indications: ['Kisukari aina 2'],
    contraindications: ['Aina 1', 'Mzio wa sulfa', 'CKD'],
    side_effects: ['Hypoglycemia', 'Kuongezeka uzito'],
    interactions: ['Beta-blockers', 'Fluconazole'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'insulin-r', name_sw: 'Insulini ya kawaida', name_en: 'Soluble (Regular) Insulin', generic: 'Insulin R 100IU/mL', class: 'Insulin',
    indications: ['Kisukari aina 1 na 2', 'DKA', 'Hyperkalemia'],
    contraindications: ['Hypoglycemia ya sasa'],
    side_effects: ['Hypoglycemia', 'Lipohypertrophy', 'Kuongezeka uzito'],
    interactions: ['Beta-blockers (huficha hypo)', 'Steroids', 'Pombe'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'insulin-n', name_sw: 'Insulini NPH', name_en: 'Isophane (NPH) Insulin', generic: 'Insulin NPH 100IU/mL', class: 'Insulin',
    indications: ['Kisukari (basal)'],
    contraindications: ['Hypoglycemia ya sasa'],
    side_effects: ['Hypoglycemia ya usiku', 'Lipohypertrophy'],
    interactions: ['Steroids', 'Pombe'],
    source: 'TMDA Tanzania EML', verified: true },

  // === Mental health ===
  { id: 'fluoxetine', name_sw: 'Fluoxetini', name_en: 'Fluoxetine', generic: 'Fluoxetine 20mg', class: 'SSRI',
    indications: ['Mfadhaiko', 'OCD', 'Bulimia'],
    contraindications: ['MAOI ndani ya wiki 2', 'Pimozide'],
    side_effects: ['Kichefuchefu', 'Kukosa hamu ya kula', 'Kukosa hamu ya tendo', 'Kukosa usingizi'],
    interactions: ['Tramadol', 'Warfarin', 'MAOIs', 'NSAIDs (kutokwa damu)'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'sertraline', name_sw: 'Sertralini', name_en: 'Sertraline', generic: 'Sertraline 50/100mg', class: 'SSRI',
    indications: ['Mfadhaiko', 'Wasiwasi', 'PTSD', 'OCD'],
    contraindications: ['MAOI ndani ya wiki 2'],
    side_effects: ['Kuhara', 'Kichefuchefu', 'Kukosa hamu ya tendo'],
    interactions: ['Warfarin', 'MAOIs', 'Tramadol'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'amitriptyline', name_sw: 'Amitriptilini', name_en: 'Amitriptyline', generic: 'Amitriptyline 25mg', class: 'TCA',
    indications: ['Mfadhaiko', 'Maumivu ya mishipa', 'Kichwa cha mvuto'],
    contraindications: ['Mshtuko wa moyo wa hivi karibuni', 'MAOI', 'Glaucoma kali'],
    side_effects: ['Kinywa kavu', 'Kuvimbiwa', 'Usingizi', 'Tachycardia'],
    interactions: ['MAOIs', 'SSRIs', 'Anticholinergics'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'risperidone', name_sw: 'Risperidoni', name_en: 'Risperidone', generic: 'Risperidone 2mg', class: 'Atypical antipsychotic',
    indications: ['Schizophrenia', 'Bipolar mania', 'Agitation kali'],
    contraindications: ['Mzio'],
    side_effects: ['Kuongezeka uzito', 'EPS', 'Hyperprolactinemia', 'Sedation'],
    interactions: ['Carbamazepine', 'Fluoxetine'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'haloperidol', name_sw: 'Halopeidoli', name_en: 'Haloperidol', generic: 'Haloperidol 5mg', class: 'Typical antipsychotic',
    indications: ['Schizophrenia', 'Agitation', 'Delirium'],
    contraindications: ['Parkinson', 'CNS depression kali'],
    side_effects: ['EPS', 'Tardive dyskinesia', 'QT prolongation'],
    interactions: ['QT-prolonging drugs', 'Levodopa'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'diazepam', name_sw: 'Diazepamu', name_en: 'Diazepam', generic: 'Diazepam 5mg', class: 'Benzodiazepine',
    indications: ['Wasiwasi mkali wa muda mfupi', 'Status epilepticus', 'Alcohol withdrawal'],
    contraindications: ['Pumu kali', 'Myasthenia gravis', 'Sleep apnea'],
    side_effects: ['Sedation', 'Utegemezi', 'Kuanguka kwa wazee'],
    interactions: ['Opioids (HATARI)', 'Pombe', 'CYP3A4 inhibitors'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'carbamazepine', name_sw: 'Karbamazepini', name_en: 'Carbamazepine', generic: 'Carbamazepine 200mg', class: 'Anticonvulsant/mood stabilizer',
    indications: ['Kifafa', 'Bipolar', 'Trigeminal neuralgia'],
    contraindications: ['Bone marrow suppression', 'MAOI'],
    side_effects: ['Stevens-Johnson (HLA-B*1502)', 'Hyponatremia', 'Diplopia'],
    interactions: ['Warfarin', 'OCPs', 'Dolutegravir'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'phenobarbital', name_sw: 'Fenobabitali', name_en: 'Phenobarbital', generic: 'Phenobarbital 30/60mg', class: 'Barbiturate',
    indications: ['Kifafa', 'Neonatal seizures'],
    contraindications: ['Porphyria', 'Respiratory depression'],
    side_effects: ['Sedation', 'Ataxia', 'Cognitive dulling'],
    interactions: ['Warfarin', 'OCPs', 'ARVs'],
    source: 'TMDA Tanzania EML', verified: true },

  // === Antibiotics ===
  { id: 'amoxicillin', name_sw: 'Amoksisilini', name_en: 'Amoxicillin', generic: 'Amoxicillin 500mg', class: 'Penicillin',
    indications: ['Maambukizi ya kifua', 'UTI', 'Otitis media'],
    contraindications: ['Mzio wa penicillin'],
    side_effects: ['Kuhara', 'Upele', 'Candidiasis'],
    interactions: ['Methotrexate', 'OCPs (kupungua)'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'azithromycin', name_sw: 'Azitromaisini', name_en: 'Azithromycin', generic: 'Azithromycin 500mg', class: 'Macrolide',
    indications: ['Pneumonia', 'Chlamydia', 'Trachoma'],
    contraindications: ['QT-prolongation hatari'],
    side_effects: ['Kichefuchefu', 'Kuhara', 'QT prolongation'],
    interactions: ['Warfarin', 'Digoxin', 'Statins'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'ciprofloxacin', name_sw: 'Siprofloksasini', name_en: 'Ciprofloxacin', generic: 'Ciprofloxacin 500mg', class: 'Fluoroquinolone',
    indications: ['UTI', 'Typhoid', 'GI infections'],
    contraindications: ['Watoto <18 (relative)', 'Mimba'],
    side_effects: ['Tendinopathy', 'QT prolongation', 'C. difficile'],
    interactions: ['Antacids', 'Theophylline', 'Warfarin'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'cotrimoxazole', name_sw: 'Kotrimoksazoli', name_en: 'Co-trimoxazole', generic: 'TMP-SMX 480mg', class: 'Sulfa antibiotic',
    indications: ['PCP prophylaxis (VVU)', 'UTI', 'Toxoplasma prophylaxis'],
    contraindications: ['Mzio wa sulfa', 'G6PD', 'Trimester 1 ya mimba'],
    side_effects: ['Upele', 'Hyperkalemia', 'Marrow suppression'],
    interactions: ['Warfarin', 'Methotrexate', 'ACE-I'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'doxycycline', name_sw: 'Doksaisikilini', name_en: 'Doxycycline', generic: 'Doxycycline 100mg', class: 'Tetracycline',
    indications: ['Malaria prophylaxis', 'Chlamydia', 'Acne', 'Rickettsia'],
    contraindications: ['Mimba', 'Watoto <8'],
    side_effects: ['Photosensitivity', 'Esophagitis', 'GI upset'],
    interactions: ['Antacids', 'Iron', 'Warfarin'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'metronidazole', name_sw: 'Metronidazoli', name_en: 'Metronidazole', generic: 'Metronidazole 400mg', class: 'Nitroimidazole',
    indications: ['Anaerobic infections', 'Trichomonas', 'C. difficile', 'BV'],
    contraindications: ['Trimester 1', 'Pombe'],
    side_effects: ['Ladha ya chuma', 'Disulfiram reaction na pombe', 'Peripheral neuropathy'],
    interactions: ['Pombe', 'Warfarin', 'Lithium'],
    source: 'TMDA Tanzania EML', verified: true },

  // === TB ===
  { id: 'rifampicin', name_sw: 'Rifampisini', name_en: 'Rifampicin', generic: 'Rifampicin 150/300mg', class: 'Anti-TB (RIPE)',
    indications: ['Kifua kikuu', 'Leprosy'],
    contraindications: ['Hepatic failure', 'Porphyria'],
    side_effects: ['Mkojo wa rangi ya machungwa', 'Hepatotoxicity', 'Flu syndrome'],
    interactions: ['ARVs (PIs, DTG)', 'Warfarin', 'OCPs', 'Methadone'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'isoniazid', name_sw: 'Aizoniazidi (INH)', name_en: 'Isoniazid', generic: 'Isoniazid 300mg', class: 'Anti-TB',
    indications: ['Kifua kikuu', 'LTBI prophylaxis'],
    contraindications: ['Liver disease ya kazi'],
    side_effects: ['Peripheral neuropathy (toa pyridoxine)', 'Hepatitis'],
    interactions: ['Phenytoin', 'Pombe', 'Carbamazepine'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'pyrazinamide', name_sw: 'Pyrazinamidi', name_en: 'Pyrazinamide', generic: 'Pyrazinamide 500mg', class: 'Anti-TB',
    indications: ['Kifua kikuu — awamu kuu'],
    contraindications: ['Severe liver', 'Acute gout'],
    side_effects: ['Hyperuricemia', 'Hepatotoxicity', 'Arthralgia'],
    interactions: ['Allopurinol'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'ethambutol', name_sw: 'Ethambutoli', name_en: 'Ethambutol', generic: 'Ethambutol 400mg', class: 'Anti-TB',
    indications: ['Kifua kikuu'],
    contraindications: ['Optic neuritis'],
    side_effects: ['Optic neuritis (visual)', 'Color blindness'],
    interactions: ['Antacids'],
    source: 'TMDA Tanzania EML', verified: true },

  // === Pain ===
  { id: 'paracetamol', name_sw: 'Paracetamoli', name_en: 'Paracetamol', generic: 'Paracetamol 500mg', class: 'Analgesic',
    indications: ['Maumivu hafifu-wastani', 'Homa'],
    contraindications: ['Liver failure'],
    side_effects: ['Hepatotoxicity (overdose)'],
    interactions: ['Warfarin (dosi kubwa)', 'Pombe'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'ibuprofen', name_sw: 'Ibuprofeni', name_en: 'Ibuprofen', generic: 'Ibuprofen 400mg', class: 'NSAID',
    indications: ['Maumivu', 'Inflammation', 'Homa'],
    contraindications: ['CKD', 'PUD', 'Mimba T3', 'Heart failure'],
    side_effects: ['GI bleed', 'AKI', 'BP kuongezeka'],
    interactions: ['ACE-I', 'Warfarin', 'Lithium', 'Methotrexate'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'morphine', name_sw: 'Mofini', name_en: 'Morphine', generic: 'Morphine 10mg/mL', class: 'Opioid',
    indications: ['Maumivu makali', 'Saratani', 'Palliative'],
    contraindications: ['Respiratory depression', 'Paralytic ileus'],
    side_effects: ['Sedation', 'Kuvimbiwa', 'Respiratory depression', 'Utegemezi'],
    interactions: ['Benzodiazepines (HATARI)', 'MAOIs', 'Pombe'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'tramadol', name_sw: 'Tramadoli', name_en: 'Tramadol', generic: 'Tramadol 50mg', class: 'Opioid',
    indications: ['Maumivu wastani-makali'],
    contraindications: ['Seizures', 'MAOI', 'Watoto <12'],
    side_effects: ['Kichefuchefu', 'Sedation', 'Serotonin syndrome'],
    interactions: ['SSRIs', 'MAOIs', 'Warfarin'],
    source: 'TMDA Tanzania EML', verified: true },

  // === Dialysis-related / renal ===
  { id: 'epo', name_sw: 'Erithropoyetini (EPO)', name_en: 'Erythropoietin', generic: 'Epoetin alfa 4000IU', class: 'ESA',
    indications: ['CKD anemia', 'Dialysis anemia'],
    contraindications: ['BP isiyodhibitiwa', 'Pure red cell aplasia'],
    side_effects: ['BP kuongezeka', 'Thrombosis', 'Headache'],
    interactions: ['Iron deficiency (lazima ujaze iron)'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'caco3', name_sw: 'Kalsiamu kabonati', name_en: 'Calcium carbonate', generic: 'CaCO3 500mg', class: 'Phosphate binder',
    indications: ['Hyperphosphatemia ya CKD'],
    contraindications: ['Hypercalcemia'],
    side_effects: ['Kuvimbiwa', 'Hypercalcemia'],
    interactions: ['Levothyroxine', 'Iron', 'Fluoroquinolones'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'sevelamer', name_sw: 'Sevelameri', name_en: 'Sevelamer', generic: 'Sevelamer 800mg', class: 'Phosphate binder',
    indications: ['CKD hyperphosphatemia'],
    contraindications: ['Bowel obstruction'],
    side_effects: ['GI upset', 'Kuvimbiwa'],
    interactions: ['Levothyroxine', 'Mycophenolate'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'calcitriol', name_sw: 'Kalsitrioli', name_en: 'Calcitriol', generic: 'Calcitriol 0.25mcg', class: 'Vitamin D',
    indications: ['CKD-MBD', 'Hypoparathyroidism'],
    contraindications: ['Hypercalcemia'],
    side_effects: ['Hypercalcemia', 'Hyperphosphatemia'],
    interactions: ['Thiazides', 'Digoxin'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'heparin', name_sw: 'Hepaini', name_en: 'Heparin (UFH)', generic: 'Heparin 5000IU/mL', class: 'Anticoagulant',
    indications: ['Dialysis circuit', 'DVT/PE', 'ACS'],
    contraindications: ['Active bleeding', 'HIT'],
    side_effects: ['Kutokwa damu', 'HIT', 'Osteoporosis'],
    interactions: ['NSAIDs', 'Warfarin'],
    source: 'TMDA Tanzania EML', verified: true },

  // === Other essentials ===
  { id: 'folic', name_sw: 'Asidi ya foliki', name_en: 'Folic acid', generic: 'Folic acid 5mg', class: 'Vitamin',
    indications: ['Mimba — NTD prevention', 'Megaloblastic anemia', 'Methotrexate cover'],
    contraindications: ['B12 deficiency isiyotibiwa'],
    side_effects: ['Nadra'],
    interactions: ['Methotrexate', 'Phenytoin'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'iron-ferrous', name_sw: 'Chuma (Ferrous sulfate)', name_en: 'Ferrous sulfate', generic: 'FeSO4 200mg', class: 'Iron supplement',
    indications: ['Iron deficiency anemia', 'Mimba'],
    contraindications: ['Hemochromatosis', 'PUD ya kazi'],
    side_effects: ['Kuvimbiwa', 'Kichefuchefu', 'Mavi meusi'],
    interactions: ['Levothyroxine', 'Tetracyclines', 'Quinolones'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'oxytocin', name_sw: 'Oksitosini', name_en: 'Oxytocin', generic: 'Oxytocin 10IU/mL', class: 'Uterotonic',
    indications: ['Active 3rd stage', 'PPH', 'Induction'],
    contraindications: ['Cephalopelvic disproportion', 'Fetal distress'],
    side_effects: ['Water intoxication', 'Hypotension', 'Uterine rupture'],
    interactions: ['Prostaglandins'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'magnesium-sulfate', name_sw: 'Magnesi sulfati', name_en: 'Magnesium sulfate', generic: 'MgSO4 50%', class: 'Anticonvulsant',
    indications: ['Eclampsia', 'Pre-eclampsia kali', 'Preterm neuroprotection'],
    contraindications: ['Myasthenia gravis', 'Heart block'],
    side_effects: ['Respiratory depression', 'Loss of reflexes'],
    interactions: ['CCBs', 'Neuromuscular blockers'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'methadone', name_sw: 'Methadoni', name_en: 'Methadone', generic: 'Methadone 5mg/mL', class: 'Opioid maintenance',
    indications: ['OAT — heroin addiction (MAT Tanzania)'],
    contraindications: ['Respiratory depression', 'QT >500ms'],
    side_effects: ['QT prolongation', 'Sedation', 'Kuvimbiwa'],
    interactions: ['Rifampicin', 'EFV', 'Benzodiazepines'],
    source: 'TMDA Tanzania EML', verified: true },
  { id: 'naloxone', name_sw: 'Naloksoni', name_en: 'Naloxone', generic: 'Naloxone 0.4mg/mL', class: 'Opioid antagonist',
    indications: ['Opioid overdose'],
    contraindications: ['Hakuna kwa overdose ya kweli'],
    side_effects: ['Withdrawal kali kwa mtegemezi'],
    interactions: ['Hakuna muhimu'],
    source: 'TMDA Tanzania EML', verified: true },
];
